fields:
- mode: NULLABLE
  name: destination_id
  type: STRING
- mode: NULLABLE
  name: destination_name
  type: STRING
- mode: NULLABLE
  name: account_id
  type: STRING
- mode: NULLABLE
  name: created_at
  type: TIMESTAMP
- mode: NULLABLE
  name: region
  type: STRING
