fields:
- name: id
  type: INTEGER
  mode: NULLABLE
- name: _fivetran_synced
  type: TIMESTAMP
  mode: NULLABLE
- name: name
  type: STRING
  mode: NULLABLE
- name: color_name
  type: STRING
  mode: NULLABLE
- name: key
  type: STRING
  mode: NULLABLE
