fields:
- description: null
  mode: NULLABLE
  name: id
  type: INTEGER
- description: null
  mode: NULLABLE
  name: dag_id
  type: STRING
- description: null
  mode: NULLABLE
  name: executor_class
  type: STRING
- description: null
  mode: NULLABLE
  name: hostname
  type: STRING
- description: null
  mode: NULLABLE
  name: job_type
  type: STRING
- description: null
  mode: NULLABLE
  name: state
  type: STRING
- description: null
  mode: NULLABLE
  name: unixname
  type: STRING
- description: null
  mode: NULLABLE
  name: start_date
  type: TIMESTAMP
- description: null
  mode: NULLABLE
  name: end_date
  type: TIMESTAMP
- description: null
  mode: NULLABLE
  name: latest_heartbeat
  type: TIMESTAMP
