fields:
- mode: NULLABLE
  name: cohort_date
  type: DATE
- mode: NULLABLE
  name: product
  type: STRING
- mode: NULLABLE
  name: app_version
  type: STRING
- mode: NULLABLE
  name: os
  type: STRING
- mode: NULLABLE
  name: normalized_channel
  type: STRING
- mode: NULLABLE
  name: country
  type: STRING
- mode: NULLABLE
  name: new_profiles
  type: INTEGER
- mode: NULLABLE
  name: day_2_7_activated
  type: INTEGER
