fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: version_major
  type: INTEGER
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: platform
  type: STRING
  mode: NULLABLE
- name: use_counter_content_documents_destroyed
  type: INTEGER
  mode: NULLABLE
- name: use_counter_top_level_content_documents_destroyed
  type: INTEGER
  mode: NULLABLE
- name: use_counter_service_workers_destroyed
  type: INTEGER
  mode: NULLABLE
- name: use_counter_shared_workers_destroyed
  type: INTEGER
  mode: NULLABLE
- name: use_counter_dedicated_workers_destroyed
  type: INTEGER
  mode: NULLABLE
- name: metric
  type: STRING
  mode: NULLABLE
- name: cnt
  type: INTEGER
  mode: NULLABLE
- name: rate
  type: NUMERIC
  mode: NULLABLE
