fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: The date when the ingestion edge server accepted this message
- name: version_major
  type: INTEGER
  mode: NULLABLE
  description: The user visible main portion of version string (e.g. 1, 2, etc).
- name: country
  type: STRING
  mode: NULLABLE
  description: Results of a geographic lookup based on the client's IP address; An
    ISO 3166-1 alpha-2 country code
- name: platform
  type: STRING
  mode: NULLABLE
  description: Indicates if the data is from Firefox Desktop or Mobile (Fenix)
- name: use_counter_content_documents_destroyed
  type: INTEGER
  mode: NULLABLE
  description: Use Counter Content Documents Destroyed - Denominator for Document
    Metrics
- name: use_counter_top_level_content_documents_destroyed
  type: INTEGER
  mode: NULLABLE
  description: Use Counter Top Level Content Documents Destroyed - Denominator for
    Page Metrics
- name: use_counter_service_workers_destroyed
  type: INTEGER
  mode: NULLABLE
  description: Use Counter Service Workers Destroyed - Denominator for Service Worker
    Metrics
- name: use_counter_shared_workers_destroyed
  type: INTEGER
  mode: NULLABLE
  description: Use Counter Shared Workers Destroyed - Denominator for Shared Worker
    Metrics
- name: use_counter_dedicated_workers_destroyed
  type: INTEGER
  mode: NULLABLE
  description: Use Counter Dedicated Workers Destroyed - Denominator for Dedicated
    Worker Metrics
- name: metric
  type: STRING
  mode: NULLABLE
  description: The name of the metric; naming matches that found in the Glean dictionary
- name: cnt
  type: INTEGER
  mode: NULLABLE
  description: The count for this metric
- name: rate
  type: NUMERIC
  mode: NULLABLE
  description: Usage rate; denominator depends on if metric is a doc, page, worker
    shared, worker service, or worker dedicated type of metric.
