fields:
- description: null
  mode: NULLABLE
  name: dag_id
  type: STRING
- description: null
  mode: NULLABLE
  name: owner
  type: STRING
- description: null
  mode: NULLABLE
  name: link
  type: STRING
