fields:
- name: submission_date_s3
  type: DATE
  mode: NULLABLE
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: channel
  type: STRING
  mode: NULLABLE
- name: metadata
  type: RECORD
  mode: NULLABLE
  fields:
  - name: document_id
    type: STRING
    mode: NULLABLE
  - name: timestamp
    type: INTEGER
    mode: NULLABLE
  - name: date
    type: STRING
    mode: NULLABLE
  - name: geo_country
    type: STRING
    mode: NULLABLE
  - name: geo_city
    type: STRING
    mode: NULLABLE
  - name: app_build_id
    type: STRING
    mode: NULLABLE
  - name: app_name
    type: STRING
    mode: NULLABLE
- name: v
  type: INTEGER
  mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
- name: seq
  type: INTEGER
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
- name: os
  type: STRING
  mode: NULLABLE
- name: osversion
  type: STRING
  mode: NULLABLE
- name: created
  type: INTEGER
  mode: NULLABLE
- name: tz
  type: INTEGER
  mode: NULLABLE
- name: settings
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: STRING
    mode: NULLABLE
- name: events
  type: RECORD
  mode: REPEATED
  fields:
  - name: f0_
    type: INTEGER
    mode: NULLABLE
  - name: f1_
    type: STRING
    mode: NULLABLE
  - name: f2_
    type: STRING
    mode: NULLABLE
  - name: f3_
    type: STRING
    mode: NULLABLE
  - name: f4_
    type: STRING
    mode: NULLABLE
  - name: f5_
    type: RECORD
    mode: REPEATED
    fields:
    - name: key
      type: STRING
      mode: NULLABLE
    - name: value
      type: STRING
      mode: NULLABLE
- name: arch
  type: STRING
  mode: NULLABLE
- name: device
  type: STRING
  mode: NULLABLE
- name: process_start_timestamp
  type: INTEGER
  mode: NULLABLE
- name: experiments
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: STRING
    mode: NULLABLE
