fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: client_id
  type: STRING
  mode: NULLABLE
  description: Client ID
- name: sample_id
  type: INTEGER
  mode: NULLABLE
  description: Sample ID
- name: distribution_id
  type: STRING
  mode: NULLABLE
  description: Distribution ID
- name: locale
  type: STRING
  mode: NULLABLE
  description: Locale
- name: app_version
  type: STRING
  mode: NULLABLE
  description: App Version
- name: isp
  type: STRING
  mode: NULLABLE
  description: ISP Name
- name: first_seen_date
  type: DATE
  mode: NULLABLE
  description: First Seen Date - Date when the server first received any of the 3
    ping types from this client
- name: attribution_campaign
  type: STRING
  mode: NULLABLE
  description: Attribution Campaign (from clients first seen)
- name: attribution_content
  type: STRING
  mode: NULLABLE
  description: Attribution Content (from clients first seen)
- name: attribution_dlsource
  type: STRING
  mode: NULLABLE
  description: Attribution Download Source (from clients first seen)
- name: attribution_medium
  type: STRING
  mode: NULLABLE
  description: Attribution Medium (from clients first seen)
- name: attribution_ua
  type: STRING
  mode: NULLABLE
  description: Attribution UA (from clients first seen)
- name: attribution_experiment
  type: STRING
  mode: NULLABLE
  description: Attribution Experiment (from clients first seen)
- name: attribution_variation
  type: STRING
  mode: NULLABLE
  description: Attribution Variation (from clients last seen since unavailable in
    clients first seen)
- name: normalized_channel
  type: STRING
  mode: NULLABLE
  description: Normalized Channel
- name: normalized_os
  type: STRING
  mode: NULLABLE
  description: Normalized Operating System
- name: normalized_os_version
  type: STRING
  mode: NULLABLE
  description: Normalized Operating System Version
- name: startup_profile_selection_reason
  type: STRING
  mode: NULLABLE
  description: Startup Profile Selection Reason - How the profile was selected during
    startup
- name: country
  type: STRING
  mode: NULLABLE
  description: Country
- name: is_dau
  type: BOOLEAN
  mode: NULLABLE
- name: is_wau
  type: BOOLEAN
  mode: NULLABLE
- name: is_mau
  type: BOOLEAN
  mode: NULLABLE
- name: lifecycle_stage
  type: STRING
  mode: NULLABLE
