fields:
- name: additional_properties
  type: STRING
  mode: NULLABLE
- name: addon_version
  type: STRING
  mode: NULLABLE
- name: block
  type: INTEGER
  mode: NULLABLE
- name: click
  type: INTEGER
  mode: NULLABLE
- name: document_id
  type: STRING
  mode: NULLABLE
- name: impression_id
  type: STRING
  mode: NULLABLE
- name: loaded
  type: INTEGER
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
- name: metadata
  type: RECORD
  mode: NULLABLE
  fields:
  - name: geo
    type: RECORD
    mode: NULLABLE
    fields:
    - name: city
      type: STRING
      mode: NULLABLE
    - name: country
      type: STRING
      mode: NULLABLE
    - name: db_version
      type: STRING
      mode: NULLABLE
    - name: subdivision1
      type: STRING
      mode: NULLABLE
    - name: subdivision2
      type: STRING
      mode: NULLABLE
  - name: header
    type: RECORD
    mode: NULLABLE
    fields:
    - name: date
      type: STRING
      mode: NULLABLE
    - name: dnt
      type: STRING
      mode: NULLABLE
    - name: x_debug_id
      type: STRING
      mode: NULLABLE
    - name: x_pingsender_version
      type: STRING
      mode: NULLABLE
    - name: x_source_tags
      type: STRING
      mode: NULLABLE
    - name: x_telemetry_agent
      type: STRING
      mode: NULLABLE
    - name: x_foxsec_ip_reputation
      type: STRING
      mode: NULLABLE
    - name: x_lb_tags
      type: STRING
      mode: NULLABLE
    - name: parsed_date
      type: TIMESTAMP
      mode: NULLABLE
    - name: parsed_x_source_tags
      type: STRING
      mode: REPEATED
    - name: parsed_x_lb_tags
      type: RECORD
      mode: NULLABLE
      fields:
      - name: tls_version
        type: STRING
        mode: NULLABLE
      - name: tls_cipher_hex
        type: STRING
        mode: NULLABLE
  - name: user_agent
    type: RECORD
    mode: NULLABLE
    fields:
    - name: browser
      type: STRING
      mode: NULLABLE
    - name: os
      type: STRING
      mode: NULLABLE
    - name: version
      type: STRING
      mode: NULLABLE
  - name: isp
    type: RECORD
    mode: NULLABLE
    fields:
    - name: db_version
      type: STRING
      mode: NULLABLE
    - name: name
      type: STRING
      mode: NULLABLE
    - name: organization
      type: STRING
      mode: NULLABLE
- name: normalized_app_name
  type: STRING
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
- name: normalized_country_code
  type: STRING
  mode: NULLABLE
- name: normalized_os
  type: STRING
  mode: NULLABLE
- name: normalized_os_version
  type: STRING
  mode: NULLABLE
- name: page
  type: STRING
  mode: NULLABLE
- name: pocket
  type: INTEGER
  mode: NULLABLE
- name: profile_creation_date
  type: INTEGER
  mode: NULLABLE
- name: region
  type: STRING
  mode: NULLABLE
- name: release_channel
  type: STRING
  mode: NULLABLE
- name: sample_id
  type: INTEGER
  mode: NULLABLE
- name: shield_id
  type: STRING
  mode: NULLABLE
- name: source
  type: STRING
  mode: NULLABLE
- name: submission_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: tiles
  type: RECORD
  mode: REPEATED
  fields:
  - name: id
    type: INTEGER
    mode: NULLABLE
  - name: pos
    type: INTEGER
    mode: NULLABLE
- name: user_prefs
  type: INTEGER
  mode: NULLABLE
- name: version
  type: STRING
  mode: NULLABLE
- name: experiments
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: RECORD
    mode: NULLABLE
    fields:
    - name: branch
      type: STRING
      mode: NULLABLE
- name: window_inner_height
  type: INTEGER
  mode: NULLABLE
- name: window_inner_width
  type: INTEGER
  mode: NULLABLE
