fields:
- description: Airflow DAG id
  mode: NULLABLE
  name: dag_id
  type: STRING
- description: Airflow task id
  mode: NULLABLE
  name: task_id
  type: STRING
- mode: NULLABLE
  name: duration
  type: INTEGER
- mode: NULLABLE
  name: execution_date
  type: TIMESTAMP
- mode: NULLABLE
  name: start_date
  type: TIMESTAMP
- mode: NULLABLE
  name: end_date
  type: TIMESTAMP
