fields:
- name: dag_id
  type: STRING
  mode: NULLABLE
  description: Airflow DAG id
- name: task_id
  type: STRING
  mode: NULLABLE
  description: Airflow task id
- name: duration
  type: INTEGER
  mode: NULLABLE
  description: Time elapsed since start until end of task's exeuction (seconds)
- name: start_date
  type: TIMESTAMP
  mode: NULLABLE
  description: null
- name: end_date
  type: TIMESTAMP
  mode: NULLABLE
  description: null
