fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Date corresponding to the unique client count
- name: meta_attribution_app
  type: STRING
  mode: NULLABLE
  description: A string representing the app the client activity occurred on
- name: normalized_channel
  type: STRING
  mode: NULLABLE
  description: Attributable channel
- name: country
  type: STRING
  mode: NULLABLE
  description: Country corresponding to the unique client
- name: ping_count
  type: INTEGER
  mode: NULLABLE
