fields:
- name: client_id
  type: STRING
  mode: NULLABLE
  description: The smaller client ID string
- name: linked_client_id
  type: STRING
  mode: NULLABLE
  description: The larger client ID string
- name: linkage_first_seen_date
  type: DATE
  mode: NULLABLE
  description: Date of when a client ID and linked client ID are first detected to
    be using the same account ID
- name: linkage_last_seen_date
  type: DATE
  mode: NULLABLE
  description: Date of when a client ID and linked client ID are last detected to
    be using the same account ID
