fields:
- mode: NULLABLE
  name: external_id
  type: STRING
- mode: NULLABLE
  name: email
  type: STRING
- mode: NULLABLE
  name: mailing_country
  type: STRING
- mode: NULLABLE
  name: email_subscribe
  type: STRING
- mode: NULLABLE
  name: basket_token
  type: STRING
- mode: NULLABLE
  name: email_lang
  type: STRING
- mode: NULLABLE
  name: fxa_id_sha256
  type: STRING
- mode: NULLABLE
  name: fxa_primary_email
  type: STRING
- mode: NULLABLE
  name: fxa_lang
  type: STRING
- mode: NULLABLE
  name: first_service
  type: STRING
- mode: NULLABLE
  name: user_source
  type: STRING
- mode: REPEATED
  name: products
  type: RECORD
- mode: REPEATED
  name: newsletters
  type: STRING
- mode: REPEATED
  name: waitlists
  type: RECORD
