type: BIGCONFIG_FILE
tag_deployments:
- collection:
    name: Browser Metrics (non-KPI)
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.focus_ios_derived.attribution_clients_v1.*
    metrics:
    - metric_type:
        type: PREDEFINED
        predefined_metric: FRESHNESS
      metric_name: FRESHNESS [warn]
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
    - metric_type:
        type: PREDEFINED
        predefined_metric: VOLUME
      metric_name: VOLUME [fail]
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
table_deployments:
- collection:
    name: Browser Metrics (non-KPI)
  deployments:
  - fq_table_name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.focus_ios_derived.attribution_clients_v1
    table_metrics:
    - metric_type:
        type: PREDEFINED
        predefined_metric: FRESHNESS
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
    - metric_type:
        type: PREDEFINED
        predefined_metric: VOLUME
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
