fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: addon_id
  type: STRING
  mode: NULLABLE
- name: addon_version
  type: STRING
  mode: NULLABLE
- name: event_string_value
  type: STRING
  mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
- name: sample_id
  type: INTEGER
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
- name: app_name
  type: STRING
  mode: NULLABLE
- name: app_version
  type: STRING
  mode: NULLABLE
- name: os_name
  type: STRING
  mode: NULLABLE
- name: os_version
  type: STRING
  mode: NULLABLE
- name: event_timestamp
  type: INTEGER
  mode: NULLABLE
- name: event_category
  type: STRING
  mode: NULLABLE
- name: method
  type: STRING
  mode: NULLABLE
- name: object
  type: STRING
  mode: NULLABLE
- name: value
  type: STRING
  mode: NULLABLE
- name: event_map_values
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: STRING
    mode: NULLABLE
- name: event_process
  type: STRING
  mode: NULLABLE
