fields:
- mode: NULLABLE
  name: user_role
  type: STRING
- description: Airflow user id
  mode: NULLABLE
  name: user_id
  type: INTEGER
- mode: NULLABLE
  name: created_on
  type: DATETIME
- mode: NULLABLE
  name: changed_on
  type: DATETIME
- mode: NULLABLE
  name: last_login
  type: DATETIME
