fields:
- name: user_role
  type: STRING
  mode: NULLABLE
- name: user_id
  type: INTEGER
  mode: NULLABLE
  description: Airflow user id
- name: created_on
  type: DATETIME
  mode: NULLABLE
  description: Datetime when a user was created
- name: changed_on
  type: DATETIME
  mode: NULLABLE
  description: Datetime when a user was last modified
- name: last_login
  type: DATETIME
  mode: NULLABLE
  description: Datetime when a user last logged in
