fields:
- description: Date when the app first reported a baseline ping for the client.
  mode: NULLABLE
  name: first_seen_date
  type: DATE
- description: Unique ID for the client installation.
  mode: NULLABLE
  name: client_id
  type: STRING
- description: Sample ID to limit query results during an analysis.
  mode: NULLABLE
  name: sample_id
  type: INTEGER
- description: Date when the server first received a baseline ping for the client.
  mode: NULLABLE
  name: submission_date
  type: DATE
- description: Date when the browser first ran.
  mode: NULLABLE
  name: first_run_date
  type: DATE
- description: First reported country for the client installation
  mode: NULLABLE
  name: first_reported_country
  type: STRING
- description: Name of the first reported isp (Internet Service Provider).
  mode: NULLABLE
  name: first_reported_isp
  type: STRING
- description: Channel where the browser is released.
  mode: NULLABLE
  name: channel
  type: STRING
- description: Manufacturer of the device where the client is installed.
  mode: NULLABLE
  name: device_manufacturer
  type: STRING
- description: Model of the device where the client is installed.
  mode: NULLABLE
  name: device_model
  type: STRING
- description: Version of the Operating System where the client is originally installed.
  mode: NULLABLE
  name: os_version
  type: STRING
- description: App display version for this client installation.
  mode: NULLABLE
  name: app_version
  type: STRING
- mode: NULLABLE
  name: activated
  type: BOOLEAN
- mode: NULLABLE
  name: adjust_campaign
  type: STRING
- mode: NULLABLE
  name: adjust_ad_group
  type: STRING
- mode: NULLABLE
  name: adjust_creative
  type: STRING
- fields:
  - mode: NULLABLE
    name: reported_first_session_ping
    type: BOOLEAN
  - mode: NULLABLE
    name: reported_metrics_ping
    type: BOOLEAN
  - mode: NULLABLE
    name: min_first_session_ping_submission_date
    type: DATE
  - mode: NULLABLE
    name: min_first_session_ping_run_date
    type: DATE
  - mode: NULLABLE
    name: min_metrics_ping_submission_date
    type: DATE
  - mode: NULLABLE
    name: adjust_network__source_ping
    type: STRING
  - mode: NULLABLE
    name: install_source__source_ping
    type: STRING
  - mode: NULLABLE
    name: adjust_network__source_ping_datetime
    type: DATETIME
  - mode: NULLABLE
    name: install_source__source_ping_datetime
    type: DATETIME
  mode: NULLABLE
  name: metadata
  type: RECORD
- mode: NULLABLE
  name: adjust_network
  type: STRING
- mode: NULLABLE
  name: install_source
  type: STRING
