fields:
- name: first_seen_date
  type: DATE
  mode: NULLABLE
  description: Date when the app first reported a baseline ping for the client.
- name: client_id
  type: STRING
  mode: NULLABLE
  description: Unique ID for the client installation.
- name: sample_id
  type: INTEGER
  mode: NULLABLE
  description: Sample ID to limit query results during an analysis.
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Date when the server first received a baseline ping for the client.
- name: first_run_date
  type: DATE
  mode: NULLABLE
  description: Date when the browser first ran.
- name: first_reported_country
  type: STRING
  mode: NULLABLE
  description: First reported country for the client installation
- name: first_reported_isp
  type: STRING
  mode: NULLABLE
  description: Name of the first reported isp (Internet Service Provider).
- name: channel
  type: STRING
  mode: NULLABLE
  description: Channel where the browser is released.
- name: device_manufacturer
  type: STRING
  mode: NULLABLE
  description: Manufacturer of the device where the client is installed.
- name: device_model
  type: STRING
  mode: NULLABLE
  description: Model of the device where the client is installed.
- name: os_version
  type: STRING
  mode: NULLABLE
  description: Version of the Operating System where the client is originally installed.
- name: app_version
  type: STRING
  mode: NULLABLE
  description: App display version for this client installation.
- name: locale
  type: STRING
  mode: NULLABLE
  description: Client locale.
- name: activated
  type: BOOLEAN
  mode: NULLABLE
  description: Determines if a client is activated based on the activation metric
    and a 7 day lag.
- name: adjust_campaign
  type: STRING
  mode: NULLABLE
  description: Structure parameter for the campaign name.
- name: adjust_ad_group
  type: STRING
  mode: NULLABLE
  description: Structure parameter for the the ad group of a campaign.
- name: adjust_creative
  type: STRING
  mode: NULLABLE
  description: Structure parameter for the creative content of a campaign.
- name: distribution_id
  type: STRING
  mode: NULLABLE
  description: The id of the browser distribution made available in installation sources.
- name: play_store_attribution_campaign
  type: STRING
  mode: NULLABLE
  description: The utm_campaign this install is attributed to. Reported by the install
    referrer service, not Adjust.
- name: play_store_attribution_content
  type: STRING
  mode: NULLABLE
  description: The utm_content this install is attributed to. Reported by the install
    referrer service, not Adjust.
- name: play_store_attribution_medium
  type: STRING
  mode: NULLABLE
  description: The utm_medium this install is attributed to. Reported by the install
    referrer service, not Adjust.
- name: play_store_attribution_source
  type: STRING
  mode: NULLABLE
  description: The utm_source this install is attributed to. Reported by the install
    referrer service, not Adjust.
- name: play_store_attribution_term
  type: STRING
  mode: NULLABLE
  description: The utm_term this install is attributed to. Reported by the install
    referrer service, not Adjust.
- name: play_store_attribution_install_referrer_response
  type: STRING
  mode: NULLABLE
  description: The full install referrer response.
- name: last_reported_adjust_campaign
  type: STRING
  mode: NULLABLE
- name: last_reported_adjust_ad_group
  type: STRING
  mode: NULLABLE
- name: last_reported_adjust_creative
  type: STRING
  mode: NULLABLE
- name: last_reported_adjust_network
  type: STRING
  mode: NULLABLE
- name: last_reported_date
  type: DATE
  mode: NULLABLE
- name: last_reported_channel
  type: STRING
  mode: NULLABLE
- name: last_reported_country
  type: STRING
  mode: NULLABLE
- name: last_reported_device_model
  type: STRING
  mode: NULLABLE
- name: last_reported_device_manufacturer
  type: STRING
  mode: NULLABLE
- name: last_reported_locale
  type: STRING
  mode: NULLABLE
- name: metadata
  type: RECORD
  mode: NULLABLE
  fields:
  - name: reported_first_session_ping
    type: BOOLEAN
    mode: NULLABLE
  - name: reported_metrics_ping
    type: BOOLEAN
    mode: NULLABLE
  - name: reported_baseline_ping
    type: BOOLEAN
    mode: NULLABLE
  - name: min_first_session_ping_submission_date
    type: DATE
    mode: NULLABLE
  - name: min_first_session_ping_run_date
    type: DATE
    mode: NULLABLE
  - name: min_metrics_ping_submission_date
    type: DATE
    mode: NULLABLE
  - name: adjust_network__source_ping
    type: STRING
    mode: NULLABLE
  - name: install_source__source_ping
    type: STRING
    mode: NULLABLE
  - name: adjust_network__source_ping_datetime
    type: DATETIME
    mode: NULLABLE
  - name: install_source__source_ping_datetime
    type: DATETIME
    mode: NULLABLE
  - name: play_store_attribution_campaign__ping_datetime
    type: DATETIME
    mode: NULLABLE
  - name: play_store_attribution_content__ping_datetime
    type: DATETIME
    mode: NULLABLE
  - name: play_store_attribution_medium__ping_datetime
    type: DATETIME
    mode: NULLABLE
  - name: play_store_attribution_source__ping_datetime
    type: DATETIME
    mode: NULLABLE
  - name: play_store_attribution_term__ping_datetime
    type: DATETIME
    mode: NULLABLE
  - name: play_store_attribution_install_referrer_response__ping_datetime
    type: DATETIME
    mode: NULLABLE
- name: adjust_network
  type: STRING
  mode: NULLABLE
  description: Structure parameter for the network of a campaign.
- name: install_source
  type: STRING
  mode: NULLABLE
  description: The source of a client installation.
- name: campaign_id
  type: INTEGER
  mode: NULLABLE
- name: ad_group_id
  type: INTEGER
  mode: NULLABLE
