fields:
- mode: NULLABLE
  name: time
  type: TIMESTAMP
- mode: NULLABLE
  name: experiment
  type: STRING
- mode: NULLABLE
  name: branch
  type: STRING
- mode: NULLABLE
  name: event
  type: STRING
- mode: NULLABLE
  name: value
  type: INTEGER
