fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: normalized_country_code
  type: STRING
  mode: NULLABLE
  description: Normalized Country Code
- name: play_time_ratio
  type: FLOAT
  mode: NULLABLE
  description: Play Time Ratio
