fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: reason_created
  type: STRING
  mode: NULLABLE
- name: reason_resolved
  type: STRING
  mode: NULLABLE
- name: resolved
  type: TIMESTAMP
  mode: NULLABLE
- name: run_id
  type: INTEGER
  mode: NULLABLE
- name: scheduled
  type: TIMESTAMP
  mode: NULLABLE
- name: started
  type: TIMESTAMP
  mode: NULLABLE
- name: state
  type: STRING
  mode: NULLABLE
- name: task_id
  type: STRING
  mode: NULLABLE
- name: worker_group
  type: STRING
  mode: NULLABLE
- name: worker_id
  type: STRING
  mode: NULLABLE
