type: BIGCONFIG_FILE

tag_deployments:
  - collection:
      name: Operational Checks
      notification_channels:
        - slack: '#de-bigeye-triage'
    deployments:
      - column_selectors:
        - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.focus_android_derived.usage_reporting_active_users_aggregates_v1.submission_date
        metrics:
          - saved_metric_id: is_not_null
      - column_selectors:
        - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.focus_android_derived.usage_reporting_active_users_aggregates_v1.country
        metrics:
          - saved_metric_id: is_2_char_len
      - column_selectors:
        - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.focus_android_derived.usage_reporting_active_users_aggregates_v1.channel
        metrics:
          - saved_metric_id: is_valid_channel
      - column_selectors:
        - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.focus_android_derived.usage_reporting_active_users_aggregates_v1.*
        metrics:
          - saved_metric_id: volume
          - saved_metric_id: freshness
