type: BIGCONFIG_FILE
table_deployments:
- deployments:
  - fq_table_name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.telemetry.releases
    table_metrics:
    - metric_type:
        type: PREDEFINED
        predefined_metric: FRESHNESS
      metric_schedule:
        named_schedule:
          name: Default Schedule - 17:00 UTC
    - metric_type:
        type: PREDEFINED
        predefined_metric: VOLUME
      metric_schedule:
        named_schedule:
          name: Default Schedule - 17:00 UTC
