type: BIGCONFIG_FILE
row_creation_times:
  column_selectors:
  - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.telemetry.releases.date
tag_deployments:
- deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.telemetry.releases.*
    metrics:
    - metric_type:
        type: PREDEFINED
        predefined_metric: FRESHNESS_DATA
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
    - metric_type:
        type: PREDEFINED
        predefined_metric: VOLUME_DATA
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
