fields:
- description: null
  mode: NULLABLE
  name: build_number
  type: INTEGER
- description: null
  mode: NULLABLE
  name: category
  type: STRING
- description: null
  mode: NULLABLE
  name: date
  type: DATE
- description: null
  mode: NULLABLE
  name: description
  type: STRING
- description: null
  mode: NULLABLE
  name: is_security_driven
  type: BOOLEAN
- description: null
  mode: NULLABLE
  name: product
  type: STRING
- description: null
  mode: NULLABLE
  name: version
  type: STRING
- mode: NULLABLE
  name: major_version
  type: NUMERIC
- mode: NULLABLE
  name: minor_version
  type: NUMERIC
- mode: NULLABLE
  name: patch_version
  type: NUMERIC
- mode: NULLABLE
  name: beta_version
  type: NUMERIC
