fields:
- mode: NULLABLE
  name: build_number
  type: INTEGER
- mode: NULLABLE
  name: category
  type: STRING
- mode: NULLABLE
  name: date
  type: DATE
- mode: NULLABLE
  name: description
  type: STRING
- mode: NULLABLE
  name: is_security_driven
  type: BOOLEAN
- mode: NULLABLE
  name: product
  type: STRING
- mode: NULLABLE
  name: version
  type: STRING
