fields:
- name: metric_date
  type: DATE
  mode: NULLABLE
  description: This is 28 days before processing.
- name: first_seen_date
  type: DATE
  mode: NULLABLE
  description: When the profile has been seen for the first time.
- name: app_name
  type: STRING
  mode: NULLABLE
  description: App name the profile is using.
- name: normalized_channel
  type: STRING
  mode: NULLABLE
  description: Release channel of the app the profile is using.
- name: country
  type: STRING
  mode: NULLABLE
  description: Profile's country on the metric date.
- name: app_version
  type: STRING
  mode: NULLABLE
  description: Profile's app version on the metric date.
- name: locale
  type: STRING
  mode: NULLABLE
  description: Profile's locale on the metric date.
- name: adjust_ad_group
  type: STRING
  mode: NULLABLE
  description: Adjust Ad Group the profile is attributed to.
- name: adjust_campaign
  type: STRING
  mode: NULLABLE
  description: Adjust Campaign the profile is attributed to.
- name: adjust_creative
  type: STRING
  mode: NULLABLE
  description: Adjust Creative the profile is attributed to.
- name: adjust_network
  type: STRING
  mode: NULLABLE
  description: Adjust Network the profile is attributed to.
- name: is_suspicious_device_client
  type: BOOLEAN
  mode: NULLABLE
- name: ping_sent_metric_date
  type: INTEGER
  mode: NULLABLE
- name: ping_sent_week_4
  type: INTEGER
  mode: NULLABLE
- name: active_metric_date
  type: INTEGER
  mode: NULLABLE
- name: retained_week_4
  type: INTEGER
  mode: NULLABLE
- name: retained_week_4_new_profiles
  type: INTEGER
  mode: NULLABLE
- name: new_profiles_metric_date
  type: INTEGER
  mode: NULLABLE
- name: repeat_profiles
  type: INTEGER
  mode: NULLABLE
- name: lifecycle_stage
  type: STRING
  mode: NULLABLE
