type: BIGCONFIG_FILE

tag_deployments:
  - collection:
      name: Operational Checks
      notification_channels:
        - slack: '#de-bigeye-triage'
    deployments:
      - column_selectors:
        - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_fennec_derived.usage_reporting_clients_first_seen_v1.first_seen_date
        - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_fennec_derived.usage_reporting_clients_first_seen_v1.usage_profile_id
        metrics:
          - saved_metric_id: is_not_null
            rct_overrides:
              - first_seen_date
      - column_selectors:
        - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_fennec_derived.usage_reporting_clients_first_seen_v1.*
        metrics:
          - saved_metric_id: volume
          - saved_metric_id: freshness
