fields:
- name: pipeline_family
  type: STRING
  mode: NULLABLE
- name: args
  type: STRING
  mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
- name: content_length
  type: STRING
  mode: NULLABLE
- name: date
  type: STRING
  mode: NULLABLE
- name: dnt
  type: STRING
  mode: NULLABLE
- name: document_namespace
  type: STRING
  mode: NULLABLE
- name: document_type
  type: STRING
  mode: NULLABLE
- name: document_version
  type: STRING
  mode: NULLABLE
- name: error_message
  type: STRING
  mode: NULLABLE
- name: error_type
  type: STRING
  mode: NULLABLE
- name: exception_class
  type: STRING
  mode: NULLABLE
- name: geo_city
  type: STRING
  mode: NULLABLE
- name: geo_country
  type: STRING
  mode: NULLABLE
- name: geo_subdivision1
  type: STRING
  mode: NULLABLE
- name: geo_subdivision2
  type: STRING
  mode: NULLABLE
- name: host
  type: STRING
  mode: NULLABLE
- name: input
  type: STRING
  mode: NULLABLE
- name: input_type
  type: STRING
  mode: NULLABLE
- name: job_name
  type: STRING
  mode: NULLABLE
- name: method
  type: STRING
  mode: NULLABLE
- name: protocol
  type: STRING
  mode: NULLABLE
- name: remote_addr
  type: STRING
  mode: NULLABLE
- name: stack_trace
  type: STRING
  mode: NULLABLE
- name: stack_trace_cause_1
  type: STRING
  mode: NULLABLE
- name: stack_trace_cause_2
  type: STRING
  mode: NULLABLE
- name: stack_trace_cause_3
  type: STRING
  mode: NULLABLE
- name: stack_trace_cause_4
  type: STRING
  mode: NULLABLE
- name: stack_trace_cause_5
  type: STRING
  mode: NULLABLE
- name: submission_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: uri
  type: STRING
  mode: NULLABLE
- name: user_agent
  type: STRING
  mode: NULLABLE
- name: user_agent_browser
  type: STRING
  mode: NULLABLE
- name: user_agent_os
  type: STRING
  mode: NULLABLE
- name: user_agent_version
  type: STRING
  mode: NULLABLE
- name: x_debug_id
  type: STRING
  mode: NULLABLE
- name: x_forwarded_for
  type: STRING
  mode: NULLABLE
- name: x_pingsender_version
  type: STRING
  mode: NULLABLE
- name: x_pipeline_proxy
  type: STRING
  mode: NULLABLE
- name: isp_name
  type: STRING
  mode: NULLABLE
- name: isp_organization
  type: STRING
  mode: NULLABLE
- name: x_source_tags
  type: STRING
  mode: NULLABLE
- name: x_telemetry_agent
  type: STRING
  mode: NULLABLE
- name: x_foxsec_ip_reputation
  type: STRING
  mode: NULLABLE
- name: x_lb_tags
  type: STRING
  mode: NULLABLE
