fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
- mode: NULLABLE
  name: batch_id
  type: STRING
- mode: NULLABLE
  name: origin
  type: STRING
- mode: NULLABLE
  name: aggregate
  type: INTEGER
