fields:
- name: submission_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: device_id
  type: STRING
  mode: NULLABLE
- name: session_id
  type: INTEGER
  mode: NULLABLE
- name: timestamp
  type: INTEGER
  mode: NULLABLE
- name: time
  type: INTEGER
  mode: NULLABLE
- name: app_version
  type: STRING
  mode: NULLABLE
- name: os_name
  type: STRING
  mode: NULLABLE
- name: os_version
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: city
  type: STRING
  mode: NULLABLE
- name: insert_id
  type: STRING
  mode: NULLABLE
- name: event_type
  type: STRING
  mode: NULLABLE
- name: event_properties
  type: STRING
  mode: NULLABLE
- name: user_properties
  type: STRING
  mode: NULLABLE
