fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: first_seen_date
  type: DATE
  mode: NULLABLE
  description: First Seen Date
- name: locale
  type: STRING
  mode: NULLABLE
  description: Locale
- name: normalized_channel
  type: STRING
  mode: NULLABLE
  description: Normalized Channel
- name: country
  type: STRING
  mode: NULLABLE
  description: Country
- name: app_name
  type: STRING
  mode: NULLABLE
  description: App Name
- name: app_version
  type: STRING
  mode: NULLABLE
  description: App Version (also known as app display version)
- name: adjust_network
  type: STRING
  mode: NULLABLE
  description: Adjust Network
- name: adjust_campaign
  type: STRING
  mode: NULLABLE
  description: Adjust Campaign
- name: adjust_ad_group
  type: STRING
  mode: NULLABLE
  description: Adjust Ad Group
- name: adjust_creative
  type: STRING
  mode: NULLABLE
  description: Adjust Creative
- name: play_store_attribution_campaign
  type: STRING
  mode: NULLABLE
  description: Play Store Attribution Campaign
- name: play_store_attribution_source
  type: STRING
  mode: NULLABLE
  description: Play Store Attribution Source
- name: play_store_attribution_medium
  type: STRING
  mode: NULLABLE
  description: Play Store Attribution Medium
- name: meta_attribution_app
  type: STRING
  mode: NULLABLE
  description: Meta Attribution App
- name: install_source
  type: STRING
  mode: NULLABLE
  description: Install Source
- name: is_suspicious_device_client
  type: BOOLEAN
  mode: NULLABLE
  description: Flags Firefox iOS clients created recently from an older app version
    associated with unusual counts
- name: dau
  type: INTEGER
  mode: NULLABLE
- name: wau
  type: INTEGER
  mode: NULLABLE
- name: mau
  type: INTEGER
  mode: NULLABLE
- name: lifecycle_stage
  type: STRING
  mode: NULLABLE
