fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: first_seen_date
  type: DATE
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
- name: app_name
  type: STRING
  mode: NULLABLE
- name: app_version
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
- name: is_mobile
  type: BOOLEAN
  mode: NULLABLE
- name: dau
  type: INTEGER
  mode: NULLABLE
- name: wau
  type: INTEGER
  mode: NULLABLE
- name: mau
  type: INTEGER
  mode: NULLABLE
- name: lifecycle_stage
  type: STRING
  mode: NULLABLE
- name: paid_vs_organic
  type: STRING
  mode: NULLABLE
- name: play_store_attribution_campaign
  type: STRING
  mode: NULLABLE
- name: play_store_attribution_medium
  type: STRING
  mode: NULLABLE
- name: play_store_attribution_source
  type: STRING
  mode: NULLABLE
- name: meta_attribution_app
  type: STRING
  mode: NULLABLE
- name: install_source
  type: STRING
  mode: NULLABLE
- name: adjust_ad_group
  type: STRING
  mode: NULLABLE
- name: adjust_campaign
  type: STRING
  mode: NULLABLE
- name: adjust_creative
  type: STRING
  mode: NULLABLE
- name: adjust_network
  type: STRING
  mode: NULLABLE
- name: is_suspicious_device_client
  type: BOOLEAN
  mode: NULLABLE
- name: product_name
  type: STRING
  mode: NULLABLE
