type: BIGCONFIG_FILE
tag_deployments:
- collection:
    name: Operational Checks
    notification_channels:
    - slack: '#de-bigeye-triage'
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod..firefox_reality_pc_derived.metrics_clients_last_seen_v1.submission_date
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod..firefox_reality_pc_derived.metrics_clients_last_seen_v1.client_id
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod..firefox_reality_pc_derived.metrics_clients_last_seen_v1.sample_id
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod..firefox_reality_pc_derived.metrics_clients_last_seen_v1.normalized_channel
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod..firefox_reality_pc_derived.metrics_clients_last_seen_v1.n_metrics_ping
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod..firefox_reality_pc_derived.metrics_clients_last_seen_v1.days_sent_metrics_ping_bits
    metrics:
    - saved_metric_id: is_not_null
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod..firefox_reality_pc_derived.metrics_clients_last_seen_v1.normalized_channel
    metrics:
    - saved_metric_id: is_valid_channel
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod..firefox_reality_pc_derived.metrics_clients_last_seen_v1.*
    metrics:
    - saved_metric_id: freshness
    - saved_metric_id: volume
