fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: submission_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: geo_country
  type: STRING
  mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
- name: client_ip
  type: STRING
  mode: NULLABLE
