fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: The date when the ingestion edge server accepted this message
- name: installer_type
  type: STRING
  mode: NULLABLE
  description: Which type of installer generated this ping (full or stub)
- name: version
  type: STRING
  mode: NULLABLE
  description: Version of the installed product.  May be different from installer_version
    for a stub install.  Absent for a failed stub installation.
- name: from_msi
  type: BOOLEAN
  mode: NULLABLE
  description: True if the install was launched from an MSI wrapper
- name: funnelcake
  type: STRING
  mode: NULLABLE
  description: Funnelcake ID
- name: experiment
  type: STRING
  mode: NULLABLE
- name: variation
  type: STRING
  mode: NULLABLE
- name: nm
  type: STRING
  mode: NULLABLE
- name: organization
  type: STRING
  mode: NULLABLE
- name: ping_version
  type: STRING
  mode: NULLABLE
- name: campaign
  type: STRING
  mode: NULLABLE
- name: content
  type: STRING
  mode: NULLABLE
- name: dlsource
  type: STRING
  mode: NULLABLE
- name: dltoken
  type: STRING
  mode: NULLABLE
- name: medium
  type: STRING
  mode: NULLABLE
- name: source
  type: STRING
  mode: NULLABLE
- name: ua
  type: STRING
  mode: NULLABLE
- name: city
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: subdivision1
  type: STRING
  mode: NULLABLE
- name: normalized_country_code
  type: STRING
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
- name: os_version
  type: STRING
  mode: NULLABLE
- name: build_channel
  type: STRING
  mode: NULLABLE
- name: build_id
  type: STRING
  mode: NULLABLE
- name: update_channel
  type: STRING
  mode: NULLABLE
- name: had_old_install
  type: BOOLEAN
  mode: NULLABLE
- name: old_default
  type: BOOLEAN
  mode: NULLABLE
- name: old_version
  type: STRING
  mode: NULLABLE
- name: manual_download
  type: BOOLEAN
  mode: NULLABLE
- name: silent
  type: BOOLEAN
  mode: NULLABLE
- name: user_cancelled
  type: BOOLEAN
  mode: NULLABLE
- name: succeeded
  type: BOOLEAN
  mode: NULLABLE
- name: profile_cleanup_prompt
  type: STRING
  mode: NULLABLE
- name: profile_cleanup_requested
  type: BOOLEAN
  mode: NULLABLE
- name: new_default
  type: BOOLEAN
  mode: NULLABLE
- name: new_launched
  type: BOOLEAN
  mode: NULLABLE
- name: sample_id
  type: INTEGER
  mode: NULLABLE
- name: install_attempts
  type: INTEGER
  mode: NULLABLE
- name: download_date
  type: DATE
  mode: NULLABLE
