fields:
- name: uuid
  type: STRING
  mode: NULLABLE
- name: reported_at
  type: DATETIME
  mode: NULLABLE
- name: comments
  type: STRING
  mode: NULLABLE
- name: url
  type: STRING
  mode: NULLABLE
- name: breakage_category
  type: STRING
  mode: NULLABLE
- name: app_name
  type: STRING
  mode: NULLABLE
- name: app_version
  type: STRING
  mode: NULLABLE
- name: app_channel
  type: STRING
  mode: NULLABLE
- name: os
  type: STRING
  mode: NULLABLE
- name: details
  type: STRING
  mode: NULLABLE
