fields:
- name: submission_date_s3
  type: DATE
  mode: NULLABLE
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: sample_id
  type: INTEGER
  mode: NULLABLE
- name: document_id
  type: STRING
  mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
- name: channel
  type: STRING
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: city
  type: STRING
  mode: NULLABLE
- name: os
  type: STRING
  mode: NULLABLE
- name: os_version
  type: STRING
  mode: NULLABLE
- name: os_service_pack_major
  type: INTEGER
  mode: NULLABLE
- name: os_service_pack_minor
  type: INTEGER
  mode: NULLABLE
- name: windows_build_number
  type: INTEGER
  mode: NULLABLE
- name: windows_ubr
  type: INTEGER
  mode: NULLABLE
- name: install_year
  type: INTEGER
  mode: NULLABLE
- name: profile_creation_date
  type: INTEGER
  mode: NULLABLE
- name: subsession_start_date
  type: STRING
  mode: NULLABLE
- name: subsession_length
  type: INTEGER
  mode: NULLABLE
- name: distribution_id
  type: STRING
  mode: NULLABLE
- name: sync_configured
  type: BOOLEAN
  mode: NULLABLE
- name: sync_count_desktop
  type: INTEGER
  mode: NULLABLE
- name: sync_count_mobile
  type: INTEGER
  mode: NULLABLE
- name: app_build_id
  type: STRING
  mode: NULLABLE
- name: app_display_version
  type: STRING
  mode: NULLABLE
- name: app_name
  type: STRING
  mode: NULLABLE
- name: app_version
  type: STRING
  mode: NULLABLE
- name: timestamp
  type: INTEGER
  mode: NULLABLE
- name: env_build_id
  type: STRING
  mode: NULLABLE
- name: env_build_version
  type: STRING
  mode: NULLABLE
- name: env_build_arch
  type: STRING
  mode: NULLABLE
- name: e10s_enabled
  type: BOOLEAN
  mode: NULLABLE
- name: e10s_cohort
  type: STRING
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
- name: active_experiment_id
  type: STRING
  mode: NULLABLE
- name: active_experiment_branch
  type: STRING
  mode: NULLABLE
- name: reason
  type: STRING
  mode: NULLABLE
- name: timezone_offset
  type: INTEGER
  mode: NULLABLE
- name: plugin_hangs
  type: INTEGER
  mode: NULLABLE
- name: aborts_plugin
  type: INTEGER
  mode: NULLABLE
- name: aborts_content
  type: INTEGER
  mode: NULLABLE
- name: aborts_gmplugin
  type: INTEGER
  mode: NULLABLE
- name: crashes_detected_plugin
  type: INTEGER
  mode: NULLABLE
- name: crashes_detected_content
  type: INTEGER
  mode: NULLABLE
- name: crashes_detected_gmplugin
  type: INTEGER
  mode: NULLABLE
- name: crash_submit_attempt_main
  type: INTEGER
  mode: NULLABLE
- name: crash_submit_attempt_content
  type: INTEGER
  mode: NULLABLE
- name: crash_submit_attempt_plugin
  type: INTEGER
  mode: NULLABLE
- name: crash_submit_success_main
  type: INTEGER
  mode: NULLABLE
- name: crash_submit_success_content
  type: INTEGER
  mode: NULLABLE
- name: crash_submit_success_plugin
  type: INTEGER
  mode: NULLABLE
- name: active_addons_count
  type: INTEGER
  mode: NULLABLE
- name: flash_version
  type: STRING
  mode: NULLABLE
- name: vendor
  type: STRING
  mode: NULLABLE
- name: is_default_browser
  type: BOOLEAN
  mode: NULLABLE
- name: default_search_engine_data_name
  type: STRING
  mode: NULLABLE
- name: default_search_engine
  type: STRING
  mode: NULLABLE
- name: loop_activity_counter
  type: RECORD
  mode: NULLABLE
  fields:
  - name: open_panel
    type: INTEGER
    mode: NULLABLE
  - name: open_conversation
    type: INTEGER
    mode: NULLABLE
  - name: room_open
    type: INTEGER
    mode: NULLABLE
  - name: room_share
    type: INTEGER
    mode: NULLABLE
  - name: room_delete
    type: INTEGER
    mode: NULLABLE
- name: devtools_toolbox_opened_count
  type: INTEGER
  mode: NULLABLE
- name: client_submission_date
  type: STRING
  mode: NULLABLE
- name: places_bookmarks_count
  type: INTEGER
  mode: NULLABLE
- name: places_pages_count
  type: INTEGER
  mode: NULLABLE
- name: push_api_notification_received
  type: INTEGER
  mode: NULLABLE
- name: web_notification_shown
  type: INTEGER
  mode: NULLABLE
- name: popup_notification_stats
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: RECORD
    mode: NULLABLE
    fields:
    - name: offered
      type: INTEGER
      mode: NULLABLE
    - name: action_1
      type: INTEGER
      mode: NULLABLE
    - name: action_2
      type: INTEGER
      mode: NULLABLE
    - name: action_3
      type: INTEGER
      mode: NULLABLE
    - name: action_last
      type: INTEGER
      mode: NULLABLE
    - name: dismissal_click_elsewhere
      type: INTEGER
      mode: NULLABLE
    - name: dismissal_leave_page
      type: INTEGER
      mode: NULLABLE
    - name: dismissal_close_button
      type: INTEGER
      mode: NULLABLE
    - name: dismissal_not_now
      type: INTEGER
      mode: NULLABLE
    - name: open_submenu
      type: INTEGER
      mode: NULLABLE
    - name: learn_more
      type: INTEGER
      mode: NULLABLE
    - name: reopen_offered
      type: INTEGER
      mode: NULLABLE
    - name: reopen_action_1
      type: INTEGER
      mode: NULLABLE
    - name: reopen_action_2
      type: INTEGER
      mode: NULLABLE
    - name: reopen_action_3
      type: INTEGER
      mode: NULLABLE
    - name: reopen_action_last
      type: INTEGER
      mode: NULLABLE
    - name: reopen_dismissal_click_elsewhere
      type: INTEGER
      mode: NULLABLE
    - name: reopen_dismissal_leave_page
      type: INTEGER
      mode: NULLABLE
    - name: reopen_dismissal_close_button
      type: INTEGER
      mode: NULLABLE
    - name: reopen_dismissal_not_now
      type: INTEGER
      mode: NULLABLE
    - name: reopen_open_submenu
      type: INTEGER
      mode: NULLABLE
    - name: reopen_learn_more
      type: INTEGER
      mode: NULLABLE
- name: search_counts
  type: RECORD
  mode: REPEATED
  fields:
  - name: engine
    type: STRING
    mode: NULLABLE
  - name: source
    type: STRING
    mode: NULLABLE
  - name: count
    type: INTEGER
    mode: NULLABLE
- name: addon_compatibility_check_enabled
  type: BOOLEAN
  mode: NULLABLE
- name: window_open_event_count
  type: INTEGER
  mode: NULLABLE
- name: push_api_notify
  type: INTEGER
  mode: NULLABLE
- name: max_concurrent_tab_count
  type: INTEGER
  mode: NULLABLE
- name: unique_domains_count
  type: INTEGER
  mode: NULLABLE
- name: active_addons
  type: RECORD
  mode: REPEATED
  fields:
  - name: addon_id
    type: STRING
    mode: NULLABLE
  - name: blocklisted
    type: BOOLEAN
    mode: NULLABLE
  - name: name
    type: STRING
    mode: NULLABLE
  - name: user_disabled
    type: BOOLEAN
    mode: NULLABLE
  - name: app_disabled
    type: BOOLEAN
    mode: NULLABLE
  - name: version
    type: STRING
    mode: NULLABLE
  - name: scope
    type: INTEGER
    mode: NULLABLE
  - name: type
    type: STRING
    mode: NULLABLE
  - name: foreign_install
    type: BOOLEAN
    mode: NULLABLE
  - name: has_binary_components
    type: BOOLEAN
    mode: NULLABLE
  - name: install_day
    type: INTEGER
    mode: NULLABLE
  - name: update_day
    type: INTEGER
    mode: NULLABLE
  - name: signed_state
    type: INTEGER
    mode: NULLABLE
  - name: is_system
    type: BOOLEAN
    mode: NULLABLE
- name: telemetry_enabled
  type: BOOLEAN
  mode: NULLABLE
- name: active_theme
  type: RECORD
  mode: NULLABLE
  fields:
  - name: addon_id
    type: STRING
    mode: NULLABLE
  - name: blocklisted
    type: BOOLEAN
    mode: NULLABLE
  - name: name
    type: STRING
    mode: NULLABLE
  - name: user_disabled
    type: BOOLEAN
    mode: NULLABLE
  - name: app_disabled
    type: BOOLEAN
    mode: NULLABLE
  - name: version
    type: STRING
    mode: NULLABLE
  - name: scope
    type: INTEGER
    mode: NULLABLE
  - name: type
    type: STRING
    mode: NULLABLE
  - name: foreign_install
    type: BOOLEAN
    mode: NULLABLE
  - name: has_binary_components
    type: BOOLEAN
    mode: NULLABLE
  - name: install_day
    type: INTEGER
    mode: NULLABLE
  - name: update_day
    type: INTEGER
    mode: NULLABLE
  - name: signed_state
    type: INTEGER
    mode: NULLABLE
  - name: is_system
    type: BOOLEAN
    mode: NULLABLE
- name: user_prefs
  type: RECORD
  mode: NULLABLE
  fields:
  - name: dom_ipc_process_count
    type: INTEGER
    mode: NULLABLE
- name: tab_open_event_count
  type: INTEGER
  mode: NULLABLE
- name: max_concurrent_window_count
  type: INTEGER
  mode: NULLABLE
- name: total_uri_count
  type: INTEGER
  mode: NULLABLE
- name: unfiltered_uri_count
  type: INTEGER
  mode: NULLABLE
- name: blocklist_enabled
  type: BOOLEAN
  mode: NULLABLE
- name: events
  type: RECORD
  mode: REPEATED
  fields:
  - name: timestamp
    type: INTEGER
    mode: NULLABLE
  - name: category
    type: STRING
    mode: NULLABLE
  - name: method
    type: STRING
    mode: NULLABLE
  - name: object
    type: STRING
    mode: NULLABLE
  - name: string_value
    type: STRING
    mode: NULLABLE
  - name: map_values
    type: RECORD
    mode: REPEATED
    fields:
    - name: key
      type: STRING
      mode: NULLABLE
    - name: value
      type: STRING
      mode: NULLABLE
- name: attribution
  type: RECORD
  mode: NULLABLE
  fields:
  - name: source
    type: STRING
    mode: NULLABLE
  - name: medium
    type: STRING
    mode: NULLABLE
  - name: campaign
    type: STRING
    mode: NULLABLE
  - name: content
    type: STRING
    mode: NULLABLE
- name: is_wow64
  type: BOOLEAN
  mode: NULLABLE
- name: ssl_handshake_result
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: INTEGER
    mode: NULLABLE
- name: ssl_handshake_result_success
  type: INTEGER
  mode: NULLABLE
- name: ssl_handshake_result_failure
  type: INTEGER
  mode: NULLABLE
- name: shutdown_kill
  type: INTEGER
  mode: NULLABLE
