fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: antivirus
  type: STRING
  mode: REPEATED
  description: Antivirus Software Array - Array of Antivirus Software Installed on
    Client
- name: unique_clients
  type: INTEGER
  mode: NULLABLE
  description: Number of Unique Clients
