fields:
- mode: NULLABLE
  name: submission_minute
  type: TIMESTAMP
- mode: NULLABLE
  name: n
  type: INTEGER
- mode: NULLABLE
  name: n_contile
  type: INTEGER
- mode: NULLABLE
  name: n_remotesettings
  type: INTEGER
