fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: uninstall_client_count
  type: INTEGER
  mode: NULLABLE
  description: Count of Clients with Uninstalls
