fields:
- name: submission_month
  type: DATE
  mode: NULLABLE
  description: Data aggregation month
- name: country
  type: STRING
  mode: NULLABLE
  description: Two-letter code corresponding to country where sponsored tiles are
    available. Please see `static.country_codes_v1`
- name: user_count
  type: INTEGER
  mode: NULLABLE
  description: Count of desktop users for submission_month. Calculated from Unified
    Metrics.
- name: impression_count_1and2
  type: INTEGER
  mode: NULLABLE
  description: Count of tile impressions in positions 1 and 2 for submission_month.
    Calculated from contextual-services.
- name: sponsored_impressions_all
  type: INTEGER
  mode: NULLABLE
  description: Count of tile impressions across all three positions for submission_month.
    Calculated from contextual-services.
- name: visit_count
  type: INTEGER
  mode: NULLABLE
  description: Count of distinct newtab visits for submission_month. Calculated from
    latest Newtab.
- name: clients
  type: INTEGER
  mode: NULLABLE
  description: Count of distinct newtab clients opening the Newtab page for submission_month.
    Calculated from Newtab.
- name: total_inventory_1and2
  type: INTEGER
  mode: NULLABLE
  description: Count of sponsored tile inventory for positions 1 and 2 for submission_month.
    Calculated from latest Newtab data.
- name: fill_rate
  type: FLOAT
  mode: NULLABLE
  description: 'Float of sponsored tile fill rate for positions 1 and 2 for submission_month.
    Impressions / Inventory.

    Calculated from Newtab and contextual-services data.'
- name: visits_total_inventory_1to3
  type: INTEGER
  mode: NULLABLE
  description: Count of sponsored tile inventory for positions 1 to 3 for submission_month.
    Calculated from latest Newtab data.
- name: visits_total_fill_rate_1to3
  type: FLOAT
  mode: NULLABLE
  description: 'Float of calculated fill rate (positions 1 to 3). Impressions / Inventory.

    Calculated from latest Newtab and contextual-services data.'
