fields:
- description: Activity date represented by this row
  mode: NULLABLE
  name: measured_at
  type: DATE
- description: Number of Pocket monthly active users on this measured_at date
  mode: NULLABLE
  name: user_count
  type: INTEGER
