fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: normalized_country_code
  type: STRING
  mode: NULLABLE
  description: Normalized Country Code
- name: bookmarks_added_per_dau
  type: FLOAT
  mode: NULLABLE
  description: Bookmarks Added per DAU
- name: bookmarks_opened_per_dau
  type: FLOAT
  mode: NULLABLE
  description: Bookmarks Opened per DAU
