fields:
- description: null
  mode: NULLABLE
  name: submission_date
  type: DATE
- description: null
  mode: NULLABLE
  name: client_id
  type: STRING
- description: null
  mode: NULLABLE
  name: sample_id
  type: INTEGER
- description: null
  mode: NULLABLE
  name: application_name
  type: STRING
- description: null
  mode: NULLABLE
  name: build_id
  type: STRING
- description: null
  mode: NULLABLE
  name: channel
  type: STRING
- description: null
  mode: NULLABLE
  name: os
  type: STRING
- description: null
  mode: NULLABLE
  name: os_version
  type: STRING
- description: null
  mode: NULLABLE
  name: country_code
  type: STRING
- mode: NULLABLE
  name: main_crash_count
  type: INTEGER
- mode: NULLABLE
  name: content_crash_count
  type: INTEGER
- mode: NULLABLE
  name: gpu_crash_count
  type: INTEGER
- mode: NULLABLE
  name: rdd_crash_count
  type: INTEGER
- mode: NULLABLE
  name: socket_crash_count
  type: INTEGER
- mode: NULLABLE
  name: utility_crash_count
  type: INTEGER
- mode: NULLABLE
  name: vr_crash_count
  type: INTEGER
