fields:
- name: first_seen_date
  type: DATE
  mode: NULLABLE
  description: Date we first received a baseline ping from the profile.
- name: normalized_channel
  type: STRING
  mode: NULLABLE
  description: Release channel of the app the profile is using.
- name: app_name
  type: STRING
  mode: NULLABLE
  description: App name the profile is using.
- name: app_version
  type: STRING
  mode: NULLABLE
  description: Client's app version on the first seen date.
- name: country
  type: STRING
  mode: NULLABLE
  description: Client's country on the first seen date.
- name: locale
  type: STRING
  mode: NULLABLE
  description: Client's locale on the first seen date.
- name: os
  type: STRING
  mode: NULLABLE
  description: Client's os on the first seen date.
- name: os_version
  type: STRING
  mode: NULLABLE
  description: Client's os version on the first seen date.
- name: device_manufacturer
  type: STRING
  mode: NULLABLE
  description: Client's device manufacturer on the first seen date.
- name: is_mobile
  type: BOOLEAN
  mode: NULLABLE
  description: Indicates if this specific entry is used towards calculating mobile
    DAU.
- name: is_suspicious_device_client
  type: BOOLEAN
  mode: NULLABLE
  description: Flag to identify suspicious device users, see bug-1846554 for more
    info.
- name: adjust_ad_group
  type: STRING
  mode: NULLABLE
  description: Adjust Ad Group the profile is attributed to.
- name: adjust_campaign
  type: STRING
  mode: NULLABLE
  description: Adjust Campaign the profile is attributed to.
- name: adjust_creative
  type: STRING
  mode: NULLABLE
  description: Adjust Creative the profile is attributed to.
- name: adjust_network
  type: STRING
  mode: NULLABLE
  description: Adjust Network the profile is attributed to.
- name: new_profiles
  type: INTEGER
  mode: NULLABLE
  description: Number of new profiles recorded for the first seen date.
- name: paid_vs_organic
  type: STRING
  mode: NULLABLE
