fields:
- description: A JSON string containing any payload properties not present in the
    schema
  mode: NULLABLE
  name: additional_properties
  type: STRING
- description: The 40 char hex ID of the changeset. See https://www.mercurial-scm.org/wiki/ChangeSetID.
  mode: NULLABLE
  name: changeset_id
  type: STRING
- description: Statistics about files changed by this changeset.  Similar to running
    'hg diff --stat'.  May be null if diffstats were not computed.
  fields:
  - description: The number of lines added by this changeset.
    mode: NULLABLE
    name: additions
    type: INTEGER
  - description: The number of files modified by this changeset.
    mode: NULLABLE
    name: changed_files
    type: INTEGER
  - description: The number of lines removed by this changeset.
    mode: NULLABLE
    name: deletions
    type: INTEGER
  mode: NULLABLE
  name: diffstat
  type: RECORD
- description: The document ID specified in the URI when the client sent this message
  mode: NULLABLE
  name: document_id
  type: STRING
- description: A string labelling the automated system used to land this changeset
    in this repository.  May be empty.
  mode: NULLABLE
  name: landing_system
  type: STRING
- fields:
  - description: Results of a geographic lookup based on the client's IP address
    fields:
    - mode: NULLABLE
      name: city
      type: STRING
    - description: An ISO 3166-1 alpha-2 country code
      mode: NULLABLE
      name: country
      type: STRING
    - description: The specific geo database version used for this lookup
      mode: NULLABLE
      name: db_version
      type: STRING
    - description: First major country subdivision, typically a state, province, or
        county
      mode: NULLABLE
      name: subdivision1
      type: STRING
    - description: Second major country subdivision; not applicable for most countries
      mode: NULLABLE
      name: subdivision2
      type: STRING
    mode: NULLABLE
    name: geo
    type: RECORD
  - description: Headers included in the client's HTTP request
    fields:
    - description: Date HTTP header
      mode: NULLABLE
      name: date
      type: STRING
    - description: DNT (Do Not Track) HTTP header
      mode: NULLABLE
      name: dnt
      type: STRING
    - description: X-Debug-Id HTTP header
      mode: NULLABLE
      name: x_debug_id
      type: STRING
    - description: X-PingSender-Version HTTP header
      mode: NULLABLE
      name: x_pingsender_version
      type: STRING
    - description: X-Source-Tags HTTP header
      mode: NULLABLE
      name: x_source_tags
      type: STRING
    - description: X-Telemetry-Agent HTTP header
      mode: NULLABLE
      name: x_telemetry_agent
      type: STRING
    - description: X-Foxsec-IP-Reputation header
      mode: NULLABLE
      name: x_foxsec_ip_reputation
      type: STRING
    - description: X-LB-Tags HTTP header
      mode: NULLABLE
      name: x_lb_tags
      type: STRING
    - mode: NULLABLE
      name: parsed_date
      type: TIMESTAMP
    - mode: REPEATED
      name: parsed_x_source_tags
      type: STRING
    - fields:
      - mode: NULLABLE
        name: tls_version
        type: STRING
      - mode: NULLABLE
        name: tls_cipher_hex
        type: STRING
      mode: NULLABLE
      name: parsed_x_lb_tags
      type: RECORD
    mode: NULLABLE
    name: header
    type: RECORD
  - description: Parsed components of the client's user agent string
    fields:
    - mode: NULLABLE
      name: browser
      type: STRING
    - mode: NULLABLE
      name: os
      type: STRING
    - mode: NULLABLE
      name: version
      type: STRING
    mode: NULLABLE
    name: user_agent
    type: RECORD
  - description: Results of ISP lookup based on the client's IP address
    fields:
    - description: The specific geo ISP database version used for this lookup
      mode: NULLABLE
      name: db_version
      type: STRING
    - description: The name of the ISP associated with the client's IP address
      mode: NULLABLE
      name: name
      type: STRING
    - description: The name of a specific business entity associated with the client's
        IP address when available; otherwise the ISP name
      mode: NULLABLE
      name: organization
      type: STRING
    mode: NULLABLE
    name: isp
    type: RECORD
  mode: NULLABLE
  name: metadata
  type: RECORD
- description: Set to "Other" if this message contained an unrecognized app name
  mode: NULLABLE
  name: normalized_app_name
  type: STRING
- description: Set to "Other" if this message contained an unrecognized channel name
  mode: NULLABLE
  name: normalized_channel
  type: STRING
- description: An ISO 3166-1 alpha-2 country code
  mode: NULLABLE
  name: normalized_country_code
  type: STRING
- description: Set to "Other" if this message contained an unrecognized OS name
  mode: NULLABLE
  name: normalized_os
  type: STRING
- mode: NULLABLE
  name: normalized_os_version
  type: STRING
- description: Timestamp, in Unix time (seconds since the Unix epoch), of when the
    push to the repository occurred.  This value is obtained from the original repository
    pushlog.
  mode: NULLABLE
  name: push_date
  type: INTEGER
- description: The URL of the repository the changeset was pushed to.
  mode: NULLABLE
  name: repository
  type: STRING
- description: 'A string labelling the code review system used to review this changeset.  Possible
    values include (but are not limited to): ''mozreview'', ''phabricator'', ''bmo'',
    ''unknown'', and ''not_applicable''.'
  mode: NULLABLE
  name: review_system_used
  type: STRING
- description: Hashed version of client_id (if present) useful for partitioning; ranges
    from 0 to 99
  mode: NULLABLE
  name: sample_id
  type: INTEGER
- description: Time when the ingestion edge server accepted this message
  mode: NULLABLE
  name: submission_timestamp
  type: TIMESTAMP
