fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: os
  type: STRING
  mode: NULLABLE
  description: OS
- name: nbr_unique_users
  type: INTEGER
  mode: NULLABLE
  description: Number of Unique users (distinct client ids)
