fields:
- name: dag_run_id
  type: INTEGER
  mode: NULLABLE
  description: null
- name: content
  type: STRING
  mode: NULLABLE
- name: created_at
  type: TIMESTAMP
  mode: NULLABLE
- name: updated_at
  type: TIMESTAMP
  mode: NULLABLE
- name: user_id
  type: INTEGER
  mode: NULLABLE
