fields:
- description: null
  mode: NULLABLE
  name: dag_run_id
  type: INTEGER
- description: null
  mode: NULLABLE
  name: content
  type: STRING
- description: null
  mode: NULLABLE
  name: created_at
  type: TIMESTAMP
- description: null
  mode: NULLABLE
  name: updated_at
  type: TIMESTAMP
- description: null
  mode: NULLABLE
  name: user_id
  type: INTEGER
