fields:
- name: first_seen_date
  type: DATE
  mode: NULLABLE
- name: country_code
  type: STRING
  mode: NULLABLE
- name: channel
  type: STRING
  mode: NULLABLE
- name: os
  type: STRING
  mode: NULLABLE
- name: os_version
  type: NUMERIC
  mode: NULLABLE
- name: distribution_id
  type: STRING
  mode: NULLABLE
- name: attribution_ua
  type: STRING
  mode: NULLABLE
- name: attribution_source
  type: STRING
  mode: NULLABLE
- name: attribution_medium
  type: STRING
  mode: NULLABLE
- name: attribution_campaign
  type: STRING
  mode: NULLABLE
- name: attribution_content
  type: STRING
  mode: NULLABLE
- name: attribution_experiment
  type: STRING
  mode: NULLABLE
- name: attribution_dlsource
  type: STRING
  mode: NULLABLE
- name: startup_profile_selection_reason
  type: STRING
  mode: NULLABLE
- name: cohort
  type: INTEGER
  mode: NULLABLE
- name: activated
  type: INTEGER
  mode: NULLABLE
- name: returned_second_day
  type: INTEGER
  mode: NULLABLE
- name: qualified_second_day
  type: INTEGER
  mode: NULLABLE
- name: retained_week4
  type: INTEGER
  mode: NULLABLE
- name: qualified_week4
  type: INTEGER
  mode: NULLABLE
