fields:
- description: Airflow DAG id
  mode: NULLABLE
  name: dag_id
  type: STRING
- description: Airflow task id
  mode: NULLABLE
  name: task_id
  type: STRING
- description: Execution date of the DAG Run instance
  mode: NULLABLE
  name: execution_date
  type: TIMESTAMP
- description: Datetime when task has been rescheduled
  mode: NULLABLE
  name: reschedule_date
  type: TIMESTAMP
- description: When the DAG run started
  mode: NULLABLE
  name: start_date
  type: TIMESTAMP
- description: When the DAG run finished
  mode: NULLABLE
  name: end_date
  type: TIMESTAMP
- mode: NULLABLE
  name: duration
  type: INTEGER
