fields:
- mode: NULLABLE
  name: date
  type: DATE
- mode: NULLABLE
  name: experiment_branch
  type: STRING
- mode: NULLABLE
  name: subgroup
  type: STRING
- mode: NULLABLE
  name: n
  type: INTEGER
- mode: NULLABLE
  name: metric_name
  type: STRING
- mode: NULLABLE
  name: metric_type
  type: STRING
- fields:
  - mode: NULLABLE
    name: key
    type: INTEGER
  - fields:
    - mode: NULLABLE
      name: pdf
      type: FLOAT
    - mode: NULLABLE
      name: count
      type: FLOAT
    - mode: NULLABLE
      name: label
      type: STRING
    mode: NULLABLE
    name: value
    type: RECORD
  mode: REPEATED
  name: histogram
  type: RECORD
- fields:
  - mode: NULLABLE
    name: comparison_branch
    type: STRING
  - mode: NULLABLE
    name: name
    type: STRING
  - mode: NULLABLE
    name: value
    type: FLOAT
  - mode: NULLABLE
    name: confidence_low
    type: FLOAT
  - mode: NULLABLE
    name: confidence_high
    type: FLOAT
  - mode: NULLABLE
    name: confidence_level
    type: FLOAT
  - mode: NULLABLE
    name: p_value
    type: FLOAT
  mode: REPEATED
  name: statistics
  type: RECORD
- mode: NULLABLE
  name: experiment_id
  type: STRING
