fields:
- name: client_id
  type: STRING
  mode: NULLABLE
- name: sample_id
  type: INTEGER
  mode: NULLABLE
- name: first_seen_date
  type: DATE
  mode: NULLABLE
- name: first_reported_country
  type: STRING
  mode: NULLABLE
- name: first_reported_isp
  type: STRING
  mode: NULLABLE
- name: channel
  type: STRING
  mode: NULLABLE
- name: device_manufacturer
  type: STRING
  mode: NULLABLE
- name: device_model
  type: STRING
  mode: NULLABLE
- name: os_version
  type: STRING
  mode: NULLABLE
- name: app_version
  type: STRING
  mode: NULLABLE
- name: submission_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: adjust_ad_group
  type: STRING
  mode: NULLABLE
- name: adjust_campaign
  type: STRING
  mode: NULLABLE
- name: adjust_creative
  type: STRING
  mode: NULLABLE
- name: adjust_network
  type: STRING
  mode: NULLABLE
- name: metadata
  type: RECORD
  mode: NULLABLE
  fields:
  - name: is_reported_first_session_ping
    type: BOOLEAN
    mode: NULLABLE
  - name: is_reported_metrics_ping
    type: BOOLEAN
    mode: NULLABLE
  - name: adjust_info__source_ping
    type: STRING
    mode: NULLABLE
- name: is_suspicious_device_client
  type: BOOLEAN
  mode: NULLABLE
- name: is_activated
  type: BOOLEAN
  mode: NULLABLE
