type: BIGCONFIG_FILE
tag_deployments:
- deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_fennec_aurora_derived.usage_reporting_clients_last_seen_v1.*
    metrics:
    - metric_type:
        type: PREDEFINED
        predefined_metric: FRESHNESS
      metric_name: FRESHNESS
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
    - metric_type:
        type: PREDEFINED
        predefined_metric: VOLUME
      metric_name: VOLUME [fail]
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
table_deployments:
- collection:
    name: Operational Checks
    notification_channels:
    - slack: '#de-bigeye-triage'
  deployments:
  - fq_table_name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_fennec_aurora_derived.usage_reporting_clients_last_seen_v1
    columns:
    - column_name: submission_date
      metrics:
      - saved_metric_id: is_not_null
    - column_name: usage_profile_id
      metrics:
      - saved_metric_id: is_not_null
    - column_name: days_seen_bits
      metrics:
      - saved_metric_id: is_not_null
    - column_name: days_active_bits
      metrics:
      - saved_metric_id: is_not_null
    - column_name: days_created_profile_bits
      metrics:
      - saved_metric_id: is_not_null
    table_metrics:
    - saved_metric_id: volume
    - saved_metric_id: freshness
