fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: new_years_day
  type: INTEGER
  mode: NULLABLE
- name: lunar_new_year
  type: INTEGER
  mode: NULLABLE
- name: in_republic_day
  type: INTEGER
  mode: NULLABLE
- name: us_superbowl
  type: INTEGER
  mode: NULLABLE
- name: valentines_day
  type: INTEGER
  mode: NULLABLE
- name: in_holi
  type: INTEGER
  mode: NULLABLE
- name: eid_al_fitr
  type: INTEGER
  mode: NULLABLE
- name: easter_day
  type: INTEGER
  mode: NULLABLE
- name: fr_may_day
  type: INTEGER
  mode: NULLABLE
- name: fr_victory_day
  type: INTEGER
  mode: NULLABLE
- name: us_memorial_day
  type: INTEGER
  mode: NULLABLE
- name: us_juneteenth
  type: INTEGER
  mode: NULLABLE
- name: us_independence_day
  type: INTEGER
  mode: NULLABLE
- name: us_labor_day
  type: INTEGER
  mode: NULLABLE
- name: mx_independence_day
  type: INTEGER
  mode: NULLABLE
- name: us_thanksgiving
  type: INTEGER
  mode: NULLABLE
- name: us_blackfriday
  type: INTEGER
  mode: NULLABLE
- name: us_cybermonday
  type: INTEGER
  mode: NULLABLE
- name: ca_thanksgiving
  type: INTEGER
  mode: NULLABLE
- name: amazon_prime_days_summer
  type: INTEGER
  mode: NULLABLE
- name: de_unity_day
  type: INTEGER
  mode: NULLABLE
- name: in_diwali
  type: INTEGER
  mode: NULLABLE
- name: mx_revolution_day
  type: INTEGER
  mode: NULLABLE
- name: halloween
  type: INTEGER
  mode: NULLABLE
- name: christmas_eve
  type: INTEGER
  mode: NULLABLE
- name: christmas_day
  type: INTEGER
  mode: NULLABLE
- name: boxing_day
  type: INTEGER
  mode: NULLABLE
- name: hanukkah
  type: INTEGER
  mode: NULLABLE
- name: us_kwanzaa
  type: INTEGER
  mode: NULLABLE
- name: new_years_eve
  type: INTEGER
  mode: NULLABLE
