fields:
- name: id
  type: INTEGER
  mode: NULLABLE
- name: _fivetran_synced
  type: TIMESTAMP
  mode: NULLABLE
- name: description
  type: STRING
  mode: NULLABLE
- name: name
  type: STRING
  mode: NULLABLE
- name: status_category_id
  type: INTEGER
  mode: NULLABLE
