fields:
- description: null
  mode: NULLABLE
  name: timestamp
  type: TIMESTAMP
- description: null
  mode: NULLABLE
  name: dag_id
  type: STRING
- description: null
  mode: NULLABLE
  name: warning_type
  type: STRING
- description: null
  mode: NULLABLE
  name: message
  type: STRING
