fields:
- name: document_namespace
  type: STRING
  mode: NULLABLE
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: document_type
  type: STRING
  mode: NULLABLE
- name: document_version
  type: STRING
  mode: NULLABLE
- name: notes
  type: STRING
  mode: NULLABLE
- name: bug
  type: STRING
  mode: NULLABLE
- name: total_errors
  type: INTEGER
  mode: NULLABLE
