fields:
- name: activity_date
  type: DATE
  mode: NULLABLE
  description: The date that the conversion action took place.
- name: gclid
  type: STRING
  mode: NULLABLE
  description: A Google Click ID, which uniquely represent an ad impression for Google
    ads.
- name: did_firefox_first_run
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the GA session associated with this GCLID resulted in a Firefox
    install which ran the first time on this day.
- name: did_search
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the GA session associated with this GCLID resulted in a Firefox
    install with a search on this day.
- name: did_click_ad
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the GA session associated with this GCLID resulted in a Firefox
    install with an ad click on this day.
- name: did_returned_second_day
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the GA session associated with this GCLID resulted in a Firefox
    install that returned on this day.
