fields:
- mode: NULLABLE
  name: client_id
  type: STRING
- mode: NULLABLE
  name: sample_id
  type: INTEGER
- mode: NULLABLE
  name: submission_date
  type: DATE
- mode: NULLABLE
  name: normalized_channel
  type: STRING
- mode: NULLABLE
  name: days_since_seen
  type: INTEGER
- mode: NULLABLE
  name: days_since_created_profile
  type: INTEGER
- mode: NULLABLE
  name: days_since_seen_session_start
  type: INTEGER
- mode: NULLABLE
  name: days_since_seen_session_end
  type: INTEGER
- mode: NULLABLE
  name: days_seen_bits
  type: INTEGER
- mode: NULLABLE
  name: days_created_profile_bits
  type: INTEGER
- mode: NULLABLE
  name: first_run_date
  type: DATE
- mode: NULLABLE
  name: durations
  type: INTEGER
- mode: NULLABLE
  name: days_seen_session_start_bits
  type: INTEGER
- mode: NULLABLE
  name: days_seen_session_end_bits
  type: INTEGER
- mode: NULLABLE
  name: normalized_os
  type: STRING
- mode: NULLABLE
  name: normalized_os_version
  type: STRING
- mode: NULLABLE
  name: android_sdk_version
  type: STRING
- mode: NULLABLE
  name: locale
  type: STRING
- mode: NULLABLE
  name: city
  type: STRING
- mode: NULLABLE
  name: country
  type: STRING
- mode: NULLABLE
  name: isp
  type: STRING
- mode: NULLABLE
  name: app_build
  type: STRING
- mode: NULLABLE
  name: app_channel
  type: STRING
- mode: NULLABLE
  name: app_display_version
  type: STRING
- mode: NULLABLE
  name: architecture
  type: STRING
- mode: NULLABLE
  name: device_manufacturer
  type: STRING
- mode: NULLABLE
  name: device_model
  type: STRING
- mode: NULLABLE
  name: telemetry_sdk_build
  type: STRING
- mode: NULLABLE
  name: first_seen_date
  type: DATE
- mode: NULLABLE
  name: is_new_profile
  type: BOOLEAN
- mode: NULLABLE
  name: n_metrics_ping
  type: INTEGER
- mode: NULLABLE
  name: days_sent_metrics_ping_bits
  type: INTEGER
- mode: NULLABLE
  name: uri_count
  type: INTEGER
- mode: NULLABLE
  name: is_default_browser
  type: BOOLEAN
