fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: event_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: user_id
  type: STRING
  mode: NULLABLE
- name: service
  type: STRING
  mode: NULLABLE
- name: device_id
  type: STRING
  mode: NULLABLE
- name: os_name
  type: STRING
  mode: NULLABLE
- name: flow_id
  type: STRING
  mode: NULLABLE
- name: event_type
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: language
  type: STRING
  mode: NULLABLE
- name: entrypoint
  type: STRING
  mode: NULLABLE
- name: utm_term
  type: STRING
  mode: NULLABLE
- name: utm_medium
  type: STRING
  mode: NULLABLE
- name: utm_source
  type: STRING
  mode: NULLABLE
- name: utm_campaign
  type: STRING
  mode: NULLABLE
- name: utm_content
  type: STRING
  mode: NULLABLE
- name: ua_version
  type: STRING
  mode: NULLABLE
- name: ua_browser
  type: STRING
  mode: NULLABLE
- name: days_seen_bits
  type: INTEGER
  mode: NULLABLE
- name: name
  type: STRING
  mode: NULLABLE
- name: code
  type: STRING
  mode: NULLABLE
- name: country_name
  type: STRING
  mode: NULLABLE
- name: days_since_seen
  type: INTEGER
  mode: NULLABLE
