fields:
- name: dag_id
  type: STRING
  mode: NULLABLE
  description: Airflow DAG id (<root_dag_id>.<subdag_id>)
- name: root_dag_id
  type: STRING
  mode: NULLABLE
  description: Airflow Root DAG id
- name: subdag_id
  type: STRING
  mode: NULLABLE
  description: Airflow subdag id
- name: is_subdag
  type: BOOLEAN
  mode: NULLABLE
  description: Indicates if this DAG is a subdag
- name: owners
  type: STRING
  mode: NULLABLE
  description: DAG owners (comma separated)
- name: is_paused
  type: BOOLEAN
  mode: NULLABLE
  description: Indicates if the DAG is currently paused
- name: has_task_concurrency_limits
  type: BOOLEAN
  mode: NULLABLE
  description: Indicates if DAG has concurrency limit set
- name: concurrency
  type: INTEGER
  mode: NULLABLE
  description: Cuncerrency settings for the DAG
- name: max_active_runs
  type: INTEGER
  mode: NULLABLE
  description: Max number of active DAG runs allowed
- name: is_active
  type: BOOLEAN
  mode: NULLABLE
  description: Indicates if the DAG is active
