fields:
- description: Airflow DAG id (<root_dag_id>.<subdag_id>)
  mode: NULLABLE
  name: dag_id
  type: STRING
- description: Airflow Root DAG id
  mode: NULLABLE
  name: root_dag_id
  type: STRING
- description: Airflow subdag id
  mode: NULLABLE
  name: subdag_id
  type: STRING
- description: Indicates if this DAG is a subdag
  mode: NULLABLE
  name: is_subdag
  type: BOOLEAN
- description: DAG owners (comma separated)
  mode: NULLABLE
  name: owners
  type: STRING
- mode: NULLABLE
  name: is_paused
  type: BOOLEAN
- mode: NULLABLE
  name: has_task_concurrency_limits
  type: BOOLEAN
- mode: NULLABLE
  name: concurrency
  type: INTEGER
- mode: NULLABLE
  name: max_active_runs
  type: INTEGER
