fields:
- name: client_id
  type: STRING
  mode: NULLABLE
  description: Unique ID for the client installation.
- name: sample_id
  type: INTEGER
  mode: NULLABLE
  description: Sample ID, a number 0-99 inclusive, that samples by client ID
- name: as_of_date
  type: DATE
  mode: NULLABLE
  description: The date associated with the Markov state; as_of_date will not update
    after a year of inactivity as the markov states stop updating
- name: first_seen_date
  type: DATE
  mode: NULLABLE
  description: First submission date that this client was seen on
- name: days_since_first_seen
  type: INTEGER
  mode: NULLABLE
  description: Days Since First Seen
- name: days_since_active
  type: INTEGER
  mode: NULLABLE
  description: Days Since Active
- name: first_reported_country
  type: STRING
  mode: NULLABLE
  description: First Reported Country
- name: attribution
  type: RECORD
  mode: NULLABLE
  fields:
  - name: source
    type: STRING
    mode: NULLABLE
    description: null
  - name: medium
    type: STRING
    mode: NULLABLE
    description: null
  - name: campaign
    type: STRING
    mode: NULLABLE
    description: null
  - name: content
    type: STRING
    mode: NULLABLE
    description: null
  - name: experiment
    type: STRING
    mode: NULLABLE
  - name: variation
    type: STRING
    mode: NULLABLE
  - name: dltoken
    type: STRING
    mode: NULLABLE
  - name: dlsource
    type: STRING
    mode: NULLABLE
  - name: ua
    type: STRING
    mode: NULLABLE
  description: Attribution
- name: days_seen_bytes
  type: BYTES
  mode: NULLABLE
  description: Days Seen Bytes
- name: active
  type: INTEGER
  mode: NULLABLE
  description: Active
- name: ad_clicks
  type: INTEGER
  mode: NULLABLE
  description: Ad Clicks
- name: total_historic_ad_clicks
  type: INTEGER
  mode: NULLABLE
  description: Total Historical Ad Clicks
