fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
- mode: NULLABLE
  name: cohort_date
  type: DATE
- mode: NULLABLE
  name: client_id
  type: STRING
- mode: NULLABLE
  name: country
  type: STRING
- mode: NULLABLE
  name: adjust_network
  type: STRING
- mode: NULLABLE
  name: adjust_adgroup
  type: STRING
- mode: NULLABLE
  name: adjust_campaign
  type: STRING
- mode: NULLABLE
  name: adjust_creative
  type: STRING
- mode: NULLABLE
  name: new_profiles
  type: INTEGER
- mode: NULLABLE
  name: dau
  type: INTEGER
- mode: NULLABLE
  name: search_count
  type: INTEGER
- mode: NULLABLE
  name: ad_clicks
  type: INTEGER
