fields:
- name: metric_date
  type: DATE
  mode: NULLABLE
  description: Metric DAte
- name: first_seen_date
  type: DATE
  mode: NULLABLE
  description: First Seen Date
- name: normalized_channel
  type: STRING
  mode: NULLABLE
  description: Normalized Channel
- name: country
  type: STRING
  mode: NULLABLE
  description: Country
- name: app_version
  type: STRING
  mode: NULLABLE
  description: App Version
- name: locale
  type: STRING
  mode: NULLABLE
  description: Locale
- name: attribution_campaign
  type: STRING
  mode: NULLABLE
  description: Attribution Campaign
- name: attribution_content
  type: STRING
  mode: NULLABLE
  description: Attribution Content
- name: attribution_dlsource
  type: STRING
  mode: NULLABLE
  description: Attribution DL Source
- name: attribution_medium
  type: STRING
  mode: NULLABLE
  description: Attribution Medium
- name: attribution_ua
  type: STRING
  mode: NULLABLE
  description: Attribution UA
- name: normalized_os
  type: STRING
  mode: NULLABLE
  description: Normalized OS
- name: normalized_os_version
  type: STRING
  mode: NULLABLE
  description: Normalized OS Version
- name: ping_sent_metric_date
  type: INTEGER
  mode: NULLABLE
- name: ping_sent_week_4
  type: INTEGER
  mode: NULLABLE
- name: active_metric_date
  type: INTEGER
  mode: NULLABLE
- name: retained_week_4
  type: INTEGER
  mode: NULLABLE
- name: retained_week_4_new_profiles
  type: INTEGER
  mode: NULLABLE
- name: new_profiles_metric_date
  type: INTEGER
  mode: NULLABLE
- name: repeat_profiles
  type: INTEGER
  mode: NULLABLE
- name: attribution_experiment
  type: STRING
  mode: NULLABLE
  description: Attribution Experiment
- name: attribution_variation
  type: STRING
  mode: NULLABLE
  description: Attribution Variation
- name: startup_profile_selection_reason
  type: STRING
  mode: NULLABLE
  description: Startup Profile Selection Reason
- name: lifecycle_stage
  type: STRING
  mode: NULLABLE
