fields:
- mode: NULLABLE
  name: country_code
  type: STRING
- mode: NULLABLE
  name: submission_month
  type: DATETIME
- mode: NULLABLE
  name: direct_sales_included
  type: BOOLEAN
- mode: NULLABLE
  name: device
  type: STRING
- mode: NULLABLE
  name: placement
  type: STRING
- mode: NULLABLE
  name: product
  type: STRING
- mode: NULLABLE
  name: pricing_model
  type: STRING
- mode: NULLABLE
  name: forecast_month
  type: DATETIME
- mode: NULLABLE
  name: forecast_predicted_at
  type: TIMESTAMP
- mode: NULLABLE
  name: position
  type: INTEGER
- mode: NULLABLE
  name: impressions
  type: FLOAT
- mode: NULLABLE
  name: clicks
  type: FLOAT
- mode: NULLABLE
  name: revenue
  type: FLOAT
- mode: NULLABLE
  name: CPM
  type: FLOAT
