fields:
- name: client_id
  type: STRING
  mode: NULLABLE
  description: Unique ID for the client installation.
- name: ad_click_history
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: DATE
    mode: NULLABLE
    description: The date associated with the ad_click value
  - name: value
    type: INTEGER
    mode: NULLABLE
    description: The total number of ad_clicks for the submission_date
  description: History of ad_clicks for a user, by submission_date
