fields:
- description: A JSON string containing any payload properties not present in the
    schema
  mode: NULLABLE
  name: additional_properties
  type: STRING
- fields:
  - mode: NULLABLE
    name: architecture
    type: STRING
  - mode: NULLABLE
    name: build_id
    type: STRING
  - mode: NULLABLE
    name: channel
    type: STRING
  - mode: NULLABLE
    name: display_version
    type: STRING
  - mode: NULLABLE
    name: name
    type: STRING
  - mode: NULLABLE
    name: platform_version
    type: STRING
  - mode: NULLABLE
    name: vendor
    type: STRING
  - mode: NULLABLE
    name: version
    type: STRING
  - mode: NULLABLE
    name: xpcom_abi
    type: STRING
  mode: NULLABLE
  name: application
  type: RECORD
- mode: NULLABLE
  name: creation_date
  type: STRING
- description: The document ID specified in the URI when the client sent this message
  mode: NULLABLE
  name: document_id
  type: STRING
- mode: NULLABLE
  name: id
  type: STRING
- fields:
  - description: Results of a geographic lookup based on the client's IP address
    fields:
    - mode: NULLABLE
      name: city
      type: STRING
    - description: An ISO 3166-1 alpha-2 country code
      mode: NULLABLE
      name: country
      type: STRING
    - description: The specific geo database version used for this lookup
      mode: NULLABLE
      name: db_version
      type: STRING
    - description: First major country subdivision, typically a state, province, or
        county
      mode: NULLABLE
      name: subdivision1
      type: STRING
    - description: Second major country subdivision; not applicable for most countries
      mode: NULLABLE
      name: subdivision2
      type: STRING
    mode: NULLABLE
    name: geo
    type: RECORD
  - description: Headers included in the client's HTTP request
    fields:
    - description: Date HTTP header
      mode: NULLABLE
      name: date
      type: STRING
    - description: DNT (Do Not Track) HTTP header
      mode: NULLABLE
      name: dnt
      type: STRING
    - description: X-Debug-Id HTTP header
      mode: NULLABLE
      name: x_debug_id
      type: STRING
    - description: X-PingSender-Version HTTP header
      mode: NULLABLE
      name: x_pingsender_version
      type: STRING
    - description: X-Source-Tags HTTP header
      mode: NULLABLE
      name: x_source_tags
      type: STRING
    - description: X-Telemetry-Agent HTTP header
      mode: NULLABLE
      name: x_telemetry_agent
      type: STRING
    - description: X-Foxsec-IP-Reputation header
      mode: NULLABLE
      name: x_foxsec_ip_reputation
      type: STRING
    - description: X-LB-Tags HTTP header
      mode: NULLABLE
      name: x_lb_tags
      type: STRING
    - mode: NULLABLE
      name: parsed_date
      type: TIMESTAMP
    - mode: REPEATED
      name: parsed_x_source_tags
      type: STRING
    - fields:
      - mode: NULLABLE
        name: tls_version
        type: STRING
      - mode: NULLABLE
        name: tls_cipher_hex
        type: STRING
      mode: NULLABLE
      name: parsed_x_lb_tags
      type: RECORD
    mode: NULLABLE
    name: header
    type: RECORD
  - description: Results of ISP lookup based on the client's IP address
    fields:
    - description: The specific geo ISP database version used for this lookup
      mode: NULLABLE
      name: db_version
      type: STRING
    - description: The name of the ISP associated with the client's IP address
      mode: NULLABLE
      name: name
      type: STRING
    - description: The name of a specific business entity associated with the client's
        IP address when available; otherwise the ISP name
      mode: NULLABLE
      name: organization
      type: STRING
    mode: NULLABLE
    name: isp
    type: RECORD
  - description: Components of the URI to which this ping was sent
    fields:
    - mode: NULLABLE
      name: app_build_id
      type: STRING
    - mode: NULLABLE
      name: app_name
      type: STRING
    - mode: NULLABLE
      name: app_update_channel
      type: STRING
    - mode: NULLABLE
      name: app_version
      type: STRING
    mode: NULLABLE
    name: uri
    type: RECORD
  - description: Parsed components of the client's user agent string
    fields:
    - mode: NULLABLE
      name: browser
      type: STRING
    - mode: NULLABLE
      name: os
      type: STRING
    - mode: NULLABLE
      name: version
      type: STRING
    mode: NULLABLE
    name: user_agent
    type: RECORD
  mode: NULLABLE
  name: metadata
  type: RECORD
- description: Set to "Other" if this message contained an unrecognized app name
  mode: NULLABLE
  name: normalized_app_name
  type: STRING
- description: Set to "Other" if this message contained an unrecognized channel name
  mode: NULLABLE
  name: normalized_channel
  type: STRING
- description: An ISO 3166-1 alpha-2 country code
  mode: NULLABLE
  name: normalized_country_code
  type: STRING
- description: Set to "Other" if this message contained an unrecognized OS name
  mode: NULLABLE
  name: normalized_os
  type: STRING
- mode: NULLABLE
  name: normalized_os_version
  type: STRING
- fields:
  - mode: NULLABLE
    name: accounts_days_visited_per_month
    type: FLOAT
  - fields:
    - mode: NULLABLE
      name: id
      type: STRING
    - mode: NULLABLE
      name: name
      type: STRING
    mode: REPEATED
    name: active_addons
    type: RECORD
  - mode: NULLABLE
    name: browser_privatebrowsing_autostart
    type: BOOLEAN
  - mode: NULLABLE
    name: browser_startup_page
    type: FLOAT
  - mode: NULLABLE
    name: cookies_oldest_days_old
    type: FLOAT
  - mode: NULLABLE
    name: default_private_search_engine_is_google
    type: BOOLEAN
  - mode: NULLABLE
    name: default_search_engine_is_google
    type: BOOLEAN
  - mode: NULLABLE
    name: google_accounts_cookie_days_old
    type: FLOAT
  - mode: NULLABLE
    name: google_accounts_cookie_present
    type: BOOLEAN
  - mode: NULLABLE
    name: has_allow_cookie_exceptions
    type: BOOLEAN
  - mode: NULLABLE
    name: has_block_cookie_exceptions
    type: BOOLEAN
  - mode: NULLABLE
    name: has_browser_search_ad_clicks
    type: BOOLEAN
  - mode: NULLABLE
    name: has_browser_search_with_ads
    type: BOOLEAN
  - mode: NULLABLE
    name: history_average_days_per_month
    type: FLOAT
  - mode: NULLABLE
    name: history_oldest_days_old
    type: FLOAT
  - mode: NULLABLE
    name: logins_accounts
    type: BOOLEAN
  - mode: NULLABLE
    name: logins_accounts_uses_per_month
    type: FLOAT
  - mode: NULLABLE
    name: network_cookie_cookie_behavior
    type: FLOAT
  - mode: NULLABLE
    name: network_cookie_lifetime_policy
    type: FLOAT
  - mode: NULLABLE
    name: password_manager_enabled
    type: BOOLEAN
  - mode: NULLABLE
    name: privacy_clear_on_shutdown_cookies
    type: BOOLEAN
  - mode: NULLABLE
    name: privacy_sanitize_sanitize_on_shutdown
    type: BOOLEAN
  - mode: NULLABLE
    name: profile_days_old
    type: FLOAT
  - mode: NULLABLE
    name: session_days_old
    type: FLOAT
  mode: NULLABLE
  name: payload
  type: RECORD
- description: Hashed version of client_id (if present) useful for partitioning; ranges
    from 0 to 99
  mode: NULLABLE
  name: sample_id
  type: INTEGER
- description: Time when the ingestion edge server accepted this message
  mode: NULLABLE
  name: submission_timestamp
  type: TIMESTAMP
- mode: NULLABLE
  name: version
  type: FLOAT
