fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: url
  type: STRING
  mode: NULLABLE
  description: Chrome Extension URL
- name: chrome_extension_name
  type: STRING
  mode: NULLABLE
  description: Chrome Extension Name
- name: star_rating_raw
  type: NUMERIC
  mode: NULLABLE
- name: star_rating_numeric
  type: NUMERIC
  mode: NULLABLE
- name: number_of_ratings_raw
  type: STRING
  mode: NULLABLE
- name: number_of_ratings_numeric
  type: FLOAT
  mode: NULLABLE
- name: number_of_users_raw
  type: STRING
  mode: NULLABLE
- name: number_of_users_numeric
  type: INTEGER
  mode: NULLABLE
- name: extension_version
  type: STRING
  mode: NULLABLE
  description: Extension Version
- name: extension_size
  type: STRING
  mode: NULLABLE
  description: Extension Size
- name: extension_languages
  type: STRING
  mode: NULLABLE
  description: Extension Languages
- name: developer_desc
  type: STRING
  mode: NULLABLE
  description: Developer Description
- name: developer_email
  type: STRING
  mode: NULLABLE
  description: Developer Email
- name: developer_website
  type: STRING
  mode: NULLABLE
  description: Developer Website
- name: developer_phone
  type: STRING
  mode: NULLABLE
  description: Developer Phone
- name: extension_updated_date
  type: STRING
  mode: NULLABLE
  description: Extension Updated Date
- name: category
  type: STRING
  mode: NULLABLE
  description: Extension Category
