fields:
- name: service_name
  type: STRING
  mode: NULLABLE
- name: service
  type: STRING
  mode: NULLABLE
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: funnel
  type: STRING
  mode: NULLABLE
- name: login_view
  type: INTEGER
  mode: NULLABLE
- name: login_submit
  type: INTEGER
  mode: NULLABLE
- name: login_success
  type: INTEGER
  mode: NULLABLE
- name: login_email_confirmation_view
  type: INTEGER
  mode: NULLABLE
- name: login_email_confirmation_submit
  type: INTEGER
  mode: NULLABLE
- name: login_email_confirmation_success
  type: INTEGER
  mode: NULLABLE
- name: login_two_factor_view
  type: INTEGER
  mode: NULLABLE
- name: login_two_factor_submit
  type: INTEGER
  mode: NULLABLE
- name: login_two_factor_success
  type: INTEGER
  mode: NULLABLE
- name: login_complete
  type: INTEGER
  mode: NULLABLE
