fields:
- name: service_name
  type: STRING
  mode: NULLABLE
- name: service
  type: STRING
  mode: NULLABLE
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: funnel
  type: STRING
  mode: NULLABLE
- name: login_view
  type: INTEGER
  mode: NULLABLE
- name: login_submit
  type: INTEGER
  mode: NULLABLE
- name: login_email_confirmation_view
  type: INTEGER
  mode: NULLABLE
- name: login_email_confirmation_submit
  type: INTEGER
  mode: NULLABLE
- name: login_two_factor_view
  type: INTEGER
  mode: NULLABLE
- name: login_two_factor_submit
  type: INTEGER
  mode: NULLABLE
- name: login_complete
  type: INTEGER
  mode: NULLABLE
- name: email_first_view
  type: INTEGER
  mode: NULLABLE
- name: reg_view
  type: INTEGER
  mode: NULLABLE
- name: cached_login_view
  type: INTEGER
  mode: NULLABLE
- name: email_first_google_start
  type: INTEGER
  mode: NULLABLE
- name: email_first_apple_start
  type: INTEGER
  mode: NULLABLE
- name: reg_google_start
  type: INTEGER
  mode: NULLABLE
- name: reg_apple_start
  type: INTEGER
  mode: NULLABLE
- name: login_google_start
  type: INTEGER
  mode: NULLABLE
- name: login_apple_start
  type: INTEGER
  mode: NULLABLE
- name: google_deeplink
  type: INTEGER
  mode: NULLABLE
- name: apple_deeplink
  type: INTEGER
  mode: NULLABLE
- name: google_login_complete
  type: INTEGER
  mode: NULLABLE
- name: apple_login_complete
  type: INTEGER
  mode: NULLABLE
