fields:
- description: App ID of the channel data was received from
  mode: NULLABLE
  name: normalized_app_id
  type: STRING
- mode: NULLABLE
  name: submission_date
  type: DATE
- mode: NULLABLE
  name: additional_properties
  type: STRING
- fields:
  - mode: NULLABLE
    name: android_sdk_version
    type: STRING
  - mode: NULLABLE
    name: app_build
    type: STRING
  - mode: NULLABLE
    name: app_channel
    type: STRING
  - mode: NULLABLE
    name: app_display_version
    type: STRING
  - mode: NULLABLE
    name: architecture
    type: STRING
  - mode: NULLABLE
    name: client_id
    type: STRING
  - mode: NULLABLE
    name: device_manufacturer
    type: STRING
  - mode: NULLABLE
    name: device_model
    type: STRING
  - mode: NULLABLE
    name: first_run_date
    type: STRING
  - mode: NULLABLE
    name: locale
    type: STRING
  - mode: NULLABLE
    name: os
    type: STRING
  - mode: NULLABLE
    name: os_version
    type: STRING
  - mode: NULLABLE
    name: telemetry_sdk_build
    type: STRING
  - mode: NULLABLE
    name: build_date
    type: STRING
  - mode: NULLABLE
    name: windows_build_number
    type: INTEGER
  mode: NULLABLE
  name: client_info
  type: RECORD
- mode: NULLABLE
  name: document_id
  type: STRING
- fields:
  - mode: NULLABLE
    name: category
    type: STRING
  - fields:
    - mode: NULLABLE
      name: key
      type: STRING
    - mode: NULLABLE
      name: value
      type: STRING
    mode: REPEATED
    name: extra
    type: RECORD
  - mode: NULLABLE
    name: name
    type: STRING
  - mode: NULLABLE
    name: timestamp
    type: INTEGER
  mode: REPEATED
  name: events
  type: RECORD
- fields:
  - fields:
    - mode: NULLABLE
      name: city
      type: STRING
    - mode: NULLABLE
      name: country
      type: STRING
    - mode: NULLABLE
      name: db_version
      type: STRING
    - mode: NULLABLE
      name: subdivision1
      type: STRING
    - mode: NULLABLE
      name: subdivision2
      type: STRING
    mode: NULLABLE
    name: geo
    type: RECORD
  - fields:
    - mode: NULLABLE
      name: date
      type: STRING
    - mode: NULLABLE
      name: dnt
      type: STRING
    - mode: NULLABLE
      name: x_debug_id
      type: STRING
    - mode: NULLABLE
      name: x_pingsender_version
      type: STRING
    - mode: NULLABLE
      name: x_source_tags
      type: STRING
    - mode: NULLABLE
      name: x_telemetry_agent
      type: STRING
    - mode: NULLABLE
      name: x_foxsec_ip_reputation
      type: STRING
    - mode: NULLABLE
      name: x_lb_tags
      type: STRING
    - mode: NULLABLE
      name: parsed_date
      type: TIMESTAMP
    - mode: REPEATED
      name: parsed_x_source_tags
      type: STRING
    - fields:
      - mode: NULLABLE
        name: tls_version
        type: STRING
      - mode: NULLABLE
        name: tls_cipher_hex
        type: STRING
      mode: NULLABLE
      name: parsed_x_lb_tags
      type: RECORD
    mode: NULLABLE
    name: header
    type: RECORD
  - fields:
    - mode: NULLABLE
      name: browser
      type: STRING
    - mode: NULLABLE
      name: os
      type: STRING
    - mode: NULLABLE
      name: version
      type: STRING
    mode: NULLABLE
    name: user_agent
    type: RECORD
  - fields:
    - mode: NULLABLE
      name: db_version
      type: STRING
    - mode: NULLABLE
      name: name
      type: STRING
    - mode: NULLABLE
      name: organization
      type: STRING
    mode: NULLABLE
    name: isp
    type: RECORD
  mode: NULLABLE
  name: metadata
  type: RECORD
- fields:
  - fields:
    - mode: NULLABLE
      name: migration_addons_any_failures
      type: BOOLEAN
    - mode: NULLABLE
      name: migration_bookmarks_any_failures
      type: BOOLEAN
    - mode: NULLABLE
      name: migration_fxa_any_failures
      type: BOOLEAN
    - mode: NULLABLE
      name: migration_fxa_has_custom_idp_server
      type: BOOLEAN
    - mode: NULLABLE
      name: migration_fxa_has_custom_token_server
      type: BOOLEAN
    - mode: NULLABLE
      name: migration_gecko_any_failures
      type: BOOLEAN
    - mode: NULLABLE
      name: migration_history_any_failures
      type: BOOLEAN
    - mode: NULLABLE
      name: migration_logins_any_failures
      type: BOOLEAN
    - mode: NULLABLE
      name: migration_open_tabs_any_failures
      type: BOOLEAN
    - mode: NULLABLE
      name: migration_settings_any_failures
      type: BOOLEAN
    - mode: NULLABLE
      name: migration_settings_telemetry_enabled
      type: BOOLEAN
    - mode: NULLABLE
      name: migration_telemetry_identifiers_any_failures
      type: BOOLEAN
    - mode: NULLABLE
      name: migration_search_any_failures
      type: BOOLEAN
    - mode: NULLABLE
      name: migration_pinned_sites_any_failures
      type: BOOLEAN
    mode: NULLABLE
    name: boolean
    type: RECORD
  - fields:
    - mode: NULLABLE
      name: migration_addons_failed_addons
      type: INTEGER
    - mode: NULLABLE
      name: migration_addons_failure_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_addons_migrated_addons
      type: INTEGER
    - mode: NULLABLE
      name: migration_addons_success_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_bookmarks_detected
      type: INTEGER
    - mode: NULLABLE
      name: migration_fxa_failure_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_fxa_success_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_history_detected
      type: INTEGER
    - mode: NULLABLE
      name: migration_logins_detected
      type: INTEGER
    - mode: NULLABLE
      name: migration_logins_failure_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_logins_success_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_logins_unsupported_db_version
      type: INTEGER
    - mode: NULLABLE
      name: migration_open_tabs_detected
      type: INTEGER
    - mode: NULLABLE
      name: migration_open_tabs_migrated
      type: INTEGER
    - mode: NULLABLE
      name: migration_settings_failure_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_settings_success_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_bookmarks_failure_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_bookmarks_success_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_gecko_failure_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_gecko_success_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_history_failure_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_history_success_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_open_tabs_failure_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_open_tabs_success_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_telemetry_identifiers_failure_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_telemetry_identifiers_success_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_search_failure_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_search_success_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_pinned_sites_detected_pinned_sites
      type: INTEGER
    - mode: NULLABLE
      name: migration_pinned_sites_failure_reason
      type: INTEGER
    - mode: NULLABLE
      name: migration_pinned_sites_migrated_pinned_sites
      type: INTEGER
    - mode: NULLABLE
      name: migration_pinned_sites_success_reason
      type: INTEGER
    mode: NULLABLE
    name: counter
    type: RECORD
  - fields:
    - mode: NULLABLE
      name: migration_telemetry_identifiers_fennec_profile_creation_date
      type: STRING
    - mode: NULLABLE
      name: raw_migration_telemetry_identifiers_fennec_profile_creation_date
      type: STRING
    mode: NULLABLE
    name: datetime
    type: RECORD
  - fields:
    - fields:
      - mode: NULLABLE
        name: key
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: REPEATED
      name: glean_error_invalid_label
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: key
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: REPEATED
      name: glean_error_invalid_overflow
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: key
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: REPEATED
      name: glean_error_invalid_state
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: key
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: REPEATED
      name: glean_error_invalid_value
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: key
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: REPEATED
      name: migration_bookmarks_migrated
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: key
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: REPEATED
      name: migration_history_migrated
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: key
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: REPEATED
      name: migration_logins_failure_counts
      type: RECORD
    mode: NULLABLE
    name: labeled_counter
    type: RECORD
  - fields:
    - fields:
      - mode: NULLABLE
        name: key
        type: STRING
      - mode: NULLABLE
        name: value
        type: STRING
      mode: REPEATED
      name: migration_migration_versions
      type: RECORD
    mode: NULLABLE
    name: labeled_string
    type: RECORD
  - fields:
    - mode: NULLABLE
      name: migration_fxa_bad_auth_state
      type: STRING
    - mode: NULLABLE
      name: migration_fxa_failure_reason_rust
      type: STRING
    - mode: NULLABLE
      name: migration_fxa_unsupported_account_version
      type: STRING
    - mode: NULLABLE
      name: migration_fxa_unsupported_pickle_version
      type: STRING
    - mode: NULLABLE
      name: migration_fxa_unsupported_state_version
      type: STRING
    mode: NULLABLE
    name: string
    type: RECORD
  - fields:
    - fields:
      - mode: NULLABLE
        name: time_unit
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: NULLABLE
      name: migration_bookmarks_duration
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: time_unit
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: NULLABLE
      name: migration_history_duration
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: time_unit
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: NULLABLE
      name: migration_addons_total_duration
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: time_unit
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: NULLABLE
      name: migration_bookmarks_total_duration
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: time_unit
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: NULLABLE
      name: migration_fxa_total_duration
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: time_unit
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: NULLABLE
      name: migration_gecko_total_duration
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: time_unit
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: NULLABLE
      name: migration_history_total_duration
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: time_unit
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: NULLABLE
      name: migration_logins_total_duration
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: time_unit
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: NULLABLE
      name: migration_open_tabs_total_duration
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: time_unit
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: NULLABLE
      name: migration_pinned_sites_total_duration
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: time_unit
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: NULLABLE
      name: migration_search_total_duration
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: time_unit
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: NULLABLE
      name: migration_settings_total_duration
      type: RECORD
    - fields:
      - mode: NULLABLE
        name: time_unit
        type: STRING
      - mode: NULLABLE
        name: value
        type: INTEGER
      mode: NULLABLE
      name: migration_telemetry_identifiers_total_duration
      type: RECORD
    mode: NULLABLE
    name: timespan
    type: RECORD
  - fields:
    - mode: NULLABLE
      name: migration_telemetry_identifiers_fennec_client_id
      type: STRING
    mode: NULLABLE
    name: uuid
    type: RECORD
  - fields:
    - mode: NULLABLE
      name: key
      type: STRING
    - mode: NULLABLE
      name: value
      type: STRING
    mode: REPEATED
    name: jwe
    type: RECORD
  - fields:
    - mode: NULLABLE
      name: key
      type: STRING
    - fields:
      - mode: NULLABLE
        name: key
        type: STRING
      - fields:
        - mode: NULLABLE
          name: denominator
          type: INTEGER
        - mode: NULLABLE
          name: numerator
          type: INTEGER
        mode: NULLABLE
        name: value
        type: RECORD
      mode: REPEATED
      name: value
      type: RECORD
    mode: REPEATED
    name: labeled_rate
    type: RECORD
  - fields:
    - mode: NULLABLE
      name: key
      type: STRING
    - mode: NULLABLE
      name: value
      type: STRING
    mode: REPEATED
    name: url
    type: RECORD
  - fields:
    - mode: NULLABLE
      name: key
      type: STRING
    - mode: NULLABLE
      name: value
      type: STRING
    mode: REPEATED
    name: text
    type: RECORD
  mode: NULLABLE
  name: metrics
  type: RECORD
- mode: NULLABLE
  name: normalized_app_name
  type: STRING
- mode: NULLABLE
  name: normalized_channel
  type: STRING
- mode: NULLABLE
  name: normalized_country_code
  type: STRING
- mode: NULLABLE
  name: normalized_os
  type: STRING
- mode: NULLABLE
  name: normalized_os_version
  type: STRING
- fields:
  - mode: NULLABLE
    name: end_time
    type: STRING
  - fields:
    - mode: NULLABLE
      name: key
      type: STRING
    - fields:
      - mode: NULLABLE
        name: branch
        type: STRING
      - fields:
        - mode: NULLABLE
          name: type
          type: STRING
        - mode: NULLABLE
          name: enrollment_id
          type: STRING
        mode: NULLABLE
        name: extra
        type: RECORD
      mode: NULLABLE
      name: value
      type: RECORD
    mode: REPEATED
    name: experiments
    type: RECORD
  - mode: NULLABLE
    name: ping_type
    type: STRING
  - mode: NULLABLE
    name: reason
    type: STRING
  - mode: NULLABLE
    name: seq
    type: INTEGER
  - mode: NULLABLE
    name: start_time
    type: STRING
  - mode: NULLABLE
    name: parsed_start_time
    type: TIMESTAMP
  - mode: NULLABLE
    name: parsed_end_time
    type: TIMESTAMP
  mode: NULLABLE
  name: ping_info
  type: RECORD
- mode: NULLABLE
  name: sample_id
  type: INTEGER
- mode: NULLABLE
  name: submission_timestamp
  type: TIMESTAMP
