fields:
- name: survey_data
  type: RECORD
  mode: REPEATED
  fields:
  - name: answer_id
    type: INTEGER
    mode: NULLABLE
  - name: answer
    type: STRING
    mode: NULLABLE
  - name: original_answer
    type: STRING
    mode: NULLABLE
  - name: question
    type: STRING
    mode: NULLABLE
  - name: id
    type: INTEGER
    mode: NULLABLE
  - name: section_id
    type: INTEGER
    mode: NULLABLE
  - name: shown
    type: BOOLEAN
    mode: NULLABLE
  - name: type
    type: STRING
    mode: NULLABLE
  - name: parent
    type: INTEGER
    mode: NULLABLE
  - name: options
    type: RECORD
    mode: REPEATED
    fields:
    - name: id
      type: INTEGER
      mode: NULLABLE
    - name: option
      type: STRING
      mode: NULLABLE
    - name: answer
      type: STRING
      mode: NULLABLE
  - name: subquestions
    type: STRING
    mode: NULLABLE
- name: url_variables
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: STRING
    mode: NULLABLE
- name: response_time
  type: INTEGER
  mode: NULLABLE
- name: session_id
  type: STRING
  mode: NULLABLE
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: '%E4Y-%m-%d'
- name: id
  type: INTEGER
  mode: NULLABLE
- name: status
  type: STRING
  mode: NULLABLE
- name: date_started
  type: TIMESTAMP
  mode: NULLABLE
- name: language
  type: STRING
  mode: NULLABLE
