fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: normalized_os
  type: STRING
  mode: NULLABLE
  description: Normalized Operating System
- name: play_time_ratio
  type: FLOAT
  mode: NULLABLE
  description: Play Time Ratio
