fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: activity_date
  type: STRING
  mode: NULLABLE
- name: dimensions
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: STRING
    mode: NULLABLE
- name: stats
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: FLOAT
    mode: NULLABLE
