fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: account_enabled
  type: BOOLEAN
  mode: NULLABLE
  description: Account Enabled
- name: uninstalls_count
  type: INTEGER
  mode: NULLABLE
  description: Count of unique clients uninstalling
