fields:
- name: client_id
  type: STRING
  mode: NULLABLE
  description: Client ID
- name: sample_id
  type: INTEGER
  mode: NULLABLE
  description: Sample ID
- name: profile_group_id
  type: STRING
  mode: NULLABLE
  description: Profile Group Id
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: metric_date
  type: DATE
  mode: NULLABLE
  description: Metric Date
- name: country
  type: STRING
  mode: NULLABLE
  description: Country
- name: locale
  type: STRING
  mode: NULLABLE
  description: Locale
- name: app_version
  type: STRING
  mode: NULLABLE
  description: App Version
- name: normalized_channel
  type: STRING
  mode: NULLABLE
  description: Normalized Channel
- name: first_seen_date
  type: DATE
  mode: NULLABLE
  description: First Seen Date
- name: attribution_campaign
  type: STRING
  mode: NULLABLE
  description: Attribution Campaign
- name: attribution_content
  type: STRING
  mode: NULLABLE
  description: Attribution Content
- name: attribution_dlsource
  type: STRING
  mode: NULLABLE
  description: Attribution DL Source
- name: attribution_medium
  type: STRING
  mode: NULLABLE
  description: Attribution Medium
- name: attribution_ua
  type: STRING
  mode: NULLABLE
  description: Attribution UA
- name: attribution_experiment
  type: STRING
  mode: NULLABLE
  description: Attribution Experiment
- name: attribution_variation
  type: STRING
  mode: NULLABLE
  description: Attribution Variation
- name: startup_profile_selection_reason
  type: STRING
  mode: NULLABLE
  description: Start up Profile Selection Reason
- name: normalized_os
  type: STRING
  mode: NULLABLE
  description: Normalized OS
- name: normalized_os_version
  type: STRING
  mode: NULLABLE
  description: Normalized OS Version
- name: distribution_id
  type: STRING
  mode: NULLABLE
  description: Distribution ID
- name: isp
  type: STRING
  mode: NULLABLE
  description: ISP
- name: is_desktop
  type: BOOLEAN
  mode: NULLABLE
  description: Indicates if the client is included in the desktop KPI
- name: days_seen_bits
  type: INTEGER
  mode: NULLABLE
- name: days_active_bits
  type: INTEGER
  mode: NULLABLE
- name: ping_sent_metric_date
  type: BOOLEAN
  mode: NULLABLE
  description: Ping Sent on Metric Date
- name: ping_sent_week_4
  type: BOOLEAN
  mode: NULLABLE
  description: Ping Sent Week 4
- name: active_metric_date
  type: BOOLEAN
  mode: NULLABLE
  description: Active on Metric Date
- name: retained_week_4
  type: BOOLEAN
  mode: NULLABLE
  description: Retained Week 4
- name: new_profile_metric_date
  type: BOOLEAN
  mode: NULLABLE
  description: New Profile on Metric Date
- name: repeat_profile
  type: BOOLEAN
  mode: NULLABLE
  description: Repeat Profile
- name: retained_week_4_new_profile
  type: BOOLEAN
  mode: NULLABLE
  description: Retained Week 4 New Profile
- name: lifecycle_stage
  type: STRING
  mode: NULLABLE
