fields:
- mode: NULLABLE
  name: created
  type: TIMESTAMP
- mode: NULLABLE
  name: id
  type: STRING
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - mode: NULLABLE
    name: value
    type: STRING
  mode: REPEATED
  name: metadata
  type: RECORD
