fields:
- description: A JSON string containing any payload properties not present in the
    schema
  mode: NULLABLE
  name: additional_properties
  type: STRING
- mode: NULLABLE
  name: assigned_to
  type: INTEGER
- mode: REPEATED
  name: blocked_by
  type: INTEGER
- mode: NULLABLE
  name: bug_id
  type: INTEGER
- mode: NULLABLE
  name: bug_severity
  type: STRING
- mode: NULLABLE
  name: bug_status
  type: STRING
- mode: NULLABLE
  name: component
  type: STRING
- mode: NULLABLE
  name: creation_ts
  type: STRING
- mode: NULLABLE
  name: delta_ts
  type: STRING
- mode: REPEATED
  name: depends_on
  type: INTEGER
- description: The document ID specified in the URI when the client sent this message
  mode: NULLABLE
  name: document_id
  type: STRING
- mode: NULLABLE
  name: duplicate_of
  type: INTEGER
- mode: REPEATED
  name: duplicates
  type: INTEGER
- fields:
  - mode: NULLABLE
    name: name
    type: STRING
  - mode: NULLABLE
    name: requestee_id
    type: INTEGER
  - mode: NULLABLE
    name: setter_id
    type: INTEGER
  - mode: NULLABLE
    name: status
    type: STRING
  mode: REPEATED
  name: flags
  type: RECORD
- mode: REPEATED
  name: groups
  type: STRING
- mode: REPEATED
  name: keywords
  type: STRING
- fields:
  - description: Results of a geographic lookup based on the client's IP address
    fields:
    - mode: NULLABLE
      name: city
      type: STRING
    - description: An ISO 3166-1 alpha-2 country code
      mode: NULLABLE
      name: country
      type: STRING
    - description: The specific geo database version used for this lookup
      mode: NULLABLE
      name: db_version
      type: STRING
    - description: First major country subdivision, typically a state, province, or
        county
      mode: NULLABLE
      name: subdivision1
      type: STRING
    - description: Second major country subdivision; not applicable for most countries
      mode: NULLABLE
      name: subdivision2
      type: STRING
    mode: NULLABLE
    name: geo
    type: RECORD
  - description: Headers included in the client's HTTP request
    fields:
    - description: Date HTTP header
      mode: NULLABLE
      name: date
      type: STRING
    - description: DNT (Do Not Track) HTTP header
      mode: NULLABLE
      name: dnt
      type: STRING
    - description: X-Debug-Id HTTP header
      mode: NULLABLE
      name: x_debug_id
      type: STRING
    - description: X-PingSender-Version HTTP header
      mode: NULLABLE
      name: x_pingsender_version
      type: STRING
    - description: X-Source-Tags HTTP header
      mode: NULLABLE
      name: x_source_tags
      type: STRING
    - description: X-Telemetry-Agent HTTP header
      mode: NULLABLE
      name: x_telemetry_agent
      type: STRING
    - description: X-Foxsec-IP-Reputation header
      mode: NULLABLE
      name: x_foxsec_ip_reputation
      type: STRING
    - description: X-LB-Tags HTTP header
      mode: NULLABLE
      name: x_lb_tags
      type: STRING
    - mode: NULLABLE
      name: parsed_date
      type: TIMESTAMP
    - mode: REPEATED
      name: parsed_x_source_tags
      type: STRING
    - fields:
      - mode: NULLABLE
        name: tls_version
        type: STRING
      - mode: NULLABLE
        name: tls_cipher_hex
        type: STRING
      mode: NULLABLE
      name: parsed_x_lb_tags
      type: RECORD
    mode: NULLABLE
    name: header
    type: RECORD
  - description: Parsed components of the client's user agent string
    fields:
    - mode: NULLABLE
      name: browser
      type: STRING
    - mode: NULLABLE
      name: os
      type: STRING
    - mode: NULLABLE
      name: version
      type: STRING
    mode: NULLABLE
    name: user_agent
    type: RECORD
  - description: Results of ISP lookup based on the client's IP address
    fields:
    - description: The specific geo ISP database version used for this lookup
      mode: NULLABLE
      name: db_version
      type: STRING
    - description: The name of the ISP associated with the client's IP address
      mode: NULLABLE
      name: name
      type: STRING
    - description: The name of a specific business entity associated with the client's
        IP address when available; otherwise the ISP name
      mode: NULLABLE
      name: organization
      type: STRING
    mode: NULLABLE
    name: isp
    type: RECORD
  mode: NULLABLE
  name: metadata
  type: RECORD
- description: Set to "Other" if this message contained an unrecognized app name
  mode: NULLABLE
  name: normalized_app_name
  type: STRING
- description: Set to "Other" if this message contained an unrecognized channel name
  mode: NULLABLE
  name: normalized_channel
  type: STRING
- description: An ISO 3166-1 alpha-2 country code
  mode: NULLABLE
  name: normalized_country_code
  type: STRING
- description: Set to "Other" if this message contained an unrecognized OS name
  mode: NULLABLE
  name: normalized_os
  type: STRING
- mode: NULLABLE
  name: normalized_os_version
  type: STRING
- mode: NULLABLE
  name: priority
  type: STRING
- mode: NULLABLE
  name: product
  type: STRING
- mode: NULLABLE
  name: qa_contact
  type: INTEGER
- mode: NULLABLE
  name: reporter
  type: INTEGER
- mode: NULLABLE
  name: resolution
  type: STRING
- description: Hashed version of client_id (if present) useful for partitioning; ranges
    from 0 to 99
  mode: NULLABLE
  name: sample_id
  type: INTEGER
- description: Time when the ingestion edge server accepted this message
  mode: NULLABLE
  name: submission_timestamp
  type: TIMESTAMP
- mode: NULLABLE
  name: target_milestone
  type: STRING
- mode: NULLABLE
  name: version
  type: STRING
