type: BIGCONFIG_FILE
table_deployments:
- collection:
    name: Browser KPI Metrics
  deployments:
  - fq_table_name: moz-fx-data-shared-prod.klar_ios_derived.new_profiles_v1
    table_metrics:
    - metric_type:
        type: PREDEFINED
        predefined_metric: FRESHNESS
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
    - metric_type:
        type: PREDEFINED
        predefined_metric: VOLUME
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
