fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
- mode: NULLABLE
  name: client_id
  type: STRING
- mode: NULLABLE
  name: sample_id
  type: INTEGER
- mode: NULLABLE
  name: app_version
  type: STRING
- mode: NULLABLE
  name: country
  type: STRING
- mode: NULLABLE
  name: locale
  type: STRING
- mode: NULLABLE
  name: app_os
  type: STRING
- fields:
  - mode: NULLABLE
    name: addon
    type: STRING
  - mode: NULLABLE
    name: version
    type: STRING
  mode: REPEATED
  name: addons
  type: RECORD
