fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: partner
  type: STRING
  mode: NULLABLE
  description: Partner
- name: device
  type: STRING
  mode: NULLABLE
  description: Device
- name: channel
  type: STRING
  mode: NULLABLE
  description: Channel
- name: country
  type: STRING
  mode: NULLABLE
  description: Country
- name: dau
  type: INTEGER
  mode: NULLABLE
  description: DAU
- name: dau_engaged_w_sap
  type: INTEGER
  mode: NULLABLE
  description: DAU Engaged with SAP
- name: sap
  type: INTEGER
  mode: NULLABLE
  description: SAP
- name: tagged_sap
  type: INTEGER
  mode: NULLABLE
  description: Tagged SAP
- name: tagged_follow_on
  type: INTEGER
  mode: NULLABLE
  description: Tagged Follow On
- name: ad_click
  type: INTEGER
  mode: NULLABLE
  description: Ad Click
- name: search_with_ads
  type: INTEGER
  mode: NULLABLE
  description: Search with Ads
- name: organic
  type: INTEGER
  mode: NULLABLE
  description: Organic
- name: ad_click_organic
  type: INTEGER
  mode: NULLABLE
  description: Ad Click Organic
- name: search_with_ads_organic
  type: INTEGER
  mode: NULLABLE
  description: Number of Organic Searches with Ads
- name: monetizable_sap
  type: INTEGER
  mode: NULLABLE
  description: Monetizable SAP
- name: dau_w_engine_as_default
  type: INTEGER
  mode: NULLABLE
  description: DAU with Engine as Default
- name: serp_events_client_count
  type: INTEGER
  mode: NULLABLE
  description: SERP Events Client Count
- name: serp_events_clients_with_ad_blocker_inferred
  type: INTEGER
  mode: NULLABLE
  description: SERP Events Clients with Ad Blocker Inferred
- name: serp_events_sap
  type: INTEGER
  mode: NULLABLE
  description: SERP Events SAP
- name: serp_events_tagged_sap
  type: INTEGER
  mode: NULLABLE
  description: SERP Events Tagged SAP
- name: serp_events_tagged_follow_on
  type: INTEGER
  mode: NULLABLE
  description: SERP Events Tagged Follow On
- name: serp_events_ad_click
  type: INTEGER
  mode: NULLABLE
  description: SERP Events Ad Click
- name: serp_events_search_with_ads
  type: INTEGER
  mode: NULLABLE
  description: SERP Events Search with Ads
- name: serp_events_organic
  type: INTEGER
  mode: NULLABLE
  description: SERP Events Organic
- name: serp_events_ad_click_organic
  type: INTEGER
  mode: NULLABLE
  description: SERP Events Ad Click Organic
- name: serp_events_search_with_ads_organic
  type: INTEGER
  mode: NULLABLE
  description: SERP Events Search with Ads Organic
- name: serp_events_sap_with_ad_blocker_inferred
  type: INTEGER
  mode: NULLABLE
  description: SERP Events SAP with Inferred Ad Blocker
- name: serp_events_num_ads_visible
  type: INTEGER
  mode: NULLABLE
  description: SERP Events Number of Ads Visible
- name: serp_events_num_ads_blocked
  type: INTEGER
  mode: NULLABLE
  description: SERP Events Number of Ads Blocked
