fields:
- mode: NULLABLE
  name: destination_id
  type: STRING
  description: |
    Foreign key referencing the destination warehouse that was used.
- mode: NULLABLE
  name: measured_month
  type: DATE
  description: |
    Month of the usage activity.
- mode: NULLABLE
  name: dollars_spent
  type: BIGNUMERIC
  description: |
    Total USD used by the destination for the given month.
