fields:
- name: client_id
  type: STRING
  mode: NULLABLE
  description: null
- name: sample_id
  type: INTEGER
  mode: NULLABLE
- name: first_seen_date
  type: DATE
  mode: NULLABLE
- name: second_seen_date
  type: DATE
  mode: NULLABLE
- name: architecture
  type: STRING
  mode: NULLABLE
- name: app_build_id
  type: STRING
  mode: NULLABLE
- name: app_name
  type: STRING
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
- name: platform_version
  type: STRING
  mode: NULLABLE
- name: vendor
  type: STRING
  mode: NULLABLE
- name: app_version
  type: STRING
  mode: NULLABLE
- name: xpcom_abi
  type: STRING
  mode: NULLABLE
- name: document_id
  type: STRING
  mode: NULLABLE
- name: distribution_id
  type: STRING
  mode: NULLABLE
- name: partner_distribution_version
  type: STRING
  mode: NULLABLE
- name: partner_distributor
  type: STRING
  mode: NULLABLE
- name: partner_distributor_channel
  type: STRING
  mode: NULLABLE
- name: partner_id
  type: STRING
  mode: NULLABLE
- name: attribution_campaign
  type: STRING
  mode: NULLABLE
- name: attribution_content
  type: STRING
  mode: NULLABLE
- name: attribution_experiment
  type: STRING
  mode: NULLABLE
- name: attribution_medium
  type: STRING
  mode: NULLABLE
- name: attribution_source
  type: STRING
  mode: NULLABLE
- name: attribution_ua
  type: STRING
  mode: NULLABLE
- name: engine_data_load_path
  type: STRING
  mode: NULLABLE
- name: engine_data_name
  type: STRING
  mode: NULLABLE
- name: engine_data_origin
  type: STRING
  mode: NULLABLE
- name: engine_data_submission_url
  type: STRING
  mode: NULLABLE
- name: apple_model_id
  type: STRING
  mode: NULLABLE
- name: city
  type: STRING
  mode: NULLABLE
- name: db_version
  type: STRING
  mode: NULLABLE
- name: subdivision1
  type: STRING
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: normalized_os
  type: STRING
  mode: NULLABLE
- name: normalized_os_version
  type: STRING
  mode: NULLABLE
- name: startup_profile_selection_reason
  type: STRING
  mode: NULLABLE
- name: attribution_dltoken
  type: STRING
  mode: NULLABLE
- name: attribution_dlsource
  type: STRING
  mode: NULLABLE
- name: metadata
  type: RECORD
  mode: NULLABLE
  fields:
  - name: first_seen_date_source_ping
    type: STRING
    mode: NULLABLE
  - name: reported_main_ping
    type: BOOLEAN
    mode: NULLABLE
  - name: reported_new_profile_ping
    type: BOOLEAN
    mode: NULLABLE
  - name: reported_shutdown_ping
    type: BOOLEAN
    mode: NULLABLE
