fields:
- name: accessibility_services
  type: STRING
  mode: REPEATED
- name: additional_properties
  type: STRING
  mode: NULLABLE
- name: arch
  type: STRING
  mode: NULLABLE
- name: bug_1501329_affected
  type: BOOLEAN
  mode: NULLABLE
- name: campaign
  type: STRING
  mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
- name: created
  type: STRING
  mode: NULLABLE
- name: default_browser
  type: BOOLEAN
  mode: NULLABLE
- name: default_search
  type: STRING
  mode: NULLABLE
- name: device
  type: STRING
  mode: NULLABLE
- name: display_version
  type: STRING
  mode: NULLABLE
- name: distribution_id
  type: STRING
  mode: NULLABLE
- name: document_id
  type: STRING
  mode: NULLABLE
- name: durations
  type: INTEGER
  mode: NULLABLE
- name: experiments
  type: STRING
  mode: REPEATED
- name: flash_usage
  type: INTEGER
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
- name: metadata
  type: RECORD
  mode: NULLABLE
  fields:
  - name: geo
    type: RECORD
    mode: NULLABLE
    fields:
    - name: city
      type: STRING
      mode: NULLABLE
    - name: country
      type: STRING
      mode: NULLABLE
    - name: db_version
      type: STRING
      mode: NULLABLE
    - name: subdivision1
      type: STRING
      mode: NULLABLE
    - name: subdivision2
      type: STRING
      mode: NULLABLE
  - name: header
    type: RECORD
    mode: NULLABLE
    fields:
    - name: date
      type: STRING
      mode: NULLABLE
    - name: dnt
      type: STRING
      mode: NULLABLE
    - name: x_debug_id
      type: STRING
      mode: NULLABLE
    - name: x_pingsender_version
      type: STRING
      mode: NULLABLE
    - name: x_source_tags
      type: STRING
      mode: NULLABLE
    - name: x_telemetry_agent
      type: STRING
      mode: NULLABLE
    - name: x_foxsec_ip_reputation
      type: STRING
      mode: NULLABLE
    - name: x_lb_tags
      type: STRING
      mode: NULLABLE
    - name: parsed_date
      type: TIMESTAMP
      mode: NULLABLE
    - name: parsed_x_source_tags
      type: STRING
      mode: REPEATED
    - name: parsed_x_lb_tags
      type: RECORD
      mode: NULLABLE
      fields:
      - name: tls_version
        type: STRING
        mode: NULLABLE
      - name: tls_cipher_hex
        type: STRING
        mode: NULLABLE
  - name: uri
    type: RECORD
    mode: NULLABLE
    fields:
    - name: app_build_id
      type: STRING
      mode: NULLABLE
    - name: app_name
      type: STRING
      mode: NULLABLE
    - name: app_update_channel
      type: STRING
      mode: NULLABLE
    - name: app_version
      type: STRING
      mode: NULLABLE
  - name: user_agent
    type: RECORD
    mode: NULLABLE
    fields:
    - name: browser
      type: STRING
      mode: NULLABLE
    - name: os
      type: STRING
      mode: NULLABLE
    - name: version
      type: STRING
      mode: NULLABLE
  - name: isp
    type: RECORD
    mode: NULLABLE
    fields:
    - name: db_version
      type: STRING
      mode: NULLABLE
    - name: name
      type: STRING
      mode: NULLABLE
    - name: organization
      type: STRING
      mode: NULLABLE
- name: normalized_app_name
  type: STRING
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
- name: normalized_country_code
  type: STRING
  mode: NULLABLE
- name: normalized_os
  type: STRING
  mode: NULLABLE
- name: normalized_os_version
  type: STRING
  mode: NULLABLE
- name: os
  type: STRING
  mode: NULLABLE
- name: osversion
  type: STRING
  mode: NULLABLE
- name: profile_date
  type: INTEGER
  mode: NULLABLE
- name: sample_id
  type: INTEGER
  mode: NULLABLE
- name: searches
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: INTEGER
    mode: NULLABLE
- name: seq
  type: INTEGER
  mode: NULLABLE
- name: sessions
  type: INTEGER
  mode: NULLABLE
- name: show_tracker_stats_share
  type: BOOLEAN
  mode: NULLABLE
- name: submission_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: tz
  type: INTEGER
  mode: NULLABLE
- name: v
  type: INTEGER
  mode: NULLABLE
- name: campaign_id
  type: STRING
  mode: NULLABLE
- name: fennec
  type: RECORD
  mode: NULLABLE
  fields:
  - name: addons
    type: RECORD
    mode: NULLABLE
    fields:
    - name: active
      type: STRING
      mode: REPEATED
    - name: disabled
      type: STRING
      mode: REPEATED
  - name: new_tab
    type: RECORD
    mode: NULLABLE
    fields:
    - name: pocket_stories_clicked
      type: INTEGER
      mode: NULLABLE
    - name: top_sites_clicked
      type: INTEGER
      mode: NULLABLE
  - name: page_options
    type: RECORD
    mode: NULLABLE
    fields:
    - name: bookmark_with_star
      type: INTEGER
      mode: NULLABLE
    - name: print
      type: INTEGER
      mode: NULLABLE
    - name: save_as_pdf
      type: INTEGER
      mode: NULLABLE
    - name: total_added_search_engines
      type: INTEGER
      mode: NULLABLE
    - name: total_sites_pinned_to_topsites
      type: INTEGER
      mode: NULLABLE
    - name: view_source
      type: INTEGER
      mode: NULLABLE
    - name: current_pwas_count
      type: INTEGER
      mode: NULLABLE
  - name: settings_advanced
    type: RECORD
    mode: NULLABLE
    fields:
    - name: restore_tabs
      type: BOOLEAN
      mode: NULLABLE
    - name: show_images
      type: STRING
      mode: NULLABLE
    - name: show_web_fonts
      type: BOOLEAN
      mode: NULLABLE
  - name: settings_general
    type: RECORD
    mode: NULLABLE
    fields:
    - name: compact_tabs
      type: BOOLEAN
      mode: NULLABLE
    - name: full_screen_browsing
      type: BOOLEAN
      mode: NULLABLE
    - name: homepage
      type: RECORD
      mode: NULLABLE
      fields:
      - name: bookmarks_enabled
        type: BOOLEAN
        mode: NULLABLE
      - name: custom_homepage
        type: BOOLEAN
        mode: NULLABLE
      - name: custom_homepage_use_for_newtab
        type: BOOLEAN
        mode: NULLABLE
      - name: history_enabled
        type: BOOLEAN
        mode: NULLABLE
      - name: pocket_enabled
        type: BOOLEAN
        mode: NULLABLE
      - name: recent_bookmarks_enabled
        type: BOOLEAN
        mode: NULLABLE
      - name: topsites_enabled
        type: BOOLEAN
        mode: NULLABLE
      - name: visited_enabled
        type: BOOLEAN
        mode: NULLABLE
    - name: tab_queue
      type: BOOLEAN
      mode: NULLABLE
    - name: tab_queue_usage_count
      type: INTEGER
      mode: NULLABLE
  - name: settings_notifications
    type: RECORD
    mode: NULLABLE
    fields:
    - name: product_feature_tips
      type: BOOLEAN
      mode: NULLABLE
  - name: settings_privacy
    type: RECORD
    mode: NULLABLE
    fields:
    - name: do_not_track
      type: BOOLEAN
      mode: NULLABLE
    - name: master_password
      type: BOOLEAN
      mode: NULLABLE
    - name: master_password_usage_count
      type: INTEGER
      mode: NULLABLE
  - name: sync
    type: RECORD
    mode: NULLABLE
    fields:
    - name: only_over_wifi
      type: BOOLEAN
      mode: NULLABLE
- name: enhanced_search_ready
  type: BOOLEAN
  mode: NULLABLE
- name: enhanced_search_used
  type: BOOLEAN
  mode: NULLABLE
- name: enhanced_search_version
  type: STRING
  mode: NULLABLE
- name: default_mail_client
  type: STRING
  mode: NULLABLE
- name: default_new_tab_experience
  type: STRING
  mode: NULLABLE
- name: system_theme
  type: STRING
  mode: NULLABLE
- name: landings
  type: INTEGER
  mode: NULLABLE
- name: open_tab_count
  type: INTEGER
  mode: NULLABLE
- name: profile_group_id
  type: STRING
  mode: NULLABLE
