fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
- mode: NULLABLE
  name: hashed_addon_id
  type: STRING
- mode: NULLABLE
  name: total_downloads
  type: INTEGER
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: downloads_per_campaign
  type: RECORD
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: downloads_per_content
  type: RECORD
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: downloads_per_source
  type: RECORD
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: downloads_per_medium
  type: RECORD
