fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: day_of_week
  type: STRING
  mode: NULLABLE
- name: year
  type: INTEGER
  mode: NULLABLE
- name: month
  type: INTEGER
  mode: NULLABLE
- name: quarter
  type: INTEGER
  mode: NULLABLE
- name: week_number
  type: INTEGER
  mode: NULLABLE
- name: first_date_of_month
  type: DATE
  mode: NULLABLE
  description: First Date of Month
- name: first_date_of_quarter
  type: DATE
  mode: NULLABLE
  description: First Date of Quarter
- name: day_of_year
  type: INTEGER
  mode: NULLABLE
