fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: metadata
  type: RECORD
  mode: NULLABLE
  fields:
  - name: document_id
    type: STRING
    mode: NULLABLE
  - name: timestamp
    type: INTEGER
    mode: NULLABLE
  - name: date
    type: STRING
    mode: NULLABLE
- name: changeset_id
  type: STRING
  mode: NULLABLE
- name: review_system_used
  type: STRING
  mode: NULLABLE
- name: repository
  type: STRING
  mode: NULLABLE
- name: push_date
  type: INTEGER
  mode: NULLABLE
- name: landing_system
  type: STRING
  mode: NULLABLE
- name: diffstat
  type: RECORD
  mode: NULLABLE
  fields:
  - name: additions
    type: INTEGER
    mode: NULLABLE
  - name: changed_files
    type: INTEGER
    mode: NULLABLE
  - name: deletions
    type: INTEGER
    mode: NULLABLE
