type: BIGCONFIG_FILE
tag_deployments:
- collection:
    name: Google Analytics
    description: All checks related to GA tables
- deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.mozilla_org_derived.blogs_goals_v2.date
    metrics:
    - metric_type:
        type: PREDEFINED
        predefined_metric: COUNT_DUPLICATES
      threshold:
        type: CONSTANT
        lower_bound: 0.0
        upper_bound: 0.0
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.mozilla_org_derived.blogs_goals_v2.visit_identifier
    metrics:
    - metric_type:
        type: PREDEFINED
        predefined_metric: COUNT_DUPLICATES
      threshold:
        type: CONSTANT
        lower_bound: 0.0
        upper_bound: 0.0
    - metric_type:
      type: TEMPLATE
      template_id: 947
      aggregation_type: COUNT
      template_name: visit_identifier_regex_check
      metric_name: COUNT of visit_identifier_regex_check
      group_by:
      - date
      threshold:
        type: CONSTANT
        upper_bound: 0.0
        lower_bound: 0.0
      parameters:
      - key: column_name
        string_value: visit_identifier
      lookback:
        lookback_window:
          interval_type: DAYS
          interval_value: -1
        lookback_type: METRIC_TIME
        bucket_size: DAY
      rct_overrides:
      - date
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC

- deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.mozilla_org_derived.blogs_goals_v2.*
    metrics:
    - metric_type:
        type: PREDEFINED
        predefined_metric: FRESHNESS_DATA
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
    - metric_type:
        type: PREDEFINED
        predefined_metric: VOLUME_DATA
      metric_schedule:
        named_schedule:
          name: Default Schedule - 13:00 UTC
