type: BIGCONFIG_FILE
tag_deployments:
- collection:
    name: Operational Checks
    notification_channels:
    - slack: '#de-bigeye-triage'
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_focus_derived.baseline_clients_daily_v1.submission_date
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_focus_derived.baseline_clients_daily_v1.client_id
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_focus_derived.baseline_clients_daily_v1.sample_id
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_focus_derived.baseline_clients_daily_v1.first_seen_date
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_focus_derived.baseline_clients_daily_v1.first_run_date
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_focus_derived.baseline_clients_daily_v1.durations
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_focus_derived.baseline_clients_daily_v1.normalized_os
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_focus_derived.baseline_clients_daily_v1.normalized_os_version
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_focus_derived.baseline_clients_daily_v1.locale
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_focus_derived.baseline_clients_daily_v1.country
    metrics:
    - saved_metric_id: is_not_null
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_focus_derived.baseline_clients_daily_v1.normalized_channel
    metrics:
    - saved_metric_id: is_valid_channel
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_focus_derived.baseline_clients_daily_v1.country
    metrics:
    - saved_metric_id: is_2_char_len
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_focus_derived.baseline_clients_daily_v1.*
    metrics:
    - saved_metric_id: freshness
    - saved_metric_id: volume
