fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
- mode: NULLABLE
  name: namespace
  type: STRING
- mode: NULLABLE
  name: doc_type
  type: STRING
- mode: NULLABLE
  name: decoded
  type: INTEGER
- mode: NULLABLE
  name: live
  type: INTEGER
- mode: NULLABLE
  name: stable
  type: INTEGER
