fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: null
- name: client_id
  type: STRING
  mode: NULLABLE
  description: null
- name: sample_id
  type: INTEGER
  mode: NULLABLE
  description: null
- name: install_source
  type: STRING
  mode: NULLABLE
  description: 'The source of a profile installation.

    '
- name: submission_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: adjust_ad_group
  type: STRING
  mode: NULLABLE
- name: adjust_campaign
  type: STRING
  mode: NULLABLE
- name: adjust_creative
  type: STRING
  mode: NULLABLE
- name: adjust_network
  type: STRING
  mode: NULLABLE
- name: adjust_attribution_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: submission_timestamp_1
  type: TIMESTAMP
  mode: NULLABLE
- name: play_store_attribution_campaign
  type: STRING
  mode: NULLABLE
- name: play_store_attribution_medium
  type: STRING
  mode: NULLABLE
- name: play_store_attribution_source
  type: STRING
  mode: NULLABLE
- name: play_store_attribution_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: submission_timestamp_2
  type: TIMESTAMP
  mode: NULLABLE
- name: meta_attribution_app
  type: STRING
  mode: NULLABLE
- name: meta_attribution_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: paid_vs_organic
  type: STRING
  mode: NULLABLE
