fields:
- name: id
  type: INTEGER
  mode: NULLABLE
- name: url
  type: STRING
  mode: NULLABLE
- name: name
  type: STRING
  mode: NULLABLE
- name: company
  type: STRING
  mode: NULLABLE
- name: category
  type: STRING
  mode: NULLABLE
- name: created_at
  type: DATETIME
  mode: NULLABLE
- name: updated_at
  type: DATETIME
  mode: NULLABLE
- name: percent_done
  type: STRING
  mode: NULLABLE
- name: status
  type: STRING
  mode: NULLABLE
- name: walmart_product_id
  type: INTEGER
  mode: NULLABLE
- name: total_fake_reviews
  type: INTEGER
  mode: NULLABLE
- name: total_legit_reviews
  type: INTEGER
  mode: NULLABLE
- name: total_reviews
  type: INTEGER
  mode: NULLABLE
- name: percentage_fake
  type: NUMERIC
  mode: NULLABLE
- name: completed
  type: BOOLEAN
  mode: NULLABLE
- name: rating
  type: NUMERIC
  mode: NULLABLE
- name: price
  type: STRING
  mode: NULLABLE
- name: percentage_fake_averaged
  type: NUMERIC
  mode: NULLABLE
- name: reviewers_count
  type: INTEGER
  mode: NULLABLE
