fields:
- name: metric_date
  type: DATE
  mode: NULLABLE
- name: first_seen_date
  type: DATE
  mode: NULLABLE
- name: app_name
  type: STRING
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: app_version
  type: STRING
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
- name: is_mobile
  type: BOOLEAN
  mode: NULLABLE
- name: ping_sent_metric_date
  type: INTEGER
  mode: NULLABLE
- name: ping_sent_week_4
  type: INTEGER
  mode: NULLABLE
- name: active_metric_date
  type: INTEGER
  mode: NULLABLE
- name: retained_week_4
  type: INTEGER
  mode: NULLABLE
- name: retained_week_4_new_profiles
  type: INTEGER
  mode: NULLABLE
- name: new_profiles_metric_date
  type: INTEGER
  mode: NULLABLE
- name: repeat_profiles
  type: INTEGER
  mode: NULLABLE
- name: lifecycle_stage
  type: STRING
  mode: NULLABLE
- name: play_store_attribution_campaign
  type: STRING
  mode: NULLABLE
- name: play_store_attribution_medium
  type: STRING
  mode: NULLABLE
- name: play_store_attribution_source
  type: STRING
  mode: NULLABLE
- name: meta_attribution_app
  type: STRING
  mode: NULLABLE
- name: install_source
  type: STRING
  mode: NULLABLE
- name: adjust_ad_group
  type: STRING
  mode: NULLABLE
- name: adjust_campaign
  type: STRING
  mode: NULLABLE
- name: adjust_creative
  type: STRING
  mode: NULLABLE
- name: adjust_network
  type: STRING
  mode: NULLABLE
- name: is_suspicious_device_client
  type: BOOLEAN
  mode: NULLABLE
- name: product_name
  type: STRING
  mode: NULLABLE
