fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: version_major
  type: INTEGER
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: platform
  type: STRING
  mode: NULLABLE
- name: metric
  type: STRING
  mode: NULLABLE
- name: rate
  type: NUMERIC
  mode: NULLABLE
