fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: normalized_os
  type: STRING
  mode: NULLABLE
  description: Normalized Operating System
- name: bookmarks_added_per_dau
  type: FLOAT
  mode: NULLABLE
  description: Bookmarks Added per Daily Active User
- name: bookmarks_opened_per_dau
  type: FLOAT
  mode: NULLABLE
  description: Bookmarks Opened per DAU
