fields:
- name: id
  type: INTEGER
  mode: NULLABLE
  description: null
- name: trigger_id
  type: INTEGER
  mode: NULLABLE
  description: null
- name: created_at
  type: TIMESTAMP
  mode: NULLABLE
  description: null
- name: kwargs
  type: STRING
  mode: NULLABLE
  description: null
- name: classpath
  type: STRING
  mode: NULLABLE
  description: null
- name: created_date
  type: TIMESTAMP
  mode: NULLABLE
- name: triggerer_id
  type: INTEGER
  mode: NULLABLE
