fields:
- description: null
  mode: NULLABLE
  name: id
  type: INTEGER
- description: null
  mode: NULLABLE
  name: trigger_id
  type: INTEGER
- description: null
  mode: NULLABLE
  name: created_at
  type: TIMESTAMP
- description: null
  mode: NULLABLE
  name: kwargs
  type: STRING
- description: null
  mode: NULLABLE
  name: classpath
  type: STRING
