fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: glean_client_id
  type: STRING
  mode: NULLABLE
- name: legacy_telemetry_client_id
  type: STRING
  mode: NULLABLE
- name: sample_id
  type: INTEGER
  mode: NULLABLE
- name: event_name
  type: STRING
  mode: NULLABLE
- name: event_timestamp
  type: INTEGER
  mode: NULLABLE
- name: event_id
  type: STRING
  mode: NULLABLE
- name: experiments
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: RECORD
    mode: NULLABLE
    fields:
    - name: branch
      type: STRING
      mode: NULLABLE
    - name: extra
      type: RECORD
      mode: NULLABLE
      fields:
      - name: type
        type: STRING
        mode: NULLABLE
      - name: enrollment_id
        type: STRING
        mode: NULLABLE
- name: seq
  type: INTEGER
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
- name: normalized_country_code
  type: STRING
  mode: NULLABLE
- name: normalized_engine
  type: STRING
  mode: NULLABLE
- name: pref_data_collection
  type: BOOLEAN
  mode: NULLABLE
- name: pref_sponsored_suggestions
  type: BOOLEAN
  mode: NULLABLE
- name: pref_fx_suggestions
  type: BOOLEAN
  mode: NULLABLE
- name: engagement_type
  type: STRING
  mode: NULLABLE
- name: interaction
  type: STRING
  mode: NULLABLE
- name: num_chars_typed
  type: INTEGER
  mode: NULLABLE
- name: num_total_results
  type: INTEGER
  mode: NULLABLE
- name: selected_position
  type: INTEGER
  mode: NULLABLE
- name: selected_result
  type: STRING
  mode: NULLABLE
- name: results
  type: RECORD
  mode: REPEATED
  fields:
  - name: position
    type: INTEGER
    mode: NULLABLE
  - name: result_type
    type: STRING
    mode: NULLABLE
  - name: product_result_type
    type: STRING
    mode: NULLABLE
  - name: result_group
    type: STRING
    mode: NULLABLE
- name: product_selected_result
  type: STRING
  mode: NULLABLE
- name: event_action
  type: STRING
  mode: NULLABLE
- name: is_terminal
  type: BOOLEAN
  mode: NULLABLE
- name: engaged_result_type
  type: STRING
  mode: NULLABLE
- name: product_engaged_result_type
  type: STRING
  mode: NULLABLE
- name: annoyance_signal_type
  type: STRING
  mode: NULLABLE
