fields:
- name: submission_date_s3
  type: DATE
  mode: NULLABLE
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: app_name
  type: STRING
  mode: NULLABLE
- name: os
  type: STRING
  mode: NULLABLE
- name: metadata
  type: RECORD
  mode: NULLABLE
  fields:
  - name: document_id
    type: STRING
    mode: NULLABLE
  - name: timestamp
    type: INTEGER
    mode: NULLABLE
  - name: date
    type: STRING
    mode: NULLABLE
  - name: geo_country
    type: STRING
    mode: NULLABLE
  - name: geo_city
    type: STRING
    mode: NULLABLE
  - name: app_build_id
    type: STRING
    mode: NULLABLE
  - name: normalized_channel
    type: STRING
    mode: NULLABLE
- name: application
  type: RECORD
  mode: NULLABLE
  fields:
  - name: name
    type: STRING
    mode: NULLABLE
- name: v
  type: INTEGER
  mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
- name: seq
  type: INTEGER
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
- name: osversion
  type: STRING
  mode: NULLABLE
- name: device
  type: STRING
  mode: NULLABLE
- name: arch
  type: STRING
  mode: NULLABLE
- name: profile_date
  type: INTEGER
  mode: NULLABLE
- name: default_search
  type: STRING
  mode: NULLABLE
- name: distribution_id
  type: STRING
  mode: NULLABLE
- name: created
  type: STRING
  mode: NULLABLE
- name: tz
  type: INTEGER
  mode: NULLABLE
- name: sessions
  type: INTEGER
  mode: NULLABLE
- name: durations
  type: INTEGER
  mode: NULLABLE
- name: searches
  type: RECORD
  mode: REPEATED
  fields:
  - name: key
    type: STRING
    mode: NULLABLE
  - name: value
    type: INTEGER
    mode: NULLABLE
- name: experiments
  type: STRING
  mode: REPEATED
- name: flash_usage
  type: INTEGER
  mode: NULLABLE
- name: campaign
  type: STRING
  mode: NULLABLE
- name: campaign_id
  type: STRING
  mode: NULLABLE
- name: default_browser
  type: BOOLEAN
  mode: NULLABLE
- name: show_tracker_stats_share
  type: BOOLEAN
  mode: NULLABLE
- name: accessibility_services
  type: STRING
  mode: REPEATED
- name: metadata_app_version
  type: STRING
  mode: NULLABLE
- name: bug_1501329_affected
  type: BOOLEAN
  mode: NULLABLE
