fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: user_agent
  type: STRING
  mode: NULLABLE
  description: User Agent - i.e. the browser name
- name: uninstalls_count
  type: INTEGER
  mode: NULLABLE
  description: Count of unique clients uninstalling
