fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
- name: sample_id
  type: INTEGER
  mode: NULLABLE
- name: paid_vs_organic
  type: STRING
  mode: NULLABLE
- name: is_suspicious_device_client
  type: BOOLEAN
  mode: NULLABLE
- name: adjust_ad_group
  type: STRING
  mode: NULLABLE
- name: adjust_campaign
  type: STRING
  mode: NULLABLE
- name: adjust_creative
  type: STRING
  mode: NULLABLE
- name: adjust_network
  type: STRING
  mode: NULLABLE
- name: adjust_attribution_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: play_store_attribution_campaign
  type: STRING
  mode: NULLABLE
- name: play_store_attribution_medium
  type: STRING
  mode: NULLABLE
- name: play_store_attribution_source
  type: STRING
  mode: NULLABLE
- name: play_store_attribution_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: meta_attribution_app
  type: STRING
  mode: NULLABLE
- name: meta_attribution_timestamp
  type: TIMESTAMP
  mode: NULLABLE
- name: install_source
  type: STRING
  mode: NULLABLE
- name: distribution_id
  type: STRING
  mode: NULLABLE
- name: product_name
  type: STRING
  mode: NULLABLE
