fields:
- name: shredder_run_date
  type: DATE
  mode: NULLABLE
- name: table_id
  type: STRING
  mode: NULLABLE
- name: start_time
  type: TIMESTAMP
  mode: NULLABLE
- name: end_time
  type: TIMESTAMP
  mode: NULLABLE
- name: run_time_hours
  type: FLOAT
  mode: NULLABLE
- name: avg_slots
  type: FLOAT
  mode: NULLABLE
- name: tib_processed
  type: FLOAT
  mode: NULLABLE
- name: slot_hours
  type: FLOAT
  mode: NULLABLE
- name: num_jobs
  type: INTEGER
  mode: NULLABLE
- name: num_job_errors
  type: INTEGER
  mode: NULLABLE
