fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
- mode: NULLABLE
  name: doc_type
  type: STRING
- mode: NULLABLE
  name: document_id
  type: STRING
- mode: NULLABLE
  name: client_id
  type: STRING
- mode: NULLABLE
  name: normalized_channel
  type: STRING
- mode: NULLABLE
  name: country
  type: STRING
- mode: NULLABLE
  name: locale
  type: STRING
- mode: NULLABLE
  name: app_name
  type: STRING
- mode: NULLABLE
  name: app_version
  type: STRING
- mode: NULLABLE
  name: os
  type: STRING
- mode: NULLABLE
  name: os_version
  type: STRING
- mode: NULLABLE
  name: timestamp
  type: TIMESTAMP
- mode: NULLABLE
  name: sample_id
  type: INTEGER
- mode: NULLABLE
  name: event_timestamp
  type: INTEGER
- mode: NULLABLE
  name: event_category
  type: STRING
- mode: NULLABLE
  name: event_method
  type: STRING
- mode: NULLABLE
  name: event_object
  type: STRING
- mode: NULLABLE
  name: event_string_value
  type: STRING
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - mode: NULLABLE
    name: value
    type: STRING
  mode: REPEATED
  name: event_map_values
  type: RECORD
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - fields:
    - mode: NULLABLE
      name: branch
      type: STRING
    - mode: NULLABLE
      name: enrollment_id
      type: STRING
    - mode: NULLABLE
      name: type
      type: STRING
    mode: NULLABLE
    name: value
    type: RECORD
  mode: REPEATED
  name: experiments
  type: RECORD
- mode: NULLABLE
  name: event_process
  type: STRING
- mode: NULLABLE
  name: subsession_id
  type: STRING
- mode: NULLABLE
  name: session_start_time
  type: TIMESTAMP
- mode: NULLABLE
  name: session_id
  type: STRING
- mode: NULLABLE
  name: build_id
  type: STRING
- fields:
  - mode: NULLABLE
    name: version
    type: STRING
  - mode: NULLABLE
    name: major_version
    type: NUMERIC
  - mode: NULLABLE
    name: minor_version
    type: NUMERIC
  - mode: NULLABLE
    name: is_major_release
    type: BOOLEAN
  mode: NULLABLE
  name: browser_version_info
  type: RECORD
