fields:
- description: null
  mode: NULLABLE
  name: timestamp
  type: TIMESTAMP
- description: null
  mode: NULLABLE
  name: id
  type: INTEGER
- description: null
  mode: NULLABLE
  name: filename
  type: STRING
- description: null
  mode: NULLABLE
  name: stacktrace
  type: STRING
