fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
- mode: NULLABLE
  name: addon_id
  type: STRING
- mode: NULLABLE
  name: dau
  type: INTEGER
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: dau_by_addon_version
  type: RECORD
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: dau_by_app_os
  type: RECORD
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: dau_by_app_version
  type: RECORD
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: dau_by_fenix_build
  type: RECORD
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: dau_by_country
  type: RECORD
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: dau_by_locale
  type: RECORD
