fields:
- name: id
  type: INTEGER
  mode: NULLABLE
- name: _fivetran_deleted
  type: BOOLEAN
  mode: NULLABLE
- name: _fivetran_synced
  type: TIMESTAMP
  mode: NULLABLE
- name: description
  type: STRING
  mode: NULLABLE
- name: key
  type: STRING
  mode: NULLABLE
- name: lead_id
  type: STRING
  mode: NULLABLE
- name: name
  type: STRING
  mode: NULLABLE
- name: permission_scheme_id
  type: INTEGER
  mode: NULLABLE
- name: project_category_id
  type: INTEGER
  mode: NULLABLE
- name: project_type_key
  type: STRING
  mode: NULLABLE
