type: BIGCONFIG_FILE
tag_deployments:
- collection:
    name: Browser Metrics (non-KPI)
    notification_channels:
    - slack: '#ds-bigeye-triage'
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.klar_ios_derived.attribution_clients_v1.client_id
    metrics:
    - saved_metric_id: is_unique
    - saved_metric_id: is_not_null
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.klar_ios_derived.attribution_clients_v1.*
    metrics:
    - saved_metric_id: freshness
    - saved_metric_id: volume
- collection:
    name: Operational Checks
    notification_channels:
    - slack: '#de-bigeye-triage'
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.klar_ios_derived.attribution_clients_v1.*
    metrics:
    - saved_metric_id: freshness
    - saved_metric_id: volume
