fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
- mode: NULLABLE
  name: service
  type: STRING
- mode: NULLABLE
  name: country
  type: STRING
- mode: NULLABLE
  name: LANGUAGE,
  type: STRING
- mode: NULLABLE
  name: app_version
  type: STRING
- mode: NULLABLE
  name: os_name
  type: STRING
- mode: NULLABLE
  name: os_version
  type: STRING
- mode: NULLABLE
  name: service_user_count
  type: INTEGER
