fields:
- name: date
  type: DATE
  mode: NULLABLE
  description: Date of the visit
- name: visit_identifier
  type: STRING
  mode: NULLABLE
  description: Visit Identifier - Uniquely identifies a visit; concatenation of user_pseudo_id
    and ga_session_id
- name: device_category
  type: STRING
  mode: NULLABLE
  description: Device Category - The device category the visitor used to visit the
    site
- name: operating_system
  type: STRING
  mode: NULLABLE
  description: Operating System - The operating system the visitor used to visit the
    site
- name: browser
  type: STRING
  mode: NULLABLE
  description: Browser - The browser the visiting device was using when it visited
    the site
- name: language
  type: STRING
  mode: NULLABLE
  description: Language - The language the visiting device was using when it visited
    the site
- name: country
  type: STRING
  mode: NULLABLE
  description: Country - The country from which events were reported, based on IP
    address
- name: source
  type: STRING
  mode: NULLABLE
  description: Source - Referring partner domain
- name: medium
  type: STRING
  mode: NULLABLE
  description: Medium - Category of the source, such as 'organic' for a search engine
- name: campaign
  type: STRING
  mode: NULLABLE
  description: Campaign - Identifier for the marketing campaign
- name: content
  type: STRING
  mode: NULLABLE
  description: Content - Indicates the particular link within a campaign
- name: blog
  type: STRING
  mode: NULLABLE
  description: Blog
- name: subblog
  type: STRING
  mode: NULLABLE
  description: Sub-Blog
- name: sessions
  type: INTEGER
  mode: NULLABLE
  description: Number of Sessions - The number of sessions with an entrances value
    of 1
