fields:
- name: account_name
  type: STRING
  mode: NULLABLE
  description: The name of the Google Ads account, e.g. Mozilla Firefox.
- name: account_id
  type: INTEGER
  mode: NULLABLE
  description: The ID associated with the account name.
- name: campaign_id
  type: INTEGER
  mode: NULLABLE
  description: The ID of the Google Ads campaign.
- name: campaign_name
  type: STRING
  mode: NULLABLE
  description: The name of the Google Ads campaign. We take the most recently reported
    name.
- name: campaign_region
  type: STRING
  mode: NULLABLE
  description: Only for App Campaigns. The region the campaign ran in.
- name: campaign_country_code
  type: STRING
  mode: NULLABLE
  description: Only for App Campaigns. The country the campaign ran in.
- name: campaign_language
  type: STRING
  mode: NULLABLE
  description: Only for App Campaigns. The language the campaign ran in.
