fields:
- name: source_project
  type: STRING
  mode: NULLABLE
  description: Project used for executing job
- name: creation_date
  type: DATE
  mode: NULLABLE
  description: Job creation date
- name: job_id
  type: STRING
  mode: NULLABLE
  description: ID of job
- name: job_type
  type: STRING
  mode: NULLABLE
  description: The type of the job
- name: reservation_id
  type: STRING
  mode: NULLABLE
  description: Name of the primary reservation (slots for distributing resources)
    assigned to this job
- name: cache_hit
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the query results of this job were from a cache
- name: state
  type: STRING
  mode: NULLABLE
  description: Running state of the job
- name: statement_type
  type: STRING
  mode: NULLABLE
  description: The type of query statement
- name: reference_project_id
  type: STRING
  mode: NULLABLE
- name: reference_dataset_id
  type: STRING
  mode: NULLABLE
- name: reference_table_id
  type: STRING
  mode: NULLABLE
- name: destination_project_id
  type: STRING
  mode: NULLABLE
- name: destination_dataset_id
  type: STRING
  mode: NULLABLE
- name: destination_table_id
  type: STRING
  mode: NULLABLE
- name: user_email
  type: STRING
  mode: NULLABLE
- name: task_duration
  type: INTERVAL
  mode: NULLABLE
- name: total_terabytes_processed
  type: FLOAT
  mode: NULLABLE
- name: total_terabytes_billed
  type: FLOAT
  mode: NULLABLE
- name: total_slot_ms
  type: INTEGER
  mode: NULLABLE
- name: error_location
  type: STRING
  mode: NULLABLE
- name: error_reason
  type: STRING
  mode: NULLABLE
- name: error_message
  type: STRING
  mode: NULLABLE
- name: resource_warning
  type: STRING
  mode: NULLABLE
