fields:
- name: task_id
  type: STRING
  mode: NULLABLE
- name: run_id
  type: INTEGER
  mode: NULLABLE
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: run_cost
  type: FLOAT
  mode: NULLABLE
