fields:
- name: date
  type: DATE
  mode: NULLABLE
- name: country_code
  type: STRING
  mode: NULLABLE
- name: impressions
  type: INTEGER
  mode: NULLABLE
- name: clicks
  type: INTEGER
  mode: NULLABLE
- name: new_profiles
  type: INTEGER
  mode: NULLABLE
- name: activated_profiles
  type: INTEGER
  mode: NULLABLE
- name: spend
  type: FLOAT
  mode: NULLABLE
- name: lifetime_value
  type: FLOAT
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: campaign_region
  type: STRING
  mode: NULLABLE
