fields:
- name: email_id
  type: STRING
  mode: NULLABLE
  description: key to connect to rt_newsletters\ and rt_mofo_contact relational databases
- name: basket_token
  type: STRING
  mode: NULLABLE
  description: token generated for unsubscribe and email\ preference center links;
    this was called token__c in SFMC
- name: sfdc_id
  type: STRING
  mode: NULLABLE
  description: key to connect to rt_mofo_campaign_member\ and rt_mofo_opportunity
    relational databases
- name: fxa_id
  type: STRING
  mode: NULLABLE
  description: key to connect to rt_moco_fxa_service relational database
- name: double_opt_in
  type: BOOLEAN
  mode: NULLABLE
  description: TRUE = double opted-in FALSE = not opted-in.
- name: has_opted_out_of_email
  type: BOOLEAN
  mode: NULLABLE
  description: TRUE = has opted-out (exclude them from email sends)\ FALSE = can send
    emails
- name: email_lang
  type: STRING
  mode: NULLABLE
  description: preferred email language
- name: email_format
  type: STRING
  mode: NULLABLE
  description: preferred email format - values are H for HTML or T for\ Text and sometimes
    this field is blank for a contact
- name: mailing_country
  type: STRING
  mode: NULLABLE
  description: subscriber's country
- name: cohort
  type: STRING
  mode: NULLABLE
  description: stores values for automation testing
- name: fxa_created_date
  type: DATE
  mode: NULLABLE
  description: records the date/time a subscriber created a Firefox account
- name: fxa_first_service
  type: STRING
  mode: NULLABLE
  description: the first service added to the Firefox account
- name: fxa_account_deleted
  type: BOOLEAN
  mode: NULLABLE
  description: has the fxa account been deleted?
- name: sub_mozilla_foundation
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to Mozilla Foundation
- name: sub_common_voice
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to Mozilla Common Voice
- name: sub_hubs
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to Mozilla Hubs
- name: sub_mixed_reality
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to Mixed Reality
- name: sub_internet_health_report
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to Insights
- name: sub_miti
  type: BOOLEAN
  mode: NULLABLE
  description: null
- name: sub_mozilla_fellowship_awardee_alumni
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to Fellowship and Awardee Alumni
- name: sub_mozilla_festival
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to MozFest
- name: sub_mozilla_technology
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to Mozilla Technology
- name: sub_mozillians_nda
  type: BOOLEAN
  mode: NULLABLE
  description: NDA'd Mozillians
- name: sub_firefox_accounts_journey
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to Firefox Account Tips
- name: sub_knowledge_is_power
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to Knowledge is Power
- name: sub_take_action_for_the_internet
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to Take Action for the Internet
- name: sub_test_pilot
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to New Product Testing
- name: sub_firefox_news
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to Firefox News
- name: sub_about_mozilla
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to Mozilla Community
- name: sub_apps_and_hacks
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to Developer newsletter
- name: sub_rally
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to Mozilla Rally
- name: sub_firefox_sweepstakes
  type: BOOLEAN
  mode: NULLABLE
  description: subscribed to Firefox Sweepstakes
- name: vpn_waitlist_geo
  type: STRING
  mode: NULLABLE
  description: VPN waitlist country location
- name: vpn_waitlist_platform
  type: STRING
  mode: REPEATED
  description: VPN waitlist platform name
- name: relay_waitlist_geo
  type: STRING
  mode: NULLABLE
  description: Relay waitlist country location
- name: recipient_id
  type: INTEGER
  mode: NULLABLE
  description: Recipient's ID
- name: date_created
  type: DATE
  mode: NULLABLE
  description: Date when the contact was created
- name: last_modified_date
  type: DATE
  mode: NULLABLE
  description: Correspnds to Airflow's exec date. \ Means when at the time the job
    run, that was \ most recently when the contact was updated.
