fields:
- description: null
  mode: NULLABLE
  name: dag_id
  type: STRING
- description: null
  mode: NULLABLE
  name: run_id
  type: STRING
- description: null
  mode: NULLABLE
  name: task_id
  type: STRING
- description: null
  mode: NULLABLE
  name: state
  type: STRING
- description: null
  mode: NULLABLE
  name: try_number
  type: INTEGER
- description: null
  mode: NULLABLE
  name: start_date
  type: TIMESTAMP
- description: null
  mode: NULLABLE
  name: end_date
  type: TIMESTAMP
- description: null
  mode: NULLABLE
  name: duration
  type: FLOAT
- description: null
  mode: NULLABLE
  name: job_id
  type: INTEGER
- description: null
  mode: NULLABLE
  name: executor_config
  type: BYTES
- description: null
  mode: NULLABLE
  name: external_executor_id
  type: STRING
- description: null
  mode: NULLABLE
  name: hostname
  type: STRING
- description: null
  mode: NULLABLE
  name: max_tries
  type: INTEGER
- description: null
  mode: NULLABLE
  name: next_kwargs
  type: STRING
- description: null
  mode: NULLABLE
  name: next_method
  type: STRING
- description: null
  mode: NULLABLE
  name: operator
  type: STRING
- description: null
  mode: NULLABLE
  name: pid
  type: INTEGER
- description: null
  mode: NULLABLE
  name: pool
  type: STRING
- description: null
  mode: NULLABLE
  name: pool_slots
  type: INTEGER
- description: null
  mode: NULLABLE
  name: priority_weight
  type: INTEGER
- description: null
  mode: NULLABLE
  name: queue
  type: STRING
- description: null
  mode: NULLABLE
  name: queued_by_job_id
  type: INTEGER
- description: null
  mode: NULLABLE
  name: queued_dttm
  type: TIMESTAMP
- description: null
  mode: NULLABLE
  name: trigger_id
  type: INTEGER
- description: null
  mode: NULLABLE
  name: trigger_timeout
  type: DATETIME
- description: null
  mode: NULLABLE
  name: unixname
  type: STRING
- description: null
  mode: NULLABLE
  name: map_index
  type: INTEGER
