fields:
- mode: NULLABLE
  name: measured_date
  type: DATE
- mode: NULLABLE
  name: measured_month
  type: DATE
- mode: NULLABLE
  name: destination_id
  type: STRING
- mode: NULLABLE
  name: connector_name
  type: STRING
- mode: NULLABLE
  name: table_name
  type: STRING
- mode: NULLABLE
  name: paid_active_rows
  type: INTEGER
- mode: NULLABLE
  name: free_active_rows
  type: INTEGER
- mode: NULLABLE
  name: total_active_rows
  type: INTEGER
