type: BIGCONFIG_FILE

tag_deployments:
  - collection:
      name: Operational Checks
      notification_channels:
        - slack: '#de-bigeye-triage'
    deployments:
      - column_selectors:
        - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_fennec_derived.usage_reporting_clients_last_seen_v1.submission_date
        - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_fennec_derived.usage_reporting_clients_last_seen_v1.usage_profile_id
        - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_fennec_derived.usage_reporting_clients_last_seen_v1.days_seen_bits
        - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_fennec_derived.usage_reporting_clients_last_seen_v1.days_active_bits
        - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_fennec_derived.usage_reporting_clients_last_seen_v1.days_created_profile_bits
        metrics:
          - saved_metric_id: is_not_null
      - column_selectors:
        - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.org_mozilla_ios_fennec_derived.usage_reporting_clients_last_seen_v1.*
        metrics:
          - saved_metric_id: volume
          - saved_metric_id: freshness
