type: BIGCONFIG_FILE

saved_metric_definitions:
  metrics:
  - saved_metric_id: COUNT_ROWS
    metric_type:
      type: PREDEFINED
      predefined_metric: COUNT_ROWS
    metric_name: downloads_with_attribution_v2_row_count
    group_by:
    - download_date
    threshold:
      type: CONSTANT
      lower_bound: 50000.0
    rct_overrides:
    - download_date

tag_deployments:
- collection:
    name: Google Analytics
    description: All GA related data
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.mozilla_org_derived.downloads_with_attribution_v2.*
    metrics:
    - saved_metric_id: COUNT_ROWS
