type: BIGCONFIG_FILE

row_creation_times:
  column_selectors:
  - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.mozilla_org_derived.downloads_with_attribution_v2.download_date

saved_metric_definitions:
  metrics:
  - saved_metric_id: COUNT_ROWS
    metric_type:
      type: PREDEFINED
      predefined_metric: COUNT_ROWS
    metric_name: Row count (#)
    group_by:
    - download_date
    threshold:
      type: CONSTANT
      lower_bound: 50000.0
    lookback:
      lookback_window:
        interval_type: DAYS
        interval_value: -1
      lookback_type: METRIC_TIME
      bucket_size: DAY
    rct_overrides:
    - download_date
    metric_schedule:
      named_schedule:
        name: Default Schedule - 13:00 UTC
tag_deployments:
- collection:
    name: Google Analytics
    description: All checks related to GA tables
  deployments:
  - column_selectors:
    - name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.mozilla_org_derived.downloads_with_attribution_v2.*
    metrics:
    - saved_metric_id: COUNT_ROWS
