fields:
- mode: NULLABLE
  name: name
  type: STRING
- mode: NULLABLE
  name: code
  type: STRING
- mode: NULLABLE
  name: region_name
  type: STRING
- mode: NULLABLE
  name: subregion_name
  type: STRING
- mode: NULLABLE
  name: intermediate_region_name
  type: STRING
