fields:
- mode: NULLABLE
  name: user_id
  type: STRING
- mode: NULLABLE
  name: service
  type: STRING
- mode: NULLABLE
  name: first_service_timestamp
  type: TIMESTAMP
- mode: NULLABLE
  name: first_service_flow
  type: STRING
- mode: NULLABLE
  name: did_register
  type: BOOLEAN
