fields:
- mode: NULLABLE
  name: client_id
  type: STRING
- mode: NULLABLE
  name: normalized_channel
  type: STRING
- mode: NULLABLE
  name: build_version
  type: STRING
- mode: NULLABLE
  name: build_id
  type: STRING
- mode: NULLABLE
  name: channel
  type: STRING
- mode: NULLABLE
  name: crash_time
  type: STRING
- mode: NULLABLE
  name: application
  type: STRING
- mode: NULLABLE
  name: os_name
  type: STRING
- mode: NULLABLE
  name: os_version
  type: STRING
- mode: NULLABLE
  name: architecture
  type: STRING
- mode: NULLABLE
  name: country
  type: STRING
- mode: NULLABLE
  name: experiment_id
  type: STRING
- mode: NULLABLE
  name: experiment_branch
  type: STRING
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - mode: NULLABLE
    name: value
    type: STRING
  mode: REPEATED
  name: experiments
  type: RECORD
- mode: NULLABLE
  name: e10s_enabled
  type: BOOLEAN
- mode: NULLABLE
  name: gfx_compositor
  type: STRING
- mode: NULLABLE
  name: profile_created
  type: INTEGER
- fields:
  - mode: NULLABLE
    name: crashDate
    type: STRING
  - mode: NULLABLE
    name: crashTime
    type: STRING
  - mode: NULLABLE
    name: processType
    type: STRING
  - mode: NULLABLE
    name: hasCrashEnvironment
    type: BOOLEAN
  - fields:
    - mode: NULLABLE
      name: key
      type: STRING
    - mode: NULLABLE
      name: value
      type: STRING
    mode: REPEATED
    name: metadata
    type: RECORD
  - mode: NULLABLE
    name: version
    type: INTEGER
  mode: NULLABLE
  name: payload
  type: RECORD
- mode: NULLABLE
  name: submission_date
  type: DATE
