fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: window_start
  type: TIMESTAMP
  mode: NULLABLE
- name: window_end
  type: TIMESTAMP
  mode: NULLABLE
- name: channel
  type: STRING
  mode: NULLABLE
- name: version
  type: STRING
  mode: NULLABLE
- name: os_name
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: experiment_id
  type: STRING
  mode: NULLABLE
- name: experiment_branch
  type: STRING
  mode: NULLABLE
- name: client_count
  type: BYTES
  mode: NULLABLE
- name: usage_hours
  type: FLOAT
  mode: NULLABLE
- name: count
  type: INTEGER
  mode: NULLABLE
- name: subsession_count
  type: INTEGER
  mode: NULLABLE
- name: main_crashes
  type: INTEGER
  mode: NULLABLE
- name: content_crashes
  type: INTEGER
  mode: NULLABLE
- name: gpu_crashes
  type: INTEGER
  mode: NULLABLE
- name: plugin_crashes
  type: INTEGER
  mode: NULLABLE
- name: gmplugin_crashes
  type: INTEGER
  mode: NULLABLE
- name: content_shutdown_crashes
  type: INTEGER
  mode: NULLABLE
- name: startup_crashes
  type: INTEGER
  mode: NULLABLE
