fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: doc_type
  type: STRING
  mode: NULLABLE
- name: decoded
  type: INTEGER
  mode: NULLABLE
- name: live
  type: INTEGER
  mode: NULLABLE
- name: stable
  type: INTEGER
  mode: NULLABLE
- name: namespace
  type: STRING
  mode: NULLABLE
- name: decoded_nondistinct
  type: INTEGER
  mode: NULLABLE
- name: live_nondistinct
  type: INTEGER
  mode: NULLABLE
