fields:
- name: gclid
  type: STRING
  mode: NULLABLE
- name: conversion_name
  type: STRING
  mode: NULLABLE
- name: activity_date
  type: INTEGER
  mode: NULLABLE
- name: activity_date_timestamp
  type: TIMESTAMP
  mode: NULLABLE
