fields:
- name: id
  type: INTEGER
  mode: NULLABLE
- name: url
  type: STRING
  mode: NULLABLE
- name: name
  type: STRING
  mode: NULLABLE
- name: company
  type: STRING
  mode: NULLABLE
- name: category
  type: STRING
  mode: NULLABLE
- name: total_reviews
  type: INTEGER
  mode: NULLABLE
- name: total_fake_reviews
  type: INTEGER
  mode: NULLABLE
- name: total_legit_reviews
  type: INTEGER
  mode: NULLABLE
- name: created_at
  type: DATETIME
  mode: NULLABLE
- name: updated_at
  type: DATETIME
  mode: NULLABLE
- name: slug
  type: STRING
  mode: NULLABLE
- name: asin
  type: STRING
  mode: NULLABLE
- name: image_url
  type: STRING
  mode: NULLABLE
- name: percentage_fake
  type: NUMERIC
  mode: NULLABLE
- name: vote_up
  type: INTEGER
  mode: NULLABLE
- name: vote_down
  type: INTEGER
  mode: NULLABLE
- name: deleted_by_amazon
  type: BOOLEAN
  mode: NULLABLE
- name: rating
  type: NUMERIC
  mode: NULLABLE
- name: category_id
  type: INTEGER
  mode: NULLABLE
- name: analyses_count
  type: INTEGER
  mode: NULLABLE
- name: domain_ending
  type: STRING
  mode: NULLABLE
- name: company_id
  type: INTEGER
  mode: NULLABLE
- name: visible
  type: BOOLEAN
  mode: NULLABLE
- name: unsupported_categories
  type: STRING
  mode: NULLABLE
