fields:
- description: TODO
  name: segment
  type: STRING
- description: TODO
  name: app_version
  type: STRING
- description: TODO
  name: attribution_medium
  type: STRING
- description: TODO
  name: attribution_source
  type: STRING
- description: TODO
  name: attributed
  type: BOOLEAN
- description: TODO
  name: city
  type: STRING
- description: TODO
  name: country
  type: STRING
- description: TODO
  name: distribution_id
  type: STRING
- description: TODO
  name: first_seen_year
  type: INTEGER
- description: TODO
  name: is_default_browser
  type: BOOLEAN
- description: TODO
  name: app_name
  type: STRING
- description: TODO
  name: channel
  type: STRING
- description: TODO
  name: os
  type: STRING
- description: TODO
  name: os_version
  type: STRING
- description: TODO
  name: os_version_major
  type: INTEGER
- description: TODO
  name: os_version_minor
  type: INTEGER
- description: TODO
  name: submission_date
  type: DATE
- description: TODO
  name: language_name
  type: STRING
- description: TODO
  name: dau
  type: INTEGER
- description: TODO
  name: wau
  type: INTEGER
- description: TODO
  name: mau
  type: INTEGER
- description: TODO
  name: new_profiles
  type: INTEGER
- description: TODO
  name: ad_clicks
  type: INTEGER
- description: TODO
  name: organic_search_count
  type: INTEGER
- description: TODO
  name: search_count
  type: INTEGER
- description: TODO
  name: search_with_ads
  type: INTEGER
- description: TODO
  name: uri_count
  type: INTEGER
- description: TODO
  name: active_hours
  type: INTEGER
- description: TODO
  name: adjust_network
  type: STRING
- description: TODO
  name: install_source
  type: STRING
#  new column
- description: TODO
  name: device_manufacturer
  type: STRING
