fields:
- name: id
  type: INTEGER
  mode: NULLABLE
- name: _fivetran_deleted
  type: BOOLEAN
  mode: NULLABLE
- name: _fivetran_synced
  type: TIMESTAMP
  mode: NULLABLE
- name: _original_estimate
  type: FLOAT
  mode: NULLABLE
- name: _progress
  type: STRING
  mode: NULLABLE
- name: _remaining_estimate
  type: FLOAT
  mode: NULLABLE
- name: _time_spent
  type: FLOAT
  mode: NULLABLE
- name: assignee
  type: STRING
  mode: NULLABLE
- name: created
  type: TIMESTAMP
  mode: NULLABLE
- name: creator
  type: STRING
  mode: NULLABLE
- name: description
  type: STRING
  mode: NULLABLE
- name: due_date
  type: DATE
  mode: NULLABLE
- name: environment
  type: STRING
  mode: NULLABLE
- name: issue_type
  type: INTEGER
  mode: NULLABLE
- name: key
  type: STRING
  mode: NULLABLE
- name: last_viewed
  type: TIMESTAMP
  mode: NULLABLE
- name: original_estimate
  type: FLOAT
  mode: NULLABLE
- name: parent_id
  type: INTEGER
  mode: NULLABLE
- name: priority
  type: INTEGER
  mode: NULLABLE
- name: progress
  type: STRING
  mode: NULLABLE
- name: project
  type: INTEGER
  mode: NULLABLE
- name: remaining_estimate
  type: FLOAT
  mode: NULLABLE
- name: reporter
  type: STRING
  mode: NULLABLE
- name: resolution
  type: INTEGER
  mode: NULLABLE
- name: resolved
  type: TIMESTAMP
  mode: NULLABLE
- name: restrict_to
  type: STRING
  mode: NULLABLE
- name: security_level
  type: INTEGER
  mode: NULLABLE
- name: status
  type: INTEGER
  mode: NULLABLE
- name: status_category_changed
  type: TIMESTAMP
  mode: NULLABLE
- name: summary
  type: STRING
  mode: NULLABLE
- name: time_spent
  type: FLOAT
  mode: NULLABLE
- name: time_tracking
  type: STRING
  mode: NULLABLE
- name: updated
  type: TIMESTAMP
  mode: NULLABLE
- name: votes
  type: STRING
  mode: NULLABLE
- name: work_ratio
  type: FLOAT
  mode: NULLABLE
