fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: client_id
  type: STRING
  mode: NULLABLE
  description: Client ID
- name: sample_id
  type: INTEGER
  mode: NULLABLE
  description: Sample ID
- name: distribution_id
  type: STRING
  mode: NULLABLE
  description: Distribution ID
- name: locale
  type: STRING
  mode: NULLABLE
  description: Locale
- name: app_version
  type: STRING
  mode: NULLABLE
  description: App Version
- name: isp_name
  type: STRING
  mode: NULLABLE
  description: ISP Name
- name: first_seen_date
  type: DATE
  mode: NULLABLE
  description: First Seen Date
- name: attribution_campaign
  type: STRING
  mode: NULLABLE
  description: Attribution Campaign
- name: attribution_content
  type: STRING
  mode: NULLABLE
  description: Attribution Content
- name: attribution_dlsource
  type: STRING
  mode: NULLABLE
  description: Attribution Download Source
- name: attribution_medium
  type: STRING
  mode: NULLABLE
  description: Attribution Medium
- name: attribution_ua
  type: STRING
  mode: NULLABLE
  description: Attribution UA
- name: normalized_channel
  type: STRING
  mode: NULLABLE
  description: Normalized Channel
- name: normalized_os
  type: STRING
  mode: NULLABLE
  description: Normalized Operating System
- name: normalized_os_version
  type: STRING
  mode: NULLABLE
  description: Normalized Operating System Version
- name: country
  type: STRING
  mode: NULLABLE
  description: Country
- name: dau
  type: BOOLEAN
  mode: NULLABLE
  description: DAU - Daily Active User
- name: wau
  type: BOOLEAN
  mode: NULLABLE
  description: WAU - Weekly Active User
- name: mau
  type: BOOLEAN
  mode: NULLABLE
  description: MAU - Monthly Active User
- name: lifecycle_stage
  type: STRING
  mode: NULLABLE
