fields:
- description: A JSON string containing any payload properties not present in the
    schema
  mode: NULLABLE
  name: additional_properties
  type: STRING
- fields:
  - mode: NULLABLE
    name: dark_mode_active
    type: BOOLEAN
  - mode: NULLABLE
    name: firefox_account_prefs_configured
    type: BOOLEAN
  - mode: NULLABLE
    name: has_at_least_one_login_saved_in_the_browser
    type: BOOLEAN
  - mode: NULLABLE
    name: has_at_least_one_self_installed_addon
    type: BOOLEAN
  - mode: NULLABLE
    name: has_at_least_one_self_installed_popular_privacy_security_addon
    type: BOOLEAN
  - mode: NULLABLE
    name: has_at_least_one_self_installed_theme
    type: BOOLEAN
  - mode: NULLABLE
    name: has_firefox_as_default_browser
    type: BOOLEAN
  - mode: NULLABLE
    name: has_more_than_12_active_ticks
    type: BOOLEAN
  - mode: NULLABLE
    name: has_more_than_1_about_preferences_non_default_value_count
    type: BOOLEAN
  - mode: NULLABLE
    name: has_more_than_5_bookmarks
    type: BOOLEAN
  - mode: NULLABLE
    name: has_more_than_5_total_uri_count
    type: BOOLEAN
  - mode: NULLABLE
    name: is_release_channel
    type: BOOLEAN
  - mode: NULLABLE
    name: locale_is_de
    type: BOOLEAN
  - mode: NULLABLE
    name: locale_is_en_us
    type: BOOLEAN
  - mode: NULLABLE
    name: main_monitor_screen_width_gt_1280
    type: BOOLEAN
  - mode: NULLABLE
    name: profile_more_than_60_days_old
    type: BOOLEAN
  mode: NULLABLE
  name: boolean_client_context_features
  type: RECORD
- fields:
  - mode: NULLABLE
    name: about_preferences_non_default_value_count
    type: FLOAT
  - mode: NULLABLE
    name: active_ticks
    type: FLOAT
  - mode: NULLABLE
    name: dark_mode_active
    type: BOOLEAN
  - mode: NULLABLE
    name: firefox_account_prefs_configured
    type: BOOLEAN
  - mode: NULLABLE
    name: has_firefox_as_default_browser
    type: BOOLEAN
  - mode: NULLABLE
    name: locale
    type: STRING
  - mode: NULLABLE
    name: logins_saved_in_the_browser_count
    type: FLOAT
  - mode: NULLABLE
    name: main_monitor_screen_width
    type: FLOAT
  - mode: NULLABLE
    name: profile_age_in_ms
    type: FLOAT
  - mode: NULLABLE
    name: self_installed_addons_count
    type: FLOAT
  - mode: NULLABLE
    name: self_installed_popular_privacy_security_addons_count
    type: FLOAT
  - mode: NULLABLE
    name: self_installed_themes_count
    type: FLOAT
  - mode: NULLABLE
    name: total_bookmarks_count
    type: FLOAT
  - mode: NULLABLE
    name: total_uri_count
    type: FLOAT
  - mode: NULLABLE
    name: update_channel
    type: STRING
  mode: NULLABLE
  name: client_context_features
  type: RECORD
- description: The document ID specified in the URI when the client sent this message
  mode: NULLABLE
  name: document_id
  type: STRING
- mode: REPEATED
  name: features_array_used_in_score_computation
  type: FLOAT
- mode: NULLABLE
  name: impression_id
  type: STRING
- fields:
  - description: Results of a geographic lookup based on the client's IP address
    fields:
    - mode: NULLABLE
      name: city
      type: STRING
    - description: An ISO 3166-1 alpha-2 country code
      mode: NULLABLE
      name: country
      type: STRING
    - description: The specific geo database version used for this lookup
      mode: NULLABLE
      name: db_version
      type: STRING
    - description: First major country subdivision, typically a state, province, or
        county
      mode: NULLABLE
      name: subdivision1
      type: STRING
    - description: Second major country subdivision; not applicable for most countries
      mode: NULLABLE
      name: subdivision2
      type: STRING
    mode: NULLABLE
    name: geo
    type: RECORD
  - description: Headers included in the client's HTTP request
    fields:
    - description: Date HTTP header
      mode: NULLABLE
      name: date
      type: STRING
    - description: DNT (Do Not Track) HTTP header
      mode: NULLABLE
      name: dnt
      type: STRING
    - description: X-Debug-Id HTTP header
      mode: NULLABLE
      name: x_debug_id
      type: STRING
    - description: X-PingSender-Version HTTP header
      mode: NULLABLE
      name: x_pingsender_version
      type: STRING
    - description: X-Source-Tags HTTP header
      mode: NULLABLE
      name: x_source_tags
      type: STRING
    - description: X-Telemetry-Agent HTTP header
      mode: NULLABLE
      name: x_telemetry_agent
      type: STRING
    - description: X-Foxsec-IP-Reputation header
      mode: NULLABLE
      name: x_foxsec_ip_reputation
      type: STRING
    - mode: NULLABLE
      name: parsed_date
      type: TIMESTAMP
    - mode: REPEATED
      name: parsed_x_source_tags
      type: STRING
    mode: NULLABLE
    name: header
    type: RECORD
  - description: Parsed components of the client's user agent string
    fields:
    - mode: NULLABLE
      name: browser
      type: STRING
    - mode: NULLABLE
      name: os
      type: STRING
    - mode: NULLABLE
      name: version
      type: STRING
    mode: NULLABLE
    name: user_agent
    type: RECORD
  - description: Results of ISP lookup based on the client's IP address
    fields:
    - description: The specific geo ISP database version used for this lookup
      mode: NULLABLE
      name: db_version
      type: STRING
    - description: The name of the ISP associated with the client's IP address
      mode: NULLABLE
      name: name
      type: STRING
    - description: The name of a specific business entity associated with the client's
        IP address when available; otherwise the ISP name
      mode: NULLABLE
      name: organization
      type: STRING
    mode: NULLABLE
    name: isp
    type: RECORD
  mode: NULLABLE
  name: metadata
  type: RECORD
- mode: NULLABLE
  name: model_version
  type: FLOAT
- description: Set to "Other" if this message contained an unrecognized app name
  mode: NULLABLE
  name: normalized_app_name
  type: STRING
- description: Set to "Other" if this message contained an unrecognized channel name
  mode: NULLABLE
  name: normalized_channel
  type: STRING
- description: An ISO 3166-1 alpha-2 country code
  mode: NULLABLE
  name: normalized_country_code
  type: STRING
- description: Set to "Other" if this message contained an unrecognized OS name
  mode: NULLABLE
  name: normalized_os
  type: STRING
- mode: NULLABLE
  name: normalized_os_version
  type: STRING
- description: Hashed version of client_id (if present) useful for partitioning; ranges
    from 0 to 99
  mode: NULLABLE
  name: sample_id
  type: INTEGER
- mode: NULLABLE
  name: study_addon_version
  type: STRING
- mode: NULLABLE
  name: study_variation
  type: STRING
- description: Time when the ingestion edge server accepted this message
  mode: NULLABLE
  name: submission_timestamp
  type: TIMESTAMP
