fields:
- name: id
  type: STRING
  mode: NULLABLE
- name: day
  type: DATE
  mode: NULLABLE
- name: ad_partner_id
  type: STRING
  mode: NULLABLE
- name: ad_rule_id
  type: STRING
  mode: NULLABLE
- name: ad_entity_id
  type: STRING
  mode: NULLABLE
- name: ad_keyword_id
  type: STRING
  mode: NULLABLE
- name: impression_renders_count
  type: INTEGER
  mode: NULLABLE
- name: impressions_count
  type: INTEGER
  mode: NULLABLE
- name: clicks_count
  type: INTEGER
  mode: NULLABLE
- name: cost
  type: NUMERIC
  mode: NULLABLE
- name: created_at
  type: DATETIME
  mode: NULLABLE
- name: updated_at
  type: DATETIME
  mode: NULLABLE
- name: placements_count
  type: INTEGER
  mode: NULLABLE
- name: conversions_count
  type: INTEGER
  mode: NULLABLE
- name: placement_renders_count
  type: INTEGER
  mode: NULLABLE
- name: event_sources_counts
  type: STRING
  mode: NULLABLE
- name: chrome_extension_engaged_impression_count
  type: STRING
  mode: NULLABLE
- name: chrome_extension_clicks_count
  type: STRING
  mode: NULLABLE
- name: chrome_extension_engaged_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: chrome_extension_impression_count
  type: STRING
  mode: NULLABLE
- name: chrome_extension_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: chrome_extension_conversions_count
  type: STRING
  mode: NULLABLE
- name: edge_extension_engaged_impression_count
  type: STRING
  mode: NULLABLE
- name: edge_extension_clicks_count
  type: STRING
  mode: NULLABLE
- name: edge_extension_engaged_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: edge_extension_impression_count
  type: STRING
  mode: NULLABLE
- name: edge_extension_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: edge_extension_conversions_count
  type: STRING
  mode: NULLABLE
- name: safari_extension_engaged_impression_count
  type: STRING
  mode: NULLABLE
- name: safari_extension_clicks_count
  type: STRING
  mode: NULLABLE
- name: safari_extension_engaged_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: safari_extension_impression_count
  type: STRING
  mode: NULLABLE
- name: safari_extension_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: safari_extension_conversions_count
  type: STRING
  mode: NULLABLE
- name: firefox_extension_engaged_impression_count
  type: STRING
  mode: NULLABLE
- name: firefox_extension_clicks_count
  type: STRING
  mode: NULLABLE
- name: firefox_extension_engaged_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: firefox_extension_impression_count
  type: STRING
  mode: NULLABLE
- name: firefox_extension_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: firefox_extension_conversions_count
  type: STRING
  mode: NULLABLE
- name: fakespot_engaged_impression_count
  type: STRING
  mode: NULLABLE
- name: fakespot_clicks_count
  type: STRING
  mode: NULLABLE
- name: fakespot_engaged_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: fakespot_impression_count
  type: STRING
  mode: NULLABLE
- name: fakespot_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: fakespot_conversions_count
  type: STRING
  mode: NULLABLE
- name: firefox_sidebar_engaged_impression_count
  type: STRING
  mode: NULLABLE
- name: firefox_sidebar_clicks_count
  type: STRING
  mode: NULLABLE
- name: firefox_sidebar_engaged_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: firefox_sidebar_impression_count
  type: STRING
  mode: NULLABLE
- name: firefox_sidebar_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: firefox_sidebar_conversions_count
  type: STRING
  mode: NULLABLE
- name: geckoview_android_engaged_impression_count
  type: STRING
  mode: NULLABLE
- name: geckoview_android_clicks_count
  type: STRING
  mode: NULLABLE
- name: geckoview_android_engaged_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: geckoview_android_impression_count
  type: STRING
  mode: NULLABLE
- name: geckoview_android_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: geckoview_android_conversions_count
  type: STRING
  mode: NULLABLE
- name: firefox_ios_engaged_impression_count
  type: STRING
  mode: NULLABLE
- name: firefox_ios_clicks_count
  type: STRING
  mode: NULLABLE
- name: firefox_ios_engaged_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: firefox_ios_impression_count
  type: STRING
  mode: NULLABLE
- name: firefox_ios_impression_product_rendered_count
  type: STRING
  mode: NULLABLE
- name: firefox_ios_conversions_count
  type: STRING
  mode: NULLABLE
