fields:
- name: id
  type: STRING
  mode: NULLABLE
- name: day
  type: DATE
  mode: NULLABLE
- name: ad_partner_id
  type: STRING
  mode: NULLABLE
- name: ad_rule_id
  type: STRING
  mode: NULLABLE
- name: ad_entity_id
  type: STRING
  mode: NULLABLE
- name: ad_keyword_id
  type: STRING
  mode: NULLABLE
- name: impression_renders_count
  type: INTEGER
  mode: NULLABLE
- name: impressions_count
  type: INTEGER
  mode: NULLABLE
- name: clicks_count
  type: INTEGER
  mode: NULLABLE
- name: cost
  type: NUMERIC
  mode: NULLABLE
- name: created_at
  type: DATETIME
  mode: NULLABLE
- name: updated_at
  type: DATETIME
  mode: NULLABLE
- name: placements_count
  type: INTEGER
  mode: NULLABLE
- name: conversions_count
  type: INTEGER
  mode: NULLABLE
- name: placement_renders_count
  type: INTEGER
  mode: NULLABLE
