fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: table_catalog
  type: STRING
  mode: NULLABLE
  description: Table Catalog
- name: table_schema
  type: STRING
  mode: NULLABLE
  description: Table Schema
- name: table_type
  type: STRING
  mode: NULLABLE
  description: Table Type
- name: nbr_objects
  type: INTEGER
  mode: NULLABLE
- name: nbr_objects_with_a_description
  type: INTEGER
  mode: NULLABLE
- name: pct_objects_with_a_desc
  type: FLOAT
  mode: NULLABLE
- name: nbr_objects_where_every_col_has_a_non_null_desc
  type: INTEGER
  mode: NULLABLE
- name: pct_objects_where_every_col_has_a_non_null_desc
  type: FLOAT
  mode: NULLABLE
