fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: geo
  type: STRING
  mode: NULLABLE
  description: Geographical Area
- name: user_state
  type: STRING
  mode: NULLABLE
  description: User State
- name: client_count
  type: INTEGER
  mode: NULLABLE
  description: Client Count
- name: search_client_count
  type: INTEGER
  mode: NULLABLE
  description: Search Client Count
- name: sap
  type: INTEGER
  mode: NULLABLE
  description: SAP
- name: search_with_ads
  type: INTEGER
  mode: NULLABLE
  description: Number of Searches with Ads
- name: ad_clicks
  type: INTEGER
  mode: NULLABLE
  description: Number of Ad Clicks
- name: tagged_follow_on
  type: INTEGER
  mode: NULLABLE
  description: Number of Tagged Follow-Ons
- name: tagged_sap
  type: INTEGER
  mode: NULLABLE
  description: Number of Tagged SAP
- name: organic
  type: INTEGER
  mode: NULLABLE
  description: Number of Organic Searches
