fields:
- name: crash_date
  type: DATE
  mode: NULLABLE
- name: abort_message
  type: STRING
  mode: NULLABLE
- name: accessibility
  type: STRING
  mode: NULLABLE
- name: adapter_device_id
  type: STRING
  mode: NULLABLE
- name: adapter_driver_version
  type: STRING
  mode: NULLABLE
- name: adapter_subsys_id
  type: STRING
  mode: NULLABLE
- name: adapter_vendor_id
  type: STRING
  mode: NULLABLE
- name: additional_minidumps
  type: STRING
  mode: REPEATED
- name: addons
  type: STRING
  mode: REPEATED
- name: addons_checked
  type: BOOLEAN
  mode: NULLABLE
- name: address
  type: STRING
  mode: NULLABLE
- name: android_board
  type: STRING
  mode: NULLABLE
- name: android_brand
  type: STRING
  mode: NULLABLE
- name: android_cpu_abi
  type: STRING
  mode: NULLABLE
- name: android_cpu_abi2
  type: STRING
  mode: NULLABLE
- name: android_device
  type: STRING
  mode: NULLABLE
- name: android_hardware
  type: STRING
  mode: NULLABLE
- name: android_manufacturer
  type: STRING
  mode: NULLABLE
- name: android_model
  type: STRING
  mode: NULLABLE
- name: android_version
  type: STRING
  mode: NULLABLE
- name: app_init_dlls
  type: STRING
  mode: NULLABLE
- name: app_notes
  type: STRING
  mode: NULLABLE
- name: available_physical_memory
  type: STRING
  mode: NULLABLE
- name: available_virtual_memory
  type: STRING
  mode: NULLABLE
- name: bios_manufacturer
  type: STRING
  mode: NULLABLE
- name: build_id
  type: STRING
  mode: NULLABLE
- name: classifications
  type: RECORD
  mode: NULLABLE
  fields:
  - name: jit
    type: RECORD
    mode: NULLABLE
    fields:
    - name: category
      type: STRING
      mode: NULLABLE
    - name: category_return_code
      type: STRING
      mode: NULLABLE
  - name: skunk_works
    type: RECORD
    mode: NULLABLE
    fields:
    - name: classification
      type: STRING
      mode: NULLABLE
    - name: classification_data
      type: STRING
      mode: NULLABLE
    - name: classification_version
      type: STRING
      mode: NULLABLE
  - name: support
    type: RECORD
    mode: NULLABLE
    fields:
    - name: classification
      type: STRING
      mode: NULLABLE
    - name: classification_data
      type: STRING
      mode: NULLABLE
    - name: classification_version
      type: STRING
      mode: NULLABLE
- name: contains_memory_report
  type: STRING
  mode: NULLABLE
- name: cpu_arch
  type: STRING
  mode: NULLABLE
- name: cpu_info
  type: STRING
  mode: NULLABLE
- name: cpu_microcode_version
  type: STRING
  mode: NULLABLE
- name: crash_id
  type: STRING
  mode: NULLABLE
- name: date
  type: STRING
  mode: NULLABLE
- name: dom_ipc_enabled
  type: STRING
  mode: NULLABLE
- name: e10s_cohort
  type: STRING
  mode: NULLABLE
- name: flash_version
  type: STRING
  mode: NULLABLE
- name: gmp_plugin
  type: STRING
  mode: NULLABLE
- name: graphics_critical_error
  type: STRING
  mode: NULLABLE
- name: graphics_startup_test
  type: STRING
  mode: NULLABLE
- name: hang_type
  type: INTEGER
  mode: NULLABLE
- name: install_age
  type: INTEGER
  mode: NULLABLE
- name: ipc_channel_error
  type: STRING
  mode: NULLABLE
- name: ipc_fatal_error_msg
  type: STRING
  mode: NULLABLE
- name: ipc_fatal_error_protocol
  type: STRING
  mode: NULLABLE
- name: ipc_message_name
  type: STRING
  mode: NULLABLE
- name: ipc_system_error
  type: STRING
  mode: NULLABLE
- name: is_garbage_collecting
  type: STRING
  mode: NULLABLE
- name: java_stack_trace
  type: STRING
  mode: NULLABLE
- name: jit_category
  type: STRING
  mode: NULLABLE
- name: json_dump
  type: RECORD
  mode: NULLABLE
  fields:
  - name: crash_info
    type: RECORD
    mode: NULLABLE
    fields:
    - name: address
      type: STRING
      mode: NULLABLE
    - name: crashing_thread
      type: INTEGER
      mode: NULLABLE
    - name: type
      type: STRING
      mode: NULLABLE
  - name: crashing_thread
    type: RECORD
    mode: NULLABLE
    fields:
    - name: frames
      type: RECORD
      mode: REPEATED
      fields:
      - name: file
        type: STRING
        mode: NULLABLE
      - name: frame
        type: INTEGER
        mode: NULLABLE
      - name: function
        type: STRING
        mode: NULLABLE
      - name: function_offset
        type: STRING
        mode: NULLABLE
      - name: line
        type: INTEGER
        mode: NULLABLE
      - name: module
        type: STRING
        mode: NULLABLE
      - name: module_offset
        type: STRING
        mode: NULLABLE
      - name: offset
        type: STRING
        mode: NULLABLE
    - name: threads_index
      type: INTEGER
      mode: NULLABLE
    - name: total_frames
      type: INTEGER
      mode: NULLABLE
  - name: largest_free_vm_block
    type: STRING
    mode: NULLABLE
  - name: main_module
    type: INTEGER
    mode: NULLABLE
  - name: modules
    type: RECORD
    mode: REPEATED
    fields:
    - name: base_addr
      type: STRING
      mode: NULLABLE
    - name: code_id
      type: STRING
      mode: NULLABLE
    - name: debug_file
      type: STRING
      mode: NULLABLE
    - name: debug_id
      type: STRING
      mode: NULLABLE
    - name: end_addr
      type: STRING
      mode: NULLABLE
    - name: filename
      type: STRING
      mode: NULLABLE
    - name: loaded_symbols
      type: BOOLEAN
      mode: NULLABLE
    - name: missing_symbols
      type: BOOLEAN
      mode: NULLABLE
    - name: symbol_disk_cache_hit
      type: BOOLEAN
      mode: NULLABLE
    - name: symbol_url
      type: STRING
      mode: NULLABLE
    - name: version
      type: STRING
      mode: NULLABLE
  - name: pid
    type: INTEGER
    mode: NULLABLE
  - name: status
    type: STRING
    mode: NULLABLE
  - name: system_info
    type: RECORD
    mode: NULLABLE
    fields:
    - name: cpu_arch
      type: STRING
      mode: NULLABLE
    - name: cpu_count
      type: INTEGER
      mode: NULLABLE
    - name: cpu_info
      type: STRING
      mode: NULLABLE
    - name: os
      type: STRING
      mode: NULLABLE
    - name: os_ver
      type: STRING
      mode: NULLABLE
  - name: thread_count
    type: INTEGER
    mode: NULLABLE
  - name: threads
    type: RECORD
    mode: REPEATED
    fields:
    - name: frame_count
      type: INTEGER
      mode: NULLABLE
    - name: frames
      type: RECORD
      mode: REPEATED
      fields:
      - name: file
        type: STRING
        mode: NULLABLE
      - name: frame
        type: INTEGER
        mode: NULLABLE
      - name: function
        type: STRING
        mode: NULLABLE
      - name: function_offset
        type: STRING
        mode: NULLABLE
      - name: line
        type: INTEGER
        mode: NULLABLE
      - name: module
        type: STRING
        mode: NULLABLE
      - name: module_offset
        type: STRING
        mode: NULLABLE
      - name: offset
        type: STRING
        mode: NULLABLE
  - name: tiny_block_size
    type: STRING
    mode: NULLABLE
  - name: write_combine_size
    type: STRING
    mode: NULLABLE
- name: last_crash
  type: INTEGER
  mode: NULLABLE
- name: memory_measures
  type: RECORD
  mode: NULLABLE
  fields:
  - name: explicit
    type: INTEGER
    mode: NULLABLE
  - name: gfx_textures
    type: INTEGER
    mode: NULLABLE
  - name: ghost_windows
    type: INTEGER
    mode: NULLABLE
  - name: heap_allocated
    type: INTEGER
    mode: NULLABLE
  - name: heap_overhead
    type: INTEGER
    mode: NULLABLE
  - name: heap_unclassified
    type: INTEGER
    mode: NULLABLE
  - name: host_object_urls
    type: INTEGER
    mode: NULLABLE
  - name: images
    type: INTEGER
    mode: NULLABLE
  - name: js_main_runtime
    type: INTEGER
    mode: NULLABLE
  - name: private
    type: INTEGER
    mode: NULLABLE
  - name: resident
    type: INTEGER
    mode: NULLABLE
  - name: resident_unique
    type: INTEGER
    mode: NULLABLE
  - name: system_heap_allocated
    type: INTEGER
    mode: NULLABLE
  - name: top_none_detached
    type: INTEGER
    mode: NULLABLE
  - name: vsize
    type: INTEGER
    mode: NULLABLE
  - name: vsize_max_contiguous
    type: INTEGER
    mode: NULLABLE
- name: memory_report
  type: RECORD
  mode: NULLABLE
  fields:
  - name: hasMozMallocUsableSize
    type: BOOLEAN
    mode: NULLABLE
  - name: reports
    type: RECORD
    mode: REPEATED
    fields:
    - name: amount
      type: INTEGER
      mode: NULLABLE
    - name: description
      type: STRING
      mode: NULLABLE
    - name: kind
      type: INTEGER
      mode: NULLABLE
    - name: path
      type: STRING
      mode: NULLABLE
    - name: process
      type: STRING
      mode: NULLABLE
    - name: units
      type: INTEGER
      mode: NULLABLE
  - name: version
    type: INTEGER
    mode: NULLABLE
- name: moz_crash_reason
  type: STRING
  mode: NULLABLE
- name: oom_allocation_size
  type: STRING
  mode: NULLABLE
- name: platform
  type: STRING
  mode: NULLABLE
- name: platform_pretty_version
  type: STRING
  mode: NULLABLE
- name: platform_version
  type: STRING
  mode: NULLABLE
- name: plugin_filename
  type: STRING
  mode: NULLABLE
- name: plugin_name
  type: STRING
  mode: NULLABLE
- name: plugin_version
  type: STRING
  mode: NULLABLE
- name: process_type
  type: STRING
  mode: NULLABLE
- name: processor_notes
  type: STRING
  mode: NULLABLE
- name: product
  type: STRING
  mode: NULLABLE
- name: productid
  type: STRING
  mode: NULLABLE
- name: proto_signature
  type: STRING
  mode: NULLABLE
- name: reason
  type: STRING
  mode: NULLABLE
- name: release_channel
  type: STRING
  mode: NULLABLE
- name: safe_mode
  type: STRING
  mode: NULLABLE
- name: shutdown_progress
  type: STRING
  mode: NULLABLE
- name: signature
  type: STRING
  mode: NULLABLE
- name: startup_crash
  type: STRING
  mode: NULLABLE
- name: submitted_from_infobar
  type: STRING
  mode: NULLABLE
- name: theme
  type: STRING
  mode: NULLABLE
- name: topmost_filenames
  type: STRING
  mode: NULLABLE
- name: total_physical_memory
  type: STRING
  mode: NULLABLE
- name: total_virtual_memory
  type: STRING
  mode: NULLABLE
- name: uptime
  type: INTEGER
  mode: NULLABLE
- name: user_comments
  type: STRING
  mode: NULLABLE
- name: useragent_locale
  type: STRING
  mode: NULLABLE
- name: uuid
  type: STRING
  mode: NULLABLE
- name: version
  type: STRING
  mode: NULLABLE
- name: winsock_lsp
  type: STRING
  mode: NULLABLE
- name: minidump_sha256_hash
  type: STRING
  mode: NULLABLE
- name: dom_fission_enabled
  type: STRING
  mode: NULLABLE
