fields:
- name: client_id
  type: STRING
  mode: NULLABLE
- name: submission_date
  type: DATE
  mode: NULLABLE
- name: source
  type: STRING
  mode: NULLABLE
- name: device
  type: STRING
  mode: NULLABLE
- name: normalized_engine
  type: STRING
  mode: NULLABLE
- name: normalized_app_name
  type: STRING
  mode: NULLABLE
- name: os
  type: STRING
  mode: NULLABLE
- name: country
  type: STRING
  mode: NULLABLE
- name: searches
  type: INTEGER
  mode: NULLABLE
- name: search_with_ads
  type: INTEGER
  mode: NULLABLE
- name: ad_click
  type: INTEGER
  mode: NULLABLE
- name: tagged_sap
  type: INTEGER
  mode: NULLABLE
- name: tagged_follow_on
  type: INTEGER
  mode: NULLABLE
