fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Submission Date
- name: os_installation_year
  type: FLOAT
  mode: NULLABLE
  description: OS Installation Year
- name: nbr_unique_clients_uninstalling
  type: INTEGER
  mode: NULLABLE
  description: Count of unique clients uninstalling
